//go:build go1.22

// Package termite provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package termite

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for FinishReason.
const (
	FinishReasonContentFilter FinishReason = "content_filter"
	FinishReasonFunctionCall  FinishReason = "function_call"
	FinishReasonLength        FinishReason = "length"
	FinishReasonStop          FinishReason = "stop"
	FinishReasonToolCalls     FinishReason = "tool_calls"
)

// Defines values for GenerateChunkObject.
const (
	GenerateChunkObjectChatCompletionChunk GenerateChunkObject = "chat.completion.chunk"
)

// Defines values for GenerateResponseObject.
const (
	GenerateResponseObjectChatCompletion GenerateResponseObject = "chat.completion"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for MediaContentPartType.
const (
	MediaContentPartTypeMedia MediaContentPartType = "media"
)

// Defines values for RecognizerCapability.
const (
	RecognizerCapabilityAnswers        RecognizerCapability = "answers"
	RecognizerCapabilityJsonExtraction RecognizerCapability = "json_extraction"
	RecognizerCapabilityLabels         RecognizerCapability = "labels"
	RecognizerCapabilityRelations      RecognizerCapability = "relations"
	RecognizerCapabilityZeroshot       RecognizerCapability = "zeroshot"
)

// Defines values for Role.
const (
	RoleAssistant Role = "assistant"
	RoleSystem    Role = "system"
	RoleTool      Role = "tool"
	RoleUser      Role = "user"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// Defines values for ToolType.
const (
	ToolTypeFunction ToolType = "function"
)

// Defines values for ToolCallType.
const (
	ToolCallTypeFunction ToolCallType = "function"
)

// Defines values for ToolCallDeltaType.
const (
	ToolCallDeltaTypeFunction ToolCallDeltaType = "function"
)

// Defines values for ToolChoice0.
const (
	ToolChoice0Auto     ToolChoice0 = "auto"
	ToolChoice0None     ToolChoice0 = "none"
	ToolChoice0Required ToolChoice0 = "required"
)

// Defines values for ToolChoice1Type.
const (
	ToolChoice1TypeFunction ToolChoice1Type = "function"
)

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	// Content Message content. Supports two formats:
	// - Simple string: "Hello, how are you?"
	// - Array of content parts (OpenAI multimodal format): [{"type": "text", "text": "Hello"}]
	Content ChatMessageContent `json:"content,omitempty,omitzero"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role"`

	// ToolCallId ID of the tool call this message is responding to (only for role=tool)
	ToolCallId string `json:"tool_call_id,omitempty,omitzero"`

	// ToolCalls Tool calls made by the assistant (only for role=assistant)
	ToolCalls []ToolCall `json:"tool_calls,omitempty,omitzero"`
}

// ChatMessageContent Message content. Supports two formats:
// - Simple string: "Hello, how are you?"
// - Array of content parts (OpenAI multimodal format): [{"type": "text", "text": "Hello"}]
type ChatMessageContent struct {
	union json.RawMessage
}

// ChatMessageContent0 Simple text content
type ChatMessageContent0 = string

// ChatMessageContent1 Array of content parts (OpenAI multimodal format)
type ChatMessageContent1 = []ContentPart

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapDurationMs Overlap duration in ms between audio chunks (default: 0)
	OverlapDurationMs int `json:"overlap_duration_ms,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`

	// WindowDurationMs Window duration in ms for audio chunking (default: 30000)
	WindowDurationMs int `json:"window_duration_ms,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Input Input content to chunk. Supports two formats:
	// - Text string: `"This is a long document..."` (backward compatible)
	// - ContentPart: `{"type": "media", "data": "<base64>", "mime_type": "audio/wav"}`
	// - ContentPart: `{"type": "text", "text": "..."}`
	Input ChunkRequest_Input `json:"input,omitempty,omitzero"`

	// Text DEPRECATED: Use 'input' instead. Text to chunk.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Text string `json:"text,omitempty,omitzero"`
}

// ChunkRequestInput0 Text to chunk (backward compatible)
type ChunkRequestInput0 = string

// ChunkRequest_Input Input content to chunk. Supports two formats:
// - Text string: `"This is a long document..."` (backward compatible)
// - ContentPart: `{"type": "media", "data": "<base64>", "mime_type": "audio/wav"}`
// - ContentPart: `{"type": "text", "text": "..."}`
type ChunkRequest_Input struct {
	union json.RawMessage
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// ClassifyRequest defines model for ClassifyRequest.
type ClassifyRequest struct {
	// HypothesisTemplate Custom hypothesis template for NLI-based classification.
	// Use "{}" as placeholder for the label.
	// Default: "This example is {}."
	HypothesisTemplate string `json:"hypothesis_template,omitempty,omitzero"`

	// Labels Candidate labels for zero-shot classification.
	// The model will predict which label(s) best describe each text.
	Labels []string `json:"labels"`

	// Model Name of classifier model from models_dir/classifiers/
	Model string `json:"model"`

	// MultiLabel If true, allows multiple labels per text (independent scoring).
	// If false (default), scores are normalized across labels.
	MultiLabel bool `json:"multi_label,omitempty,omitzero"`

	// Texts Texts to classify
	Texts []string `json:"texts"`
}

// ClassifyResponse defines model for ClassifyResponse.
type ClassifyResponse struct {
	// Classifications Array of classification results (one per input text).
	// Each result is an array of ClassifyResult sorted by score descending.
	Classifications [][]ClassifyResult `json:"classifications"`

	// Model Name of model used for classification
	Model string `json:"model"`
}

// ClassifyResult defines model for ClassifyResult.
type ClassifyResult struct {
	// Label The predicted class/category
	Label string `json:"label"`

	// Score Confidence score (0.0 to 1.0)
	Score float32 `json:"score"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl string `json:"api_url"`

	// BackendPriority Backend priority order for model loading with optional device specifiers.
	// Format: `backend` or `backend:device` where device defaults to `auto`.
	//
	// Termite tries entries in order and uses the first available backend+device
	// combination that supports the model.
	//
	// **Backends** (depend on build tags):
	// - `go` - Pure Go inference (always available, CPU only, slowest)
	// - `onnx` - ONNX Runtime (requires -tags="onnx,ORT", fastest)
	// - `xla` - GoMLX XLA (requires -tags="xla,XLA", TPU/CUDA/CPU)
	//
	// **Devices**:
	// - `auto` - Auto-detect best available (default)
	// - `cuda` - NVIDIA CUDA GPU
	// - `coreml` - Apple CoreML (macOS only, used by ONNX)
	// - `tpu` - Google TPU (used by XLA)
	// - `cpu` - Force CPU only
	//
	// **Examples**:
	// - `["onnx", "xla", "go"]` - Try backends with auto device detection
	// - `["onnx:cuda", "xla:tpu", "onnx:cpu", "go"]` - Prefer GPU, fall back to CPU
	// - `["onnx:coreml", "go"]` - macOS with CoreML acceleration
	BackendPriority []string                           `json:"backend_priority,omitempty,omitzero"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (eager loading).
	// Defaults to "5m" (lazy loading) like Ollama. Set to "0" to explicitly enable eager loading
	// where all models are loaded at startup and never unloaded.
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive>0 (default "5m"): lazy loading (load on demand, unload after idle)
	// - If keep_alive="0": eager loading (load at startup, never unload)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	// - `{models_dir}/recognizers/` - Recognition models (ONNX)
	// - `{models_dir}/rewriters/` - Seq2Seq rewriter models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// PoolSize Number of concurrent inference pipelines per model. Each pipeline loads
	// a copy of the model, so higher values use more memory but allow more
	// concurrent requests. Set to 0 to use the default (min(NumCPU, 4)).
	PoolSize int `json:"pool_size,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "BAAI/bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal input (text, image URL, or inline media)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// ExtractFieldValue defines model for ExtractFieldValue.
type ExtractFieldValue struct {
	// End Character offset where value ends (only present when include_spans=true)
	End int `json:"end,omitempty,omitzero"`

	// Score Confidence score (only present when include_confidence=true)
	Score float32 `json:"score,omitempty,omitzero"`

	// Start Character offset where value begins (only present when include_spans=true)
	Start int `json:"start,omitempty,omitzero"`

	// Value The extracted text value
	Value string `json:"value"`
}

// ExtractRequest defines model for ExtractRequest.
type ExtractRequest struct {
	// FlatNer If true, don't allow nested/overlapping entities
	FlatNer bool `json:"flat_ner,omitempty,omitzero"`

	// IncludeConfidence If true, include confidence scores in output
	IncludeConfidence bool `json:"include_confidence,omitempty,omitzero"`

	// IncludeSpans If true, include character offset spans in output
	IncludeSpans bool `json:"include_spans,omitempty,omitzero"`

	// Model Name of recognizer model with json_extraction capability
	Model string `json:"model"`

	// Schema Extraction schema mapping structure names to field definitions.
	// Each field is defined as "field_name::type" where type is "str" or "list".
	// Optional choice fields: "field_name::[opt1|opt2]::str".
	// If no type is specified, defaults to "str".
	Schema map[string][]string `json:"schema"`

	// Texts Texts to extract structured data from
	Texts []string `json:"texts"`

	// Threshold Score threshold for span extraction (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ExtractResponse defines model for ExtractResponse.
type ExtractResponse struct {
	// Model Name of model used for extraction
	Model string `json:"model"`

	// Results Array of extraction results (one per input text).
	// Each result maps structure names to arrays of extracted instances.
	// Each instance maps field names to ExtractFieldValue (for ::str fields)
	// or arrays of ExtractFieldValue (for ::list fields).
	Results []map[string][]map[string]interface{} `json:"results"`
}

// FinishReason Reason why generation stopped
type FinishReason string

// FunctionDefinition Definition of a function that can be called by the model
type FunctionDefinition struct {
	// Description A description of what the function does
	Description string `json:"description,omitempty,omitzero"`

	// Name The name of the function to call
	Name string `json:"name"`

	// Parameters JSON Schema object describing the function parameters
	Parameters map[string]interface{} `json:"parameters,omitempty,omitzero"`

	// Strict Whether to enforce strict parameter validation
	Strict bool `json:"strict,omitempty,omitzero"`
}

// GenerateChoice defines model for GenerateChoice.
type GenerateChoice struct {
	// FinishReason Reason why generation stopped
	FinishReason FinishReason `json:"finish_reason"`

	// Index Index of this choice in the list
	Index int `json:"index"`

	// Logprobs Log probability information (not supported, always null)
	Logprobs map[string]interface{} `json:"logprobs,omitzero"`
	Message  GenerateMessage        `json:"message"`
}

// GenerateChunk Streaming generation chunk (SSE event data)
type GenerateChunk struct {
	Choices []GenerateChunkChoice `json:"choices"`
	Created int                   `json:"created"`
	Id      string                `json:"id"`
	Model   string                `json:"model"`
	Object  GenerateChunkObject   `json:"object"`
}

// GenerateChunkObject defines model for GenerateChunk.Object.
type GenerateChunkObject string

// GenerateChunkChoice defines model for GenerateChunkChoice.
type GenerateChunkChoice struct {
	// Delta Delta content for streaming
	Delta GenerateDelta `json:"delta"`

	// FinishReason Reason why generation stopped
	FinishReason FinishReason `json:"finish_reason,omitempty,omitzero"`
	Index        int          `json:"index"`
}

// GenerateDelta Delta content for streaming
type GenerateDelta struct {
	// Content Token content delta
	Content string `json:"content,omitzero"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role,omitempty,omitzero"`

	// ToolCalls Tool call deltas for streaming tool calls
	ToolCalls []ToolCallDelta `json:"tool_calls,omitempty,omitzero"`
}

// GenerateMessage defines model for GenerateMessage.
type GenerateMessage struct {
	// Content The generated message content (null when tool_calls is present)
	Content string `json:"content,omitzero"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role"`

	// ToolCalls Tool calls made by the model (only present when finish_reason is tool_calls)
	ToolCalls []ToolCall `json:"tool_calls,omitempty,omitzero"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// MaxTokens Maximum tokens to generate
	MaxTokens int `json:"max_tokens,omitempty,omitzero"`

	// Messages Conversation messages (OpenAI-compatible format)
	Messages []ChatMessage `json:"messages"`

	// Model Name of the generator model from models_dir/generators/
	Model string `json:"model"`

	// Stream If true, partial message deltas will be sent as SSE events
	Stream bool `json:"stream,omitempty,omitzero"`

	// Temperature Sampling temperature (0.0 = deterministic, higher = more random)
	Temperature float32 `json:"temperature,omitempty,omitzero"`

	// ToolChoice Controls how the model uses tools. Options:
	// - "auto": Model decides whether to call a tool (default)
	// - "none": Model will not call any tools
	// - "required": Model must call at least one tool
	// - object: Force a specific function to be called
	ToolChoice ToolChoice `json:"tool_choice,omitempty,omitzero"`

	// Tools List of tools (functions) the model can call.
	// Only supported by models with tool_call_format configured.
	Tools []Tool `json:"tools,omitempty,omitzero"`

	// TopK Top-k sampling (Termite extension, not in OpenAI API)
	TopK int `json:"top_k,omitempty,omitzero"`

	// TopP Nucleus sampling probability
	TopP float32 `json:"top_p,omitempty,omitzero"`
}

// GenerateResponse OpenAI-compatible chat completion response
type GenerateResponse struct {
	// Choices List of completion choices (currently always 1)
	Choices []GenerateChoice `json:"choices"`

	// Created Unix timestamp (seconds) when the completion was created
	Created int `json:"created"`

	// Id A unique identifier for the chat completion
	Id string `json:"id"`

	// Model Model used for generation
	Model string `json:"model"`

	// Object The object type, always "chat.completion"
	Object GenerateResponseObject `json:"object"`
	Usage  GenerateUsage          `json:"usage"`
}

// GenerateResponseObject The object type, always "chat.completion"
type GenerateResponseObject string

// GenerateUsage defines model for GenerateUsage.
type GenerateUsage struct {
	// CompletionTokens Number of tokens in the completion
	CompletionTokens int `json:"completion_tokens"`

	// PromptTokens Number of tokens in the prompt
	PromptTokens int `json:"prompt_tokens"`

	// TotalTokens Total tokens used (prompt + completion)
	TotalTokens int `json:"total_tokens"`
}

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// MediaContentPart Inline binary media content (audio, image, etc.)
type MediaContentPart struct {
	// Data Base64-encoded binary data
	Data []byte `json:"data"`

	// MimeType MIME type (audio/wav, image/gif, image/png, etc.)
	MimeType string               `json:"mime_type"`
	Type     MediaContentPartType `json:"type"`
}

// MediaContentPartType defines model for MediaContentPart.Type.
type MediaContentPartType string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Classifiers Available zero-shot classification models
	Classifiers []string `json:"classifiers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Extractors Available GLiNER extractor models (zero-shot recognition with custom labels)
	Extractors []string `json:"extractors,omitempty,omitzero"`

	// Generators Available generator/LLM models from models_dir/generators/
	Generators []string `json:"generators"`

	// Readers Available reader/OCR models from models_dir/readers/
	Readers []string `json:"readers"`

	// RecognizerInfo Detailed information about recognizer models including capabilities.
	// Map of model name to model info. Use this to determine what capabilities
	// each recognizer supports (labels, zeroshot, relations, answers).
	RecognizerInfo map[string]RecognizerModelInfo `json:"recognizer_info,omitempty,omitzero"`

	// Recognizers Available recognizer models from models_dir/recognizers/
	Recognizers []string `json:"recognizers"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`

	// Rewriters Available Seq2Seq rewriter models from models_dir/rewriters/
	Rewriters []string `json:"rewriters"`

	// Transcribers Available transcriber/speech-to-text models from models_dir/transcribers/
	Transcribers []string `json:"transcribers"`
}

// ReadRequest defines model for ReadRequest.
type ReadRequest struct {
	// Images Images to read text from. Supports:
	// - Data URIs: `data:image/png;base64,...`
	// - URLs (if content_security allows)
	Images []ImageURL `json:"images"`

	// MaxTokens Maximum tokens to generate
	MaxTokens int `json:"max_tokens,omitempty,omitzero"`

	// Model Name of reader model from models_dir/readers/
	Model string `json:"model"`

	// Prompt Optional task prompt for document understanding models.
	// - TrOCR: Not used (pure OCR)
	// - Donut CORD: "<s_cord-v2>" for receipt parsing
	// - Donut DocVQA: "<s_docvqa><s_question>What is the total?</s_question><s_answer>"
	// - Florence-2: "<OCR>" for OCR, "<CAPTION>" for captioning
	Prompt string `json:"prompt,omitempty,omitzero"`
}

// ReadResponse defines model for ReadResponse.
type ReadResponse struct {
	// Model Name of model used for reading
	Model string `json:"model"`

	// Results Array of read results (one per input image)
	Results []ReadResult `json:"results"`
}

// ReadResult defines model for ReadResult.
type ReadResult struct {
	// Fields Structured fields extracted by document understanding models (Donut, Florence-2).
	// Fields are flattened with dot notation for nested structures.
	// Only present for models that output structured data.
	Fields map[string]string `json:"fields,omitempty,omitzero"`

	// Text Extracted text from the image
	Text string `json:"text"`
}

// RecognizeEntity defines model for RecognizeEntity.
type RecognizeEntity struct {
	// End Character offset where entity ends (exclusive)
	End int `json:"end"`

	// Label Entity type (PER, ORG, LOC, MISC)
	Label string `json:"label"`

	// Score Confidence score (0.0 to 1.0)
	Score float32 `json:"score"`

	// Start Character offset where entity begins
	Start int `json:"start"`

	// Text The entity text
	Text string `json:"text"`
}

// RecognizeRequest defines model for RecognizeRequest.
type RecognizeRequest struct {
	// Labels Custom entity labels to extract (GLiNER models only).
	// When using a GLiNER model, you can specify any entity types to extract,
	// enabling zero-shot NER without model retraining.
	// If not provided, the model's default labels are used.
	Labels []string `json:"labels,omitempty,omitzero"`

	// Model Name of recognizer model from models_dir/recognizers/
	Model string `json:"model"`

	// RelationLabels Relation types to extract (for models with 'relations' capability).
	// Only used when the model supports relation extraction (GLiNER multitask, REBEL).
	// If not provided, the model extracts all relations it can detect.
	RelationLabels []string `json:"relation_labels,omitempty,omitzero"`

	// Texts Texts to extract entities from
	Texts []string `json:"texts"`
}

// RecognizeResponse defines model for RecognizeResponse.
type RecognizeResponse struct {
	// Entities Array of entity arrays (one per input text)
	Entities [][]RecognizeEntity `json:"entities"`

	// Model Name of model used for NER
	Model string `json:"model"`

	// Relations Array of relation arrays (one per input text).
	// Only present when using a model with 'relations' capability (GLiNER multitask, REBEL).
	Relations [][]Relation `json:"relations,omitempty,omitzero"`
}

// RecognizerCapability Capability that a recognizer model supports:
// - labels: Entity extraction (NER) - extracts labeled spans like PER, ORG, LOC
// - zeroshot: Supports arbitrary labels at inference time (GLiNER models)
// - relations: Relation extraction between entities (GLiNER multitask, REBEL)
// - answers: Extractive question answering (GLiNER multitask)
// - json_extraction: Structured JSON extraction from text (GLiNER2)
type RecognizerCapability string

// RecognizerModelInfo Detailed information about a recognizer model
type RecognizerModelInfo struct {
	// Capabilities List of capabilities this recognizer model supports
	Capabilities []RecognizerCapability `json:"capabilities,omitempty,omitzero"`
}

// Relation defines model for Relation.
type Relation struct {
	Head RecognizeEntity `json:"head"`

	// Label The relationship type
	Label string `json:"label"`

	// Score Confidence score for the relation (0.0 to 1.0)
	Score float32         `json:"score"`
	Tail  RecognizeEntity `json:"tail"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// RewriteRequest defines model for RewriteRequest.
type RewriteRequest struct {
	// Inputs Input texts to rewrite/transform
	Inputs []string `json:"inputs"`

	// Model Name of Seq2Seq rewriter model from models_dir/rewriters/
	Model string `json:"model"`
}

// RewriteResponse defines model for RewriteResponse.
type RewriteResponse struct {
	// Model Name of model used for rewriting
	Model string `json:"model"`

	// Texts Rewritten texts (array of arrays, one per input, multiple per beam)
	Texts [][]string `json:"texts"`
}

// Role The role of a message sender in a conversation
type Role string

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// Tool A tool (function) that the model can call
type Tool struct {
	// Function Definition of a function that can be called by the model
	Function FunctionDefinition `json:"function"`

	// Type The type of tool (currently only "function" is supported)
	Type ToolType `json:"type"`
}

// ToolType The type of tool (currently only "function" is supported)
type ToolType string

// ToolCall A tool call made by the model
type ToolCall struct {
	// Function The function called by the model
	Function ToolCallFunction `json:"function"`

	// Id Unique identifier for this tool call
	Id string `json:"id"`

	// Type The type of tool call (currently only "function")
	Type ToolCallType `json:"type"`
}

// ToolCallType The type of tool call (currently only "function")
type ToolCallType string

// ToolCallDelta Incremental tool call data for streaming
type ToolCallDelta struct {
	// Function Incremental function call data for streaming
	Function ToolCallFunctionDelta `json:"function,omitempty,omitzero"`

	// Id Unique identifier (only in first delta for this index)
	Id string `json:"id,omitempty,omitzero"`

	// Index Index of the tool call in the array
	Index int `json:"index,omitempty,omitzero"`

	// Type The type of tool call (only in first delta)
	Type ToolCallDeltaType `json:"type,omitempty,omitzero"`
}

// ToolCallDeltaType The type of tool call (only in first delta)
type ToolCallDeltaType string

// ToolCallFunction The function called by the model
type ToolCallFunction struct {
	// Arguments JSON string of the arguments to the function
	Arguments string `json:"arguments"`

	// Name The name of the function called
	Name string `json:"name"`
}

// ToolCallFunctionDelta Incremental function call data for streaming
type ToolCallFunctionDelta struct {
	// Arguments Incremental arguments JSON string
	Arguments string `json:"arguments,omitempty,omitzero"`

	// Name Function name (only in first delta)
	Name string `json:"name,omitempty,omitzero"`
}

// ToolChoice Controls how the model uses tools. Options:
// - "auto": Model decides whether to call a tool (default)
// - "none": Model will not call any tools
// - "required": Model must call at least one tool
// - object: Force a specific function to be called
type ToolChoice struct {
	union json.RawMessage
}

// ToolChoice0 defines model for ToolChoice.0.
type ToolChoice0 string

// ToolChoice1 Force a specific function to be called
type ToolChoice1 struct {
	Function struct {
		// Name The name of the function to call
		Name string `json:"name"`
	} `json:"function"`
	Type ToolChoice1Type `json:"type"`
}

// ToolChoice1Type defines model for ToolChoice.1.Type.
type ToolChoice1Type string

// TranscribeRequest defines model for TranscribeRequest.
type TranscribeRequest struct {
	// Audio Base64-encoded audio data (WAV, MP3, FLAC, etc.)
	Audio []byte `json:"audio"`

	// Language Force specific language for transcription (optional, model-dependent)
	Language string `json:"language,omitempty,omitzero"`

	// Model Name of transcriber model from models_dir/transcribers/
	Model string `json:"model,omitempty,omitzero"`
}

// TranscribeResponse defines model for TranscribeResponse.
type TranscribeResponse struct {
	// Language Detected or forced language
	Language string `json:"language,omitempty,omitzero"`

	// Model Name of model used for transcription
	Model string `json:"model"`

	// Text Transcribed text from the audio
	Text string `json:"text"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// ClassifyTextJSONRequestBody defines body for ClassifyText for application/json ContentType.
type ClassifyTextJSONRequestBody = ClassifyRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// ExtractJSONJSONRequestBody defines body for ExtractJSON for application/json ContentType.
type ExtractJSONJSONRequestBody = ExtractRequest

// GenerateContentJSONRequestBody defines body for GenerateContent for application/json ContentType.
type GenerateContentJSONRequestBody = GenerateRequest

// ReadImagesJSONRequestBody defines body for ReadImages for application/json ContentType.
type ReadImagesJSONRequestBody = ReadRequest

// RecognizeEntitiesJSONRequestBody defines body for RecognizeEntities for application/json ContentType.
type RecognizeEntitiesJSONRequestBody = RecognizeRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// RewriteTextJSONRequestBody defines body for RewriteText for application/json ContentType.
type RewriteTextJSONRequestBody = RewriteRequest

// TranscribeAudioJSONRequestBody defines body for TranscribeAudio for application/json ContentType.
type TranscribeAudioJSONRequestBody = TranscribeRequest

// AsChatMessageContent0 returns the union data inside the ChatMessageContent as a ChatMessageContent0
func (t ChatMessageContent) AsChatMessageContent0() (ChatMessageContent0, error) {
	var body ChatMessageContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessageContent0 overwrites any union data inside the ChatMessageContent as the provided ChatMessageContent0
func (t *ChatMessageContent) FromChatMessageContent0(v ChatMessageContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessageContent0 performs a merge with any union data inside the ChatMessageContent, using the provided ChatMessageContent0
func (t *ChatMessageContent) MergeChatMessageContent0(v ChatMessageContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatMessageContent1 returns the union data inside the ChatMessageContent as a ChatMessageContent1
func (t ChatMessageContent) AsChatMessageContent1() (ChatMessageContent1, error) {
	var body ChatMessageContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessageContent1 overwrites any union data inside the ChatMessageContent as the provided ChatMessageContent1
func (t *ChatMessageContent) FromChatMessageContent1(v ChatMessageContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessageContent1 performs a merge with any union data inside the ChatMessageContent, using the provided ChatMessageContent1
func (t *ChatMessageContent) MergeChatMessageContent1(v ChatMessageContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChatMessageContent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChatMessageContent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsChunkRequestInput0 returns the union data inside the ChunkRequest_Input as a ChunkRequestInput0
func (t ChunkRequest_Input) AsChunkRequestInput0() (ChunkRequestInput0, error) {
	var body ChunkRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChunkRequestInput0 overwrites any union data inside the ChunkRequest_Input as the provided ChunkRequestInput0
func (t *ChunkRequest_Input) FromChunkRequestInput0(v ChunkRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChunkRequestInput0 performs a merge with any union data inside the ChunkRequest_Input, using the provided ChunkRequestInput0
func (t *ChunkRequest_Input) MergeChunkRequestInput0(v ChunkRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentPart returns the union data inside the ChunkRequest_Input as a ContentPart
func (t ChunkRequest_Input) AsContentPart() (ContentPart, error) {
	var body ContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentPart overwrites any union data inside the ChunkRequest_Input as the provided ContentPart
func (t *ChunkRequest_Input) FromContentPart(v ContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentPart performs a merge with any union data inside the ChunkRequest_Input, using the provided ContentPart
func (t *ChunkRequest_Input) MergeContentPart(v ContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChunkRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChunkRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMediaContentPart returns the union data inside the ContentPart as a MediaContentPart
func (t ContentPart) AsMediaContentPart() (MediaContentPart, error) {
	var body MediaContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMediaContentPart overwrites any union data inside the ContentPart as the provided MediaContentPart
func (t *ContentPart) FromMediaContentPart(v MediaContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMediaContentPart performs a merge with any union data inside the ContentPart, using the provided MediaContentPart
func (t *ContentPart) MergeMediaContentPart(v MediaContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsToolChoice0 returns the union data inside the ToolChoice as a ToolChoice0
func (t ToolChoice) AsToolChoice0() (ToolChoice0, error) {
	var body ToolChoice0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolChoice0 overwrites any union data inside the ToolChoice as the provided ToolChoice0
func (t *ToolChoice) FromToolChoice0(v ToolChoice0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolChoice0 performs a merge with any union data inside the ToolChoice, using the provided ToolChoice0
func (t *ToolChoice) MergeToolChoice0(v ToolChoice0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsToolChoice1 returns the union data inside the ToolChoice as a ToolChoice1
func (t ToolChoice) AsToolChoice1() (ToolChoice1, error) {
	var body ToolChoice1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolChoice1 overwrites any union data inside the ToolChoice as the provided ToolChoice1
func (t *ToolChoice) FromToolChoice1(v ToolChoice1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolChoice1 performs a merge with any union data inside the ToolChoice, using the provided ToolChoice1
func (t *ToolChoice) MergeToolChoice1(v ToolChoice1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ToolChoice) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ToolChoice) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Chunk text into smaller segments
	// (POST /chunk)
	ChunkText(w http.ResponseWriter, r *http.Request)
	// Zero-shot text classification
	// (POST /classify)
	ClassifyText(w http.ResponseWriter, r *http.Request)
	// Generate embeddings
	// (POST /embed)
	GenerateEmbeddings(w http.ResponseWriter, r *http.Request)
	// Extract structured JSON from text
	// (POST /extract)
	ExtractJSON(w http.ResponseWriter, r *http.Request)
	// Generate text using LLM (OpenAI-compatible)
	// (POST /generate)
	GenerateContent(w http.ResponseWriter, r *http.Request)
	// List available models
	// (GET /models)
	ListModels(w http.ResponseWriter, r *http.Request)
	// Read text from images (OCR/document understanding)
	// (POST /read)
	ReadImages(w http.ResponseWriter, r *http.Request)
	// Recognize named entities
	// (POST /recognize)
	RecognizeEntities(w http.ResponseWriter, r *http.Request)
	// Rerank prompts by relevance
	// (POST /rerank)
	RerankPrompts(w http.ResponseWriter, r *http.Request)
	// Rewrite text using Seq2Seq models
	// (POST /rewrite)
	RewriteText(w http.ResponseWriter, r *http.Request)
	// Transcribe audio to text (speech-to-text)
	// (POST /transcribe)
	TranscribeAudio(w http.ResponseWriter, r *http.Request)
	// Get version information
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ChunkText operation middleware
func (siw *ServerInterfaceWrapper) ChunkText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChunkText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClassifyText operation middleware
func (siw *ServerInterfaceWrapper) ClassifyText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClassifyText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateEmbeddings operation middleware
func (siw *ServerInterfaceWrapper) GenerateEmbeddings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateEmbeddings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExtractJSON operation middleware
func (siw *ServerInterfaceWrapper) ExtractJSON(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExtractJSON(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateContent operation middleware
func (siw *ServerInterfaceWrapper) GenerateContent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateContent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReadImages operation middleware
func (siw *ServerInterfaceWrapper) ReadImages(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReadImages(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecognizeEntities operation middleware
func (siw *ServerInterfaceWrapper) RecognizeEntities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecognizeEntities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RerankPrompts operation middleware
func (siw *ServerInterfaceWrapper) RerankPrompts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RerankPrompts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RewriteText operation middleware
func (siw *ServerInterfaceWrapper) RewriteText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RewriteText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TranscribeAudio operation middleware
func (siw *ServerInterfaceWrapper) TranscribeAudio(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TranscribeAudio(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/chunk", wrapper.ChunkText)
	m.HandleFunc("POST "+options.BaseURL+"/classify", wrapper.ClassifyText)
	m.HandleFunc("POST "+options.BaseURL+"/embed", wrapper.GenerateEmbeddings)
	m.HandleFunc("POST "+options.BaseURL+"/extract", wrapper.ExtractJSON)
	m.HandleFunc("POST "+options.BaseURL+"/generate", wrapper.GenerateContent)
	m.HandleFunc("GET "+options.BaseURL+"/models", wrapper.ListModels)
	m.HandleFunc("POST "+options.BaseURL+"/read", wrapper.ReadImages)
	m.HandleFunc("POST "+options.BaseURL+"/recognize", wrapper.RecognizeEntities)
	m.HandleFunc("POST "+options.BaseURL+"/rerank", wrapper.RerankPrompts)
	m.HandleFunc("POST "+options.BaseURL+"/rewrite", wrapper.RewriteText)
	m.HandleFunc("POST "+options.BaseURL+"/transcribe", wrapper.TranscribeAudio)
	m.HandleFunc("GET "+options.BaseURL+"/version", wrapper.GetVersion)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9eXMbOZIo/lXw42yEpZ7iIcnu6eYvOjbUsuzRrixrJLk9u6ZDgqpAEuMqoLqAksT2",
	"8/vsL5AJoFAXSfno2ZjtvySSOBOJvJDHx0Ess1wKJrQaTD8OVLxkGYV/j5ZUv2JK0QUzH/NC5qzQnMGP",
	"sRSaCW3+/beCzQfTwZ/G1UhjO8w4GOPI9vgUDQqZsk09L0ybT9FAS5lexzRNr3li+iRMxQXPNZdiMB2c",
	"PCdyTvSSEdOOmHZEL7kiGU5KuCIFU7kUCRcLoiXZkSJdkbksiFnFT6bb7iAa6FXOBtOB0gUXi9q8qj3r",
	"lZtLkYwmjNyuYAlUKa40Fbo5if/BzMQ1y9Sm3ZsZjmiawkpwabQo6GrwyYCP/VrygiWD6TsE5XvfSN7+",
	"g8UA4w7It/Zhfyf2MEfkssxzWWhF9L00y8+oVtOZGJJLnuUpIwieKZkN/srSVEZkKe8JLRhZyfLfZwPT",
	"8tAs0xyKHZTk1Ay48zpn4vCEZGWqeSYTmtrxd6fk3ccZrH82MCNr9qBng8j/52ebDT69n4lBNJCCvZ4P",
	"pu+a27GLNN3c7B0n2+z16AVve4YW7Oe00O1jfA9HVIoP7VM5JLH5ARDbbOWe6yXJpeLmd8IFLoNLMRpE",
	"jVvJRHIdL2nRHvRoSQsaa1aEIxFZ8AUXNLUTLVnB7ORMJIrssIc4LRW/Y8EV4UKzBSvMlrpu5CX7tWQi",
	"ZkSU2S0r3PXEUXcmEdmLyH5ERqNRx5jR4GG4kEP7bcmFPtg3EylNC/2VdgZjqc79mLYdt90vvxepGpeS",
	"JwM7WG3pUXU+3Te2FB+OpJjzRccu4fuygIMHygJLMkTNzMyUubSSXLEi45qRw/OT0UxcGUrIFaFEmavB",
	"55wlZhNzvoAhzMH89erq3DQnQ5Lw+ZwViswLmcFv8zJNCSyLFbiAmbhf8nhJuIjTMmGK5IW84wkriGIp",
	"i2FxVCQkpvHSrC0Olz2C21vH2Iw+XMNOLJmd0zLVg+mzSdSkVfSBZ2UWoBV2M7sumC4LMzZ7oIYEYP/2",
	"+WYyYWltnsGcPzBzWj1HbvYAvcw0pWIjcsz1khXkCXR8AmBUlu7ID0wMb6kyQLadIyILQu0QgmYMgQuf",
	"1ThG0KrxR/PTp/Eo3IJfWos1yTtWpDS/Tixcr7M68Fqwe40diOtgLkimyC3T94wJQsuESwfOHTvMlEy6",
	"L72bHba76dTO/GnZbjmyYdPVz2/Pf+PxKZbTgmpZ1I9wJgCvGidorr3vAMcE8PQnUwO1HaItBNBiwXT3",
	"Vlt7vYLGId3DbebMXtb6Dju3qJcFU0uZJvUDHT2LuuhBAoTW94Fdvj47+7vFL7IzGU2GeyM4SD8zDIY8",
	"xCBZKmlA0HDxZiX3XCTyvhfHDiaTNgTeQp8mmplVBShmEKBCMhinC9E+9VHICyR3nSKpJZ3rJdKKyhoW",
	"JvKyg+afmK+9RKDt0tcISIhvVjy6mQ0q0ptKsSCJjMvMiFij0WxwQ3ZuafzhnhaGGmc51fw2ZbtmmEBm",
	"mJKbmlyUsYRTFIwSqil+OSsnk4PY0Jzvn8L/DFtkPGPXVV8A//ie3s0Gn242zNMlf8GyTc810hdAwEGq",
	"e4ed0tjWItT7GofOCxZTbfitLkrWxMTnx+cXx0eHV8fPp+SNYuQJnPMTwoXSjCYjUlttne72HB3RS6qJ",
	"YCwBnnPLiMpTrgkXWhKV0TR191yNRqNOGaEPoY1+okAj8qv4ODAslF0vuR5M5zRVLBo4PvkuFPT2zDU0",
	"gtikLiZNHLD8foCj80Jpu+nRCOAfDPWjHWqvPtSP3WMpFkuRBIO99xzW8q5PTW4f7KmJPm+XDBhrwVSZ",
	"anJPFVGsuGMJckzoWQH1VsqUUWFmCKWHTrke9QHHY7YT3YFct4T2mgRRl0FrsgKNdUnTdGUkhoTsZHRl",
	"ZSvcixXYWEL4nMxpmpq7QmQcl0XBkt1thICGwOl3h+uLAkB3Spqp0Ujnq15SulzlUi+Z4upasyxPqWYd",
	"my6Vlhmp2hLXFkj+2emJE4ZwOh47KdDcyNng46fZgFBF8pTGzPAvVnipNKW3LB3NxHPHJyxFtYAxKPjx",
	"08honO2rC+fNHvKCKcXMNf74iSgmNAcC3MXmYbYOFDqiIuGJ2RC2gOX9xgo5VEup2/syYiNiwD1PU5IX",
	"LOGx0T6MyAxD7KhdcsuUJjjRLSOMxktY8qi+l3cDVGfuDNYLtqD+31IXNDXn6lG5Lbdsh7ZnRiA1krTd",
	"CCvs8gMh9TrhxbhqoMY1gL+SBde/ndKyYMU4e85+Pr64osO7Azj5YSZSPnwQKe8COijW1wCVmmRhiV2D",
	"H88JkHlC01TeK9TKDSLYgzEyFpz7DhcJy5lIDMVWsTSz7Y5m4gRummJe9NiN4GeDIAUjwrDylP/GEkLj",
	"QiplBx6FcmFAdMxcXYYh8zWwFXvD6id6QlJ5x9BAlRcyKWP9/w0i0DYMreMxA7qnWVEYfjl6zCE3KIIj",
	"BLhQj+LrqUHFhxpku4bo62htvaUl5orsSMHgjIANw0mZQzk2uG8JvmG4glA3ULAo86uShaGXtys8NLg+",
	"DGx6eEIeStuR99rgXRfmkRcIbw1Qe1DNa1DYSL090W6AecNhwW1pHlVwn5oKrSVHjiCPjfi0kEUNR0Oi",
	"00I4AH2PaQJVETwco3aYS9DWPH7cQvVoAAc35CbvBImX++ugoDm/LosOYLy5OHVmKWcvYdktSww6jb2O",
	"Ym9kDTpLrfPpeJzKmKZLqfT0h8kPk0Gwp7LopHWGwRs5Ky+4IZirGsF7N5BCPAyiwUNKB9FgIc0u6yv+",
	"GfsT15/IwnFLRL1UUjBwg61QQjeakoQBTVE5i5F4j2biBSx1Sm7smm6ILPyHKfa4sQYz29+uFAjbDS21",
	"vBkZhdnBThecKcIE/gXbm1kcFYm5EaHcSe8oT+ltyoid7884w0zEMrvlAokGyNnKK1qOp8Kc331nQaG+",
	"+86QckPpiRTktuRpQjRdqF1Qx24W8oYMyXlZMPJSEi7mrAAM3aHpPV2paikROTp/Q6RIVxFRqbxnSoMm",
	"dmMOxYwBCvVFCfID2bGoqcjQTPbTDM4uen1xZVSmOVXa939Iqen+Ur46/Tv5++lhR9+HlEZ/Pz00Xa/O",
	"34yP3jw/HB+dv9nFnT4H2KjvvsMdAeDJkByWWg4TplmsUZSooOp5G3SIywRWcPbLyfOTQ2JGJy/P3+Bv",
	"smBZCsPlho0eyYK9OjWiavz60kIDyNntCgCAI+q8xC3JRcrMksmOa/T300M7K7Z5IYuYedDiho7xHvkd",
	"vUPoobL5kFrldiFng/dmiKti5fBEIWIbEFRIqdHeGA41NXv24011XuIH/M198jOcF8wI5S/P30Qgh8N0",
	"BsuPLJj8sACuRm+EFSzMgo/GMUsZGj+a0pxfHl50szZQpnFh9kv8DynA9tKdNVNcKxaXjrqsY39U6Hm6",
	"Gi7kdcpv6fxaxQXNuVhcy5wJQzWt2n1px6usJR8Yy69pavhDzQT3LGsZ4P4q71F/1pKYbs4mZSiV0XwE",
	"yVgmixWhc80KklKlDcaRnddpSjM6DMwGo5l4hZ2NqGaQIKOax6hhCTsgDgOilbc/yTnhgsaa33G9snrH",
	"S1n9Pre0cDZ4ls0GZOcZybgoNVO75qD3lua7PbKUZQFfTMxnRhdmuUhvdysVBaijGyilv618G5LyD4zg",
	"tkbkkmlsaUbT0igqKY+5TleECbjFtRlmAkmxwc6sAoLbtMbnjDIHcivYHSs8SBoKBR5SW/eRi8fiSyoX",
	"iwa6WPwAa74UoMgKfe1eJtZbpzss+36IgHL7Zw5QAWB7h0nCLavzv4LmdcvIryUrWULK3ADZrAu+uFb8",
	"NzaaCXsKE2ChpUi54WRJRUAbsHva+ZpAH64R0td4Mo/dpj1Pd0FaN0Nxo+ZQwWSpUoO/b5dMIIrDgvFx",
	"22j6SYRaMzO3qGAxE9pZH1A+4Kq6KTunF2+IIaJmYbvbAIO8FgY953NDce+YkQ4EqWiBGV1IMTSacQNw",
	"B32Awy1eZ7fbAc1CZIcL8urnXfsYA+u1m0JYdsOI5nkhLZh6QYT3Krg7m6HiDYWC0OSOK7NCnHRoTUB2",
	"3TNRwjs7yivKCCx4LAYbFVzdjK7AfCILWnAD7IeYsQQ3ckfT0iDtW1l8MOgvxULxhJEWAtpnDsGGi4Jy",
	"gY99upBpE50nP37fdzDVNXksOofvkDAK4kkPTQiQtzo1e23Nb/MyTSMi2H01rjk1g27PJgfk0urLb0Ql",
	"/gArvmC6WA0PgRssGU1Y0X+WONkGPO9bP5rbyaQB271J/9PjtdKFUbqcguLJ13njFb/MjMgAjAB099+M",
	"knYrS5GwJNCBKipeP5tzVgzreoGdeAXPcAVPmBqRVzRXwcsknJteMl60elUMWEhDkq2LDc3hFppjsyCs",
	"5kHLnwzJBAh9J/PgGwThxJ+A5Z+7UxIyULJj/jFjJSyjIonsLbUsnyf27aQ29E/AYKd1ZmpHqrhmVGOZ",
	"IHcDJroX2yVV1ZZmeCCzQQgB3BSQmTZP3qEKvEnM7cgLZudw7evcOiLsjokmafUQyrkQIXOAtQIBchYx",
	"/mB2iPs1FAVAaOkCx8ulaMZILlv04OPg58PDk/Htgg3hIWPIxPBub/RsMPU4mPFCL8fxUooPq2Fmrry2",
	"bcEUl3KxKGk63BtMEV27Xjsqg2JbJ/+ZKkYSXrBYGzJq6BblojKpq/LW/coN8jrlk4I2xFVsEFu5/c4L",
	"maGO8bGa9NMYtXxWqLGR34+dzu+fSytNp9bNP9ObXnVTf3+nghW06nUBn7bqFsuF4L9VHeEziKsbu94X",
	"XLuOl+zX/Uv2K3HfNnvXBdf/Ox5phOjYtVNMkztOyR3PWbE7MtfL3H7FdAQ6HejceshF42EdOKKjyU0Z",
	"tDVPl0hqMHQLDnS2Xl7Mec5SLhgah9GEQMDi6H6BG6tmgpJY5itnEoKWEVGSLPliyQpkvwpIXSYL5mSR",
	"21Lj3YNvZyJYhOMRXtqfOIklpJU7GRc7Z2V2ZNTPp7tNmXOvi41YKtK+P6dc6coS6em5bV8jSp0K1tWS",
	"KdahYfAM3p01S1dIm9zFQzeqiNA7yeESgYlnaLdOUqqZiD3nsCtSS1mmRtjR8ZLopVQMKFr10FDdULLD",
	"RouRUbu6adNsYJa9vWBaV8pgzt3Wk0sPGYwGoOrwcZzyfHjHNT5v5GYbB/uPU9YtgK41z5h0rgdOj54M",
	"+sQssD5pSe4p1+hR4bAMnhuk2YFmkXXMMju0IphpbzqvVX8PJgqNG3sZ/gVVV0hiVxmRQDG6cBIQyqjg",
	"0APvbtg2ENOekpdUs3u6Ilf4W5McHEw6CYA6uI4LljChOU3Vo80ZB5VmGozSNCw783CPSdn7HXT5Zwae",
	"omiErZxE8YVjR7MHHRGeGbH/zcUp+IFxAVQHLtRuzZNirSswe9B1V9L17U/MnG8uTh/T55VZUsvZAhhk",
	"7xvxtp4zcKVDz5llwVjDuVgsnN9u4EKzZGkqyb0s0mQ2uKn5FgdN1RTMdEv0EDa4a3u8v1nnjlyd2K4Z",
	"YKMHjB3/U0RqTeGADRph++Dj1DS0/6HHzhR+Hedi8f+jw06EbjWf3t806VCwdSN7gTMlqPeFEYkMyvb7",
	"QDdh+QhXnHUOFBbavaNtTQF7pwkuUeOwYAHmAhkAqq/ngL3hVc8wa8eQeh7GK35Vo2u9fKQNnKIUsXev",
	"sHygy6PpyjZ0T6iSzLm2qwJwPWiSMrHQy44H654HR7zCXQTQXv1OxyT/VqYG03fvJqPJ3v5BNJyMJk+f",
	"fR9NRpO//PDj+8h8v3/wFL5/9v1fzPc//Pg+8BDqAVHLZSicrRd1fCNyBypC68UZAb7b+VK82RfyM1+H",
	"X9Vfhf0iPwtVeo4wAE/nORYFuss2gOq+ri8YWrvQmY1LwEE6Z33QBY31C87S5BcjPXesQCTrXPnlfG70",
	"D7R9gwBuIxJA88gLpgx5AHHPuqJfq5wK9ZO5Ort1e0ynK/G2T9n988W+bXvS7V66rZfdI+FwyxZcfA4k",
	"OgFx546n7S/A8BRZggwAW4ao+x9yKchlxkOS04Mr2HkNrvSKGfOU6mvBio0E0rsIJVI8caqZAD+7ceh8",
	"buRBGLzLr6d9uI/wTbKdSdzAInwUL7UhtusmhXP7nPma6AIDbZh0A++r7BDeo00vyT+UFNcWL4wGEdOc",
	"3vKU67oTyZwqzYUcL4y8W+yjtnS31+1TYnj1Omvo9qpVg5hVy8RJSGYxQOmijHVZsEpPnhtSZZQcjrYW",
	"5byT8Aeu8DeWEKrIbADfXpve0ykKg/aKmg+m9cwsczYwQstskHKlZwOjrTrHjHgpecxwcDVtDPhO5nrv",
	"/8hc77+fTmEY9F8z6pgd3nl0JFHNOcPO2rLu5axQBibvBjiD0sUgGtCF/xdEObHCj++7bHebHN4sUlSw",
	"TYiReUFgqsu2FdUwOzmYkBWjhSIyTcBseY+PHNp6GYwep133xU8cNLHjEsh7PXTCXBsSYHcYPvFIr6Wm",
	"+51F87UEsM/77nG+Z9X6u66bdchbJ0pV+3+E915Gc9V1r+BgVDAu2LCVpiJm/o65L3AUvHF+hJYsQXbM",
	"NgFV7QXanQlZBFP1djEX0fVp+A1upD7dDZARtW9Lt8DY16AHedxhdWHNCy64Wl4wChe7eZr4PblfrsiC",
	"CeuRQpSWeQ7e5O6FyXwziAaV3lAFPVduJXOeangDmJcCEANadD5DvbAtnntC2l5b9Zs5K0rcqOj3FVNB",
	"bhkEV6NjkTfJtkIHa8O2jTTBZzPRvRkdgxrtfIlktaCzwUuGLZwZ955RCEngAmJB+rw5I6Cq3TKUCFTJ",
	"aqMS9lebe8H0tZ2v0yROC5oxzYqNuFhfw39cvj4jl8j+EHmc5zma7YJVBVPUmUfdv9SBoTtMlusVUHGl",
	"qWYRYaPFiFxSQV4UVMRcxTIiR4cbpUU/yfv+q1N9YQaJ9Wa5yUWYGG4l5uCfhl2rrRshlyeNc+7TouHU",
	"u1b4Eq8cOwIu3yHSwt29LvzlXWfEqF10EBYT9tBldkvYA2IaV06+sM9+hux1hnKmcpEX8raDHZzKBTE/",
	"WekujDonO/AMhOY8I4FYj0pRppBJwfyltwZ3eohjVuWUWLdxB0WXgqIVZA2AqIaLGnBdfzKdkfeXumA0",
	"MzcjoJo2nu3y8hheaDXINbstaoQg394HvbYUiyldvn0Fwyi3j73x9+3ICicwtCOHERKBj0G8pHpknw+4",
	"FCMMVH2/VYS7Ha1aZBB/ZKGx8RD67kjCUk23heFzaPwp+ko3qyMUtQvxcInrdvjcbaLJAVNNvY0TJE+H",
	"eG206svdcSU/MOEHwbX0Xr5AAPyc1CvrUqDg1Kq+jSobi3psxhN/li0RqRfM2ySpafMqe8VZ4nPFOGDu",
	"GCiiSaUCAYGYHbC27P5TAF3PNYNSf4cRqHYFIFTTD/47Zp9xR9Nr1snoQ1dY/f6z73tfQDGaXkt/cqGc",
	"Ah073K7waFWnqe+OFQppvGvmsr4Ej+OPzvoSZE16fCCRrhBT9r05+N8bjw4LUJjHC5ZldHgw3Lsdct1p",
	"coFb+gg7U04LzcGZUVk3RrjxztMWcI8q4jmk6gmZy3Kz7rKo29T2Wqq52RAQkaoHxhT9BF7/RWZQXPM4",
	"ch4aP6FjRkFFIrOGIfYv29hh8Y54VrTxblTsWsquS+u8MeBnsuNkbLUb3F2j6Zhr6bwYvERlrrh1xACj",
	"W5UBCzfik6o4F++t73Snairz6w8bsnhcyXz4gSh3Ljs+aupBM6G4FJFzDLRJkw7PT7qTh5jZ8vXHf1bG",
	"KStVNV0gh36+IcYTgvXUqrLBNDKotMhCDNqqF5xsljHF1gmG3UgSDGLbkh2rgqYrJ13vbU2AGtrHepmy",
	"ERgn+AO4cShNs5zsYIS/2rW80Ch41VrvqSKV4Fe9t/xl8nRv/+BpNz3uyhh1SErBfy0Z4eCrAWHILg68",
	"AeUavTO/xVmeDultvLd/0BljvNXDXCXsd2bb8TJzW4awKrXp4/WgWVOmng0Ci0vjt04rSvkY9ehNt3K0",
	"pXzuJlt3K970CVduEzVG3u2hZ5k3b2LRoNvJTWa5fvSo2K2H7Gia9g54ZX51g2HKBhyL/DlYak+SmhDq",
	"9YVHHSBqLKUL7M5/p0PHd95ERBZoXX9zcdKiN/0hr1UnstPrkFJPP9HdjP/y8+uL+8l/vlzIvlQnIVj6",
	"vKy6PJV6Nh0qS9Vj/1ppreGt5DxzNt0rD35POCtluRpko4IMv0adPSoAtNyuOsw64DJ2ywUtVug5Vqkp",
	"kNXHOplFhOl41N63OcBub+vvnw6ZiGViBA4cHtoGHPZ2pTvjwH1yoQ7KevLqGF+pdnzOIbvC8YLP3b+5",
	"WFQL7nnUqcAO294a5HYX1SI7IQ/y1ZqMB9blu4Nb+XCTuOkJbhmAz403w+wts8Fu/QXM5XTZ2qf+cdGg",
	"Va6OdavvS2NCvF92sOJt03w8aqHed2rdMlnTSX87D6w1rrzdP0z5D49cPT4yyfXLf3nKz44viG/scaUC",
	"fxF4+IO8H2NeHczYsduOIjbkLisF1yv7wH6NO7nbH+3ZkOJWE8QoTdWHx+2y0jXX7dK3Gp+evuo7qB61",
	"9V2f3mr2UWDY/fil/e312dnfH+tuTTehGDYZvz666Fu6HaSx7ozHhVRyrse6kHFhfcILIxyY2y3oHSuG",
	"cSrv6JA/jBMpSus3PueC6VKwZBjLIhnePdqD3LlmXHMxl+teL9can/wwQAxPzFAtJ4rnTFOewqNt9QBA",
	"b62bd81DRAW+594vhMMr7yua12MTICYXA1PFXI4gRRv6kEuv4jN8sguHmgmGb85+Zp8mYgevSwR0zdyr",
	"iBQsxUQqEaFC3bNC7bY8IxKV8mwMlBeO5uz4AvOUVZP6JCQKPCM2Xa/+3tHArQ3edu3iBtHArq5/+PCC",
	"bzX++057aRBbtP4+NA+2fR+qIKX6neiCZxR+m9Ji4b7euNdHXgsbcLV+b/U4rB6e4cYa3u0Ps4PHrsOG",
	"Ya1bR190VhvSLqarvtI0+3UxnqdUDPUzy8jUryVNhr8uBlH9VzgH/+PjvGkKKjBN2frdBO3GKmcsXg61",
	"HILXYM++wpEbW7OhNvdLrnJWDDUXqyoAx31rNvUF2bG8eBeiTSiR1Dhf/eaEJ1yXtipu0wBdlwR6weia",
	"2Iqs22gNyolNeUytX6YBbRVeAQEVz62ap6bkplfRg/CINxeniuxwHx7hc4jYsNLdRmSCVS+30ws/vd/S",
	"ZNXWuQKD+e/0ULDJHZL2BwF0iQebpIO2hwdaLzosj9Zn0HAXa+MANdjnJS2FmV1TEYjJI8hJW7w+upiS",
	"M6mdVaMsGHl9dAHBo8+NQEKOXl88rxLJqmsrkbhcsljDgMWM5+AmoSAliev8XMa//O0w7J7I+O5Xanvb",
	"7wDHuRT47VvD1G0GUbCF/Du2Gzcbuu7IHd2CzOQvUgkhnsP9aurXRxe1Nb8+uoj8j0eH51cnr89qDWIK",
	"gIX91HNBd0Fia398e3P7b/zX8fIzKIfPxZ/h4ge0o8e5D9a/ta3Zbqkzid5nOLUFw3U4zbA0WeuqtyEp",
	"wmXlmYpjBS6Jt6v114nsAMJHAeoZWfIFjkMLRuYp1ZoJlqAOl0hNhNRVtn50RK9cJJV79nGPt/NKOQRH",
	"OHTdbvrTtgTYjIlyJDJ40JzPGYOnDlGO8gLesgb/djB6NnFmR/N5b/9g9PTZoM/HtyMopB4G4IsDAKbU",
	"bs6JuAO3I7CnTombaqPdxkzbjQ6W6x4LbdNafX4QCbj9r7rqWmwIFenJqIhrsrau8+OLiLy+eBmR09dH",
	"EXl1cnlUt6Oeg8D7LTIq/vj140wsqDDQZGMESX/RDDuOLYTxWXEjtq9PAgn7gDoaa1NCeszplbB6U/6i",
	"8cUu3WaXDfzbd6xFx15VKdLVrstfUxruSCgJm0RkJUt460Wf/RWhYuUhs8pZOHo0E5ADzAxTGYjMWIao",
	"GKUb2UDBdIHZMVxkgHaFOGwmKGj3RPlcA3YjkOJItVKDvXMRAj4SAO3ISQnPR4kRob5mvuFWcMm2CmaP",
	"ftnBA1G7vu475gvboHUE6CoePr8/8ar6kyDexScfAJbs30ddshJrlXBda1EFDj2cySAiF8c/H5/urj1L",
	"NwLke6lMG4SjyzRmQ2wd69ymDIoGEFZxDdQBvGtZcs3FI7XBLUNAXIDV+tiPVpxHNMBUlCciHhkBkQty",
	"VMKNFfLrZULeQC36pDMfNLYmcALvtA1D6IqZeHSe4iYD/OqJijdcn/VCpEXtNRtuyjj3IZUMwsq6r9ja",
	"m/IZsMQpNgOxL9LWocBaFCqOqpC4jnzyfm8g49E2JVShHo/Ua0qsrBESkbPji10yrKgCNDUCJoT+QcbJ",
	"mlBihnPmwWmVjIEWt1wXtPCsjoYpdDDlbY3jgeroj2tKLjoonKvr4wlB70Gawaz1c+rCdvgdZIFTtpaU",
	"+RHeeptjQOdGQOKUBFI+xD4Ey0LJFZLE41j71rphnxm3NdNGg8asnU4cXeb1Dk/gXvN6GzfankU1O3Cv",
	"e1HQCo3svUjXsDG2zcrRI+lWeBu2cun1t7RdkoJh2qNH0ss1+dD92S55TuzjcRDD6lnnZ0vtzonJk8ov",
	"S4weDQyyPBoGDXIGcLRDRVtkV8fMZf1+vJskvZq9vUPQc1nSupMiNAzxvXazDvw/L0x3o8wb3dkX8XHS",
	"Co48IhC2lHLIHeZqhSrnSuLJh1jMBBUJwQF5WBYIjQljV/tEkVs2N6cf0zT1uZGYSHLJRVtCOxEa5Wwb",
	"GNbM9YL+Nc8hP6z9isxLkVAzN02h1NCjpLhfS1asuso20iJeEvjVWphSdkcdMjezVjSXSWiep75wwbbG",
	"MlxLdYbr8O9r2c0sPvbe625lIQAFC2QdXHiEiRVt2nuFElBN2ntsipEeeNkFdoMJ3iTWZ2tSfemaglsB",
	"w+D7jFl1HVuvzNdQ4UdL8pIVGRVT0lEK9qtqi91vZVs+lW14KdvSqIvAWwv3r4WfZrge/OxRwHAJ2mig",
	"cIw7vogKiuYRqYnmUVU8x3x3y2jWrZlsVgi/UO2yETIdnFmmDIODXciBArqLkbhxELkRxjKvlGYZeLRC",
	"DK0vumzjmjultGZytU7tttv7sCWO9RjCwgFcOrRtvN4aZtH1Tm+9NlRw++9wuYYALR+YsIv6SDs4obVJ",
	"12NjcF07EjzYY/vIwY5qIyZC93cIcJr5aWcDSH/hQiV2g/P3K9sWZh0d6nCDEKg+2EHsWysi67Ph5eZz",
	"cOtzln/T4ypvA73ageUQONLvIb/licBu1x3L550E9zdhy+Poiag8EXHBUCIK1osJSNaGV37u8fgoxe3O",
	"COP0IFVuoWy0ZnVwEFDa6Qm7Odg7LHxv/eCRHnea6h9z2B1L3v6Qew/wRQDw9jJ8MoJt8j/QYgESeAdL",
	"BNXfpj+0YPKtbZpzP1fttnyc+eQDmLixlbxgNvj0FVJA4P62zwDRlXogCiDwfguQb3F3auvb5v6sOYNw",
	"3Ar4wclsD0a3A4RlH2Zui4U+zK+lvutCpgoE2YoTYgkrKVM1IuiLgba52YCWWhokwWiihMU8YYrcV1km",
	"AIjUsrSwNNNsIKRgVV+IpBRS2x5ihRNiU3fuVfOsVK6ptgUtjIRn+pguuN2pLcFEXbKouJaAxOdYadT0",
	"ddfbbG4QwToHAe6935w2dLtp11Li+i+fnV1lizvUn2Dk4zcRLN4bJPSuYb3aGsRObAzbwKLacEt33h7+",
	"EpFX5wcReXF6eFQFV2wM5kipWJQ2wKvrIP0xuobIt+weML3Ojqs4F+GlGfoSnPVXcCYeEaTnQ6IrT7oe",
	"za/XmbDHl3D9ISLsOwlqcHB96l4/OJ/DEx1LCJajj1niQfrlQGqokbXj6VMlO+6U32DT2QOBEi6zrfUT",
	"LRO6+vettepeneUXViguRT+QodofZFDvuCNYCdAFsdbWvD/Zfzqc7A33nl3tTaYHk+lk8t9d0FlwfR3L",
	"LOuqU/2SQ0BqxjVZUrWsjY9i9tPOIeX1HW6rY0hJbKADcW3qcf17o/1no0nXsL1juhDtrgHv9kaTruGa",
	"OTt91wAeUQj82ra6TrKZmt2FTFUJ2rsT8RzarDsu+TS8EmJpUinCx5JRi49U5cz7vV2CkYgs+IKDfyVM",
	"BA4wOHmHq9B2Ac2XhqyLmAW1kTCWGRIJTSKyF5H9iNhgy8aY0eBhuJBD+23JhT7Y9y48X2lnWLth8Dhv",
	"HuzqUqpsp9mh906w9Kg6n23wpafSXFe6qgXEndjMCJXfnS9XgfWiVAtfUnbH0i+tgHcKg8AprTanfdk0",
	"2iUM0inAbreQWk0JiBGKegB2x4pbgzIrgnCo9LuE3ZYLsH1C93taABFxOZ8ramIbtEjTdrusLRUDf2ja",
	"u1zrFGnzYACwR+SJ6/YEHXtlKguo5B1LoWTKIvLkH0qKJ06VCd+HI/IklYt5pvFXcB0fsvmcx/Ai9IGt",
	"fsKsyznlhYrIEyFlbkfiqa0nX1ns/PL/gd5UODbI0TKvgy1ovBF0PRUt2mJjHDOlrj+w1XVnooW3lwSb",
	"mI2Rk+dBVYYPbKW0LBhRK6HpA+6QxQXTJJXyQ5mPyAtIQuRKpB6+vbw+PDo6vry8/s/j/7o+eU6YuOOF",
	"FPAodkcLDqEh3FcNGtV40EqWxRAXM/zAVkPeaRN1z2YdNPYgjPp27VzRmCfqYEQz+psU9F6NYpk9MVLX",
	"k6pu84+TyQSP8RUXJ6/rYmqzM4TqilNMkhnU5QlejgBS1xX8u4FvAVqdwZcewOXx0cXxVXAOn3EIOElw",
	"Fp1PY0wpn8ZgTZAC7hLa4mXCa2ULG65IUNblUXvvWjbMMsQVdWbRYNdKpRvzhh9j1dXLy9Px1eklzH15",
	"YGiHwPrCyuvuU8iHBC0O315CyWBfhDKmaYVKHYkjN1LyLYvwtu88VkO9NmjdYYV5u+SapdYVxLYlpi0k",
	"2B2fnGPmtpSLDySR91CMTkGxL5blehWBuyGMjcV37QhGLGK5JnnB76hmxIzD5+Q2lfGHa/vlNc8haxok",
	"oh/VHxLtv/Z2xYkY1b/Z+3F/NBk9OgbQASOnerktMExbkhdszh+Yq6CZsul4jIlMD8x/by5OW0CBOUKg",
	"jMiLoHOpGKG3SqalZratJU7jN8ooqkZvH+9iJ5zFdLkt4w9Mj3E9rke2GtrvyxwOaNyEZzimIVetDo+D",
	"Y+scN96in02PWgnQCjVIQQUkV9vb/4vRPEaT8Q8R2ZsE//9lf7T3PXza24+IOf2973/Az99HZO/7H0f7",
	"z57az7ud6cUc8rrCWtc2eVFt5Qft1Fa2aNUc6jMl/I4nJU39VSAyt6mBwCHVjRlWuJ0Ad+CZkQH2+qqq",
	"+tUp/hu7vl1pVl/Y3uTpD8/+8v2kt8yq6Wew1g1ka7tiyTuCA9ZCGfx4fnGTDboGF/r7p27BmLgk4Rkm",
	"+KrH3k2e/tC3Tqx4dc8TvRwvGV8sYX05f4AoGoyO8pnjCma2ldS4Lw6+DqJtavrpk5VTbc5Hivma0HA4",
	"OARKO4hs6OJS61xNx+MF18vy1tAbK5Ant2Nbm7AdPOTUCKz2ayvogZclkv7KZ9IoGvZV7vXZ2d+HWAj1",
	"1WkVmDcTf/oTcWFwdmCo5mnnsN7fynGV02B0LIPvVxCIQIfnJ2CX/u67qq7lS5/Y6rvvpgReoqHWcFVo",
	"aefo9OR8t5VlAweCDq7epRnhkmVUaB5XqU9gPWafPiCiwHKQQ0DYOU1TI6/geL4Iphmrcqop2NC6GFnG",
	"D55INk4Me57RjCXODTYoiWkGsm6jBEMYVERksaCC/+Zi/917jqocQIPtXTiHC4CQ83pBlRk9lZ37iYsE",
	"876pVdqwyPpNhd+AARbKbDpSAqmYqWZQfzpl1DAITRw6Ig6OuBwnMlZjz4s9vkA2UsiU0IEzMRWkKAWB",
	"uDWaSsHMSQTlZ6kgeA9InJZKswKQ5RQwrDq/BqYZwsgeNCtAtDs/Ic6uG0MyhmEHGt6Mac4xKctNJZbX",
	"HCegp0clgLTHJ9Pw4vBlVbzTtA1RxbkTAr3OzFVhiUOZX0uacr0yXY6Y0AVNQQ20Pq6suANHtbiQSpGE",
	"G+53W2qWECETnOjcsKx4NQR/dWxeu32QNcvW7U0ZvWOKGFnUtCio1yx37ZG9YJC60p7gn0jXvURMxGxE",
	"BgPDq1QrbcsSRN/egrY40uH5CQyz3bm4a4l2ViOJZFTDOn7GjFD+1SoCbdnt5FVFQKwMbwkJDogpu/x2",
	"YUDzMwmqlP8D8MIc/hBZRkWCVE5jZkcC77RwXfAC4vOYKbKzJsB919wBI7rhYDZZ2JEHihnwjWKqUW7O",
	"Whd2bj6r0p+t6XdjYWHu6xFVDFaPgEFsjQgg4hDBWDBdcHZH04jccWUkEMUzntIC8BmhXiPHTcR5URFd",
	"f5lcQipfjXeX/DnEsGAM8tzi2coMdthbVLm3MjKOdQRuoUBL94cZF0b2vbo6dSVzYxov7cm+sJwB1l7T",
	"a5vVhN3jxpzy1N8lz0q23UN4sTo2ElRrxhH/Vhry9Jtnnma4jGoe0xSDvpQhN6aJozCgAHlQB/hrutec",
	"kYHkWZ9XsmOdj5dUJClz5U+q4AKMUUh5zOxTiJNq0pRcGPlKkQugVvCmWhdxKp6SsgXF9K9cgw7tGMfh",
	"+ckgeEYY3O3RNF/SPch8iZroYDo4GE1GB4No4PUqPHnQRqXqMs/kKTdqgNkpF1oS8LxkBZ6rsqxVOSZQ",
	"lxoaidWcyPTKIi1iACB8VY27jetYWdQIldash5KYMivTXnaxlcEgF4YrgPyTT9wG2QaoQrGplnvYLQPw",
	"6pW/Tm0JyRfCd0QmvNhD27WH1gdvnPWb9ugbQ+zNNJ8ubOQ/BSf1eBmWlQfavE/w6qoRdGNgLfRZ7W6l",
	"XlpDO4BFBw6O6N7udaaTBB4nSvHhCl8CrH74s0xWjfzsgf/4+B82eX9VG2x9wu2yik/4VH+HMJoqpkQA",
	"Dgeouz+ZfO257TslTN7l/QlnlxBVgo1tXqYpaNlPv+JKsNBjxwpOBNQ0caq5mffZ7zOvlRutQsRsw2ig",
	"yiyjxcqhRgeRUGyBTkWm+dim2Fn1U5sjl4QnpDhVaFtMNVvIgjNHd85OTyw12JAF0ZGev8p7cqLJW1l8",
	"gAv1333dgDGcGbmPpuTUeUycVBLk2enJLrio2E1ZfcRJ24i6EDZiI7wrLyyjP3hvjGpPGMKSWSckmztN",
	"zcRS3pN7hh5IBiizARMaKMKAQBq1mIqEJ1QzjP1rk9mKOhVsCwpVZUJCIuXNu2E2S8crQXf2mSR9BkmQ",
	"3SupFUj0X0t4/HlBY2ZObvzq7PTEDcMebM50LYEU2z14qWtmJexLBu/rQpNDQdOV4iiUukMwihK8nN6x",
	"sWALav8pjQ5hlUWZ89h1sKcNQ9hz+A39gKGVO0x3hE4WAPKPbiC29wm6iIJAYdQIDT5yDT3VGoLhMCpt",
	"HschXNA8L2RecHOQ3s98lTu9A4V1B317JqA6LrsOoBnBvjeZ/Nn7qagR+S+bzaCBv1yA21qVw957C+GN",
	"s9Gl3Fb5cr928gs78rdkGXaKfxbX8NP3M446pvkC//9zmMjTydNvPy/K9UJqAuGY/2zmZWY/+PazN87e",
	"ui6QUnjhluwI6UhgVQ1it8FeKy6FMlptWOStGI3Sy1hdCnhl62oHRhxrMQ+L/dur3rApGSZ6FcZAEq6C",
	"2vHWhAgGiyeqbqewmjg+IT7oCGMwoepEAqkvsG8rCXhg4LQUCcYIbBBtZvcYVheYXQj4IdBCl/loJjCP",
	"qbO2YI/ADKYl1GKrlJRwNc4kOQT35sxq9u4JqDtr8e6UHMbwEBfW6Lc6cQWE5mBgq6l3NYC11vk7TisD",
	"i4VTzRCD3KNgLts6Qs3T/ilqXmJhNK9qWVNyMxssWZpKci+LNJkNQErwCSXCHUzJzTvbGM0ttsf7G7LT",
	"sm3t1oap2XLMODUrDnArGBH/qyw2Efksc0+v9Wk2+PQJltvEzt0v1MikcPUpMcAkBvORfXczIyQsKZEm",
	"sWQmrKYNxzFP4UEGHuewll3BklIkVGjIx+JuRdMiaL6uS3NGq64JG4A1FqGWkA8R0OAmJI8y1kwPMZjg",
	"xtsYFSs4Ta2pxVscI5JJpYl3xdltjWaI7c0UAwocq0aCEOQZBnoRGJ5b0oajcJW18hvJHDDBP0ngsHN7",
	"aSMa9B1LfczGEy+c19CdFwsga9mDqjmcQ/MOR8F2pe6KqVRF2f6Qc/6HKOnuhgT3yMoOaKPslx6OXXKa",
	"htNdVRk8fGezOVkqlvgiKARtQ9tsIXdD5TTWtDGq29nxBXHpv8EiVSVAm4lmUW/3skRymZeYsAFNruDn",
	"5wUDWzMXCaBTl6o68huKXbfKyU9n4ubmxpzaTHycCUJmNuWa4SLvZlVddmQ3rjQ7flIfeJoqLF89G7yf",
	"iU8wmlkVwggoMNJb6HZDhuQ/GcsxTBODBHP/yAoQcXQWfcMw/s9Xld+1Q5kJ/Vg0TYOMmZhniMJzOOzb",
	"dmkWrzfdj4Jq95EXQ83ZLSgXShMMH3GyxjG6AphPTZjBqSLjnVOluZA2a/g+poO725sNImwKcecWuo8s",
	"OT8bvLeD4IEjzxeEPO7YwqL6cGyEfArPzhHk6Rft072Tw4JgjXapzcXaL4PfsY3Zg5Vq4ArgtBXIjGxU",
	"70EXHR0OJu2GFgLtxgjo2eBT1d7/+x7/gc8Brrc4t6UuhqB8K5btKvP/c5i2m73fSHBckbU/DAT/iwwE",
	"wbl/tnHAuc00ebNny8jkfQr1LWwEATNHI0BQDcZqnlDIhRxA8mSDoC1DgGFWtojk0ZJqMAZjCTVFDs9P",
	"vkxvD0rQfEXF3UgLLkAaNCWmyQ2K0+gxfIOZdWLG7xi5BIQZXhrN6RiqpUJt8V3cPq+CpmcCHaix2uqI",
	"HNN4aSuQg48bN/yX3BgoVUCCF5UbGwI8slILLAXDmWASdJkg756/Pjt+fzPqUPHNV+AZ0VP30hpmUNty",
	"tXMx7Yxdm0GCQhouvoOJWSKwcUfEp2XZBd7rHg5JB9TqJaU9oR2tUeOOfHjSt2AIzarGvzNHaJUp/WQD",
	"tsaAFp0q3NYl6DsNkT01TkfkgumyEDacH/KbSzEMzwrtEdFMyKIL5ZtHa80XOyECQJrPPxjYvyIDqxzg",
	"Pp+Beb00YDuG4XRY3JCV2Yo/04+DBdNdabQQpQ2hByWOtovQRd7LIqp8EaOq/llkdNHIZyqLbN0Qq5Y2",
	"A9k9+zh29mS0A7d9lbptz6bt37wTEkT7mLu1pHeM3Az5DzdElfM5f3AGR+tCgpMc9hUrJDu3JU/1kAtQ",
	"A8/TUsHb3tpVhe4p1oRoHaq22FLD+eo4y/XK6qUtLLDDv/ScHMdv1p3r4/rbjl9lMN1uA1W6cpjixEG1",
	"ni3eUL3Own9+VpvCDudseB53TOsy3sGkV88g+cPZ0Pzz8+HFFaLd6au/vSQdTsveCdBOTSsE/IUrLsWG",
	"uWmFhFBoJiKtGhmuEgu6T3UW2LDTXwUpHOzmoY7U2jXU8j7AQt5iooeIvKV3+7+weD8ify1/Pr64QoZT",
	"K03VEB4DudFIhpYqWQkRRRWwzHdJH6dc6Veuntg3Y/+NmqV9zEQ5Z9J/li74M/2f6W102iXBI2sobHLh",
	"DXbMKieGfSpDrtO+LuDdUr8VsgguxpepMf7ufeXHR7NecFa1ZaLg0tiSVeMlFUmYZxL7wObAHaW7fA5o",
	"CIGKaQO4d2xJKRWBKqGss3QFIDMkPGAOoezVHUDYPuzsAFir+k0R+eVvh+5V7co0P0ffWlDGZOY26t+C",
	"g0paSJMTPgcHLR0aik0nNXXAqaplmaXddBaJuumrluW6Y72s2gCbC2aNRqNHVMjCNVgf8r8dNuFK7BHf",
	"NKpm3fhH9gAErc5HCPNggFplrRsblUEXjAQ3qINgGm6Dtey+kaYWVtf7nbW0WpmvLlKFpAOKcP1hq/uX",
	"V3VQsPp8NeeiVujRMR5DA8fdEtWuY2lWJu3na17IVfCGlQQFGzYG09kAt9YrHsjJYUnrhqaDIXxXzj/x",
	"EuLVioQcybPT01pdJBvNeH6MPAkWZN/arDGx/kphecjri5cQARWuu+rgHh7M/1W5Gd/59PWR6XzqQwZ9",
	"xzN2T/5LFh+wK2SEZL7bq5NL6PeKq5ilKRVMlspD8wv9alvKhffE+LWt++1Ax2v+w0gK8bC7yZ3WiMbW",
	"E7p9ZqZzXX9xDDTuKpJ1xymKH/j5xjBAmjHNik4GEFYp4N+QDzQKgf3uzKBZWqjLnO+uXfC8+gdj+Ndn",
	"DNWF+wLuYPGrQcEdDyjouiitC4y8ZorkvfFpPn6pKgihJaE24rlG9OultR3JP8L4tgtXWcPXcsfXCRv+",
	"lpVKT2dib+Tjue18rsAGEkbH8tRM7I/IBWaFh4SprvzGTByMyCUTSceerHchoYrc2P3d4Dq4MhIrXwjy",
	"gbFcVWnDNNUsZUqBBQBrItslg8sHUkID/6oySCoXPB59MdWv2cQ6aL57WMNe1/4HoPwYfloPWswLNmdF",
	"J9uoRy7OxIugvrDnD+54gYs0wxTheQfT3AF0hoonbCZuUn479l0NT4g/QIKIJY+XPuaxgt3m2ilNPmKG",
	"tvreN+MhYQWc352B1MqfdNARu3l7QH/wjv8dvMNdxi/gHGaIisyvKgLvmAdYl9dxj0atmHVZMzqM06BA",
	"fDmdrNnAG9PCUwimSy6ALkYkYfBpyAXX9isM7q0aQQ4n1SU7b2dLb0Wf/c31qCdk8S9YbkTL5NCeMwQU",
	"MpyY8kL5gYpV3yiqKuHkqm+G/BKUKVrQfFlQ5ZOwAPRc1GRgCLuXReLSwNiiPy6NTFUDyPRyxf58jFgn",
	"lYZpvmFEV6P80e9OpOtFgPoCgQtfqecPGv3HG/dWRDq4n12EFUl19RDWT62rFzZlE8drWRu39d4Gjxgd",
	"L2qysI9qX/aKUX+9+7pPGXbVYAgCb4Anyu3Ec6QwKjmC5YKoXEWuJi5S11p5HAQwZUnMbqX8YMbFr8n+",
	"aOLHPhaLlKvlcC7jUll/6u++Q6g1utv3SddTsXQ+VGVuMAZ7AogP4cTARct8c1hl/ldLWaYJuWXktlYd",
	"wKfXxJTwEKaF6ZuMMudd5MHK9vbwF3iSkVlmJPGEDElB78n50StY+avzA0g6cXoIZWRfPT0cH5p/H+Gt",
	"3ZGI33swAzZiszcf0pcXHKKnQk/pt4b3+nNZcqGnX3k2+6ObA39nIlxGi6tVN+rQZsf/FpytXS3id2Zu",
	"HVUPOqgdYqQOCgj8weL+5VncVa0KyGdzuQrDGpxpp+6xYV82gpoHax25GiUQIrLwpRsicuvLRKD8367B",
	"MOpwMtW/+JoI3+y+NatfdMDdNgkLIfxzvDsaDnnawa6+MmgG+KmgxlB3as3D8xOLxT6PleH+g0/vP/2/",
	"AAAA//8ey0GupewAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
