//go:build go1.22

// Package termite provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package termite

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Text Text to chunk
	Text string `json:"text"`
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl string `json:"api_url"`

	// BackendPriority Backend priority order for model loading with optional device specifiers.
	// Format: `backend` or `backend:device` where device defaults to `auto`.
	//
	// Termite tries entries in order and uses the first available backend+device
	// combination that supports the model.
	//
	// **Backends** (depend on build tags):
	// - `go` - Pure Go inference (always available, CPU only, slowest)
	// - `onnx` - ONNX Runtime (requires -tags="onnx,ORT", fastest)
	// - `xla` - GoMLX XLA (requires -tags="xla,XLA", TPU/CUDA/CPU)
	//
	// **Devices**:
	// - `auto` - Auto-detect best available (default)
	// - `cuda` - NVIDIA CUDA GPU
	// - `coreml` - Apple CoreML (macOS only, used by ONNX)
	// - `tpu` - Google TPU (used by XLA)
	// - `cpu` - Force CPU only
	//
	// **Examples**:
	// - `["onnx", "xla", "go"]` - Try backends with auto device detection
	// - `["onnx:cuda", "xla:tpu", "onnx:cpu", "go"]` - Prefer GPU, fall back to CPU
	// - `["onnx:coreml", "go"]` - macOS with CoreML acceleration
	BackendPriority []string                           `json:"backend_priority,omitempty,omitzero"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (never unload, eager loading).
	// When set to "0" or omitted, models are loaded eagerly at startup and never unloaded (legacy behavior).
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive="0" (default): eager loading (load at startup, never unload)
	// - If keep_alive>0: lazy loading (load on demand, unload after idle)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	// - `{models_dir}/recognizers/` - Recognition models (ONNX)
	// - `{models_dir}/questionators/` - Question generation models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal embedding (text or image)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

<<<<<<< Updated upstream
<<<<<<< Updated upstream
=======
=======
>>>>>>> Stashed changes
// KGBuilderConfig Configuration for knowledge graph building
type KGBuilderConfig struct {
	// DeduplicateRelations Remove duplicate relations. Default true
	DeduplicateRelations bool `json:"deduplicate_relations,omitempty,omitzero"`

	// MinEntityConfidence Minimum confidence for entities. Default 0.0
	MinEntityConfidence float32 `json:"min_entity_confidence,omitempty,omitzero"`

	// MinRelationConfidence Minimum confidence for relations. Default 0.0
	MinRelationConfidence float32 `json:"min_relation_confidence,omitempty,omitzero"`

	// SimilarityThreshold Minimum similarity (0.0-1.0) for entity resolution. Default 0.85
	SimilarityThreshold float32 `json:"similarity_threshold,omitempty,omitzero"`

	// TrackProvenance Track extraction provenance. Default true
	TrackProvenance bool `json:"track_provenance,omitempty,omitzero"`

	// TypeMustMatch Require entities to have same type to merge. Default true
	TypeMustMatch bool `json:"type_must_match,omitempty,omitzero"`
}

// KGEdge defines model for KGEdge.
type KGEdge struct {
	// Confidence Confidence score (0.0-1.0)
	Confidence float32 `json:"confidence"`

	// CreatedAt When the edge was first created
	CreatedAt time.Time `json:"created_at,omitempty,omitzero"`

	// Id Unique identifier for this edge
	Id string `json:"id"`

	// Properties Arbitrary key-value attributes
	Properties map[string]interface{} `json:"properties,omitempty,omitzero"`

	// Provenance Sources of this relationship
	Provenance []KGProvenance `json:"provenance,omitempty,omitzero"`

	// SourceId ID of the source node (head entity)
	SourceId string `json:"source_id"`

	// TargetId ID of the target node (tail entity)
	TargetId string `json:"target_id"`

	// Type Relationship type (e.g., "founded", "works_at", "located_in")
	Type string `json:"type"`

	// UpdatedAt When the edge was last modified
	UpdatedAt time.Time `json:"updated_at,omitempty,omitzero"`
}

// KGMetadata defines model for KGMetadata.
type KGMetadata struct {
	// CreatedAt When the graph was created
	CreatedAt time.Time `json:"created_at,omitempty,omitzero"`

	// Description Optional description
	Description string `json:"description,omitempty,omitzero"`

	// DocumentCount Number of documents processed
	DocumentCount int `json:"document_count,omitempty,omitzero"`

	// DocumentIds IDs of processed documents
	DocumentIds []string `json:"document_ids,omitempty,omitzero"`

	// EdgeCount Total number of edges
	EdgeCount int `json:"edge_count,omitempty,omitzero"`

	// Name Optional name for the knowledge graph
	Name string `json:"name,omitempty,omitzero"`

	// NodeCount Total number of nodes
	NodeCount int `json:"node_count,omitempty,omitzero"`

	// UpdatedAt When the graph was last modified
	UpdatedAt time.Time `json:"updated_at,omitempty,omitzero"`
}

// KGNode defines model for KGNode.
type KGNode struct {
	// CanonicalName Primary/preferred name for this entity
	CanonicalName string `json:"canonical_name"`

	// Confidence Aggregated confidence score (0.0-1.0)
	Confidence float32 `json:"confidence"`

	// CreatedAt When the node was first created
	CreatedAt time.Time `json:"created_at,omitempty,omitzero"`

	// Id Unique identifier for this node
	Id string `json:"id"`

	// Mentions All surface forms that refer to this entity
	Mentions []string `json:"mentions,omitempty,omitzero"`

	// Properties Arbitrary key-value attributes
	Properties map[string]interface{} `json:"properties,omitempty,omitzero"`

	// Provenance Sources of this entity
	Provenance []KGProvenance `json:"provenance,omitempty,omitzero"`

	// Type Entity type (e.g., "person", "organization", "location")
	Type string `json:"type"`

	// UpdatedAt When the node was last modified
	UpdatedAt time.Time `json:"updated_at,omitempty,omitzero"`
}

// KGProvenance defines model for KGProvenance.
type KGProvenance struct {
	// CharOffsetEnd Character offset where the extraction ends
	CharOffsetEnd int `json:"char_offset_end,omitempty,omitzero"`

	// CharOffsetStart Character offset where the extraction begins
	CharOffsetStart int `json:"char_offset_start,omitempty,omitzero"`

	// ExtractionTimestamp When the extraction occurred
	ExtractionTimestamp time.Time `json:"extraction_timestamp,omitempty,omitzero"`

	// ExtractorConfidence Raw confidence from the extraction model
	ExtractorConfidence float32 `json:"extractor_confidence,omitempty,omitzero"`

	// ExtractorModel Model used for extraction (e.g., "gliner_small")
	ExtractorModel string `json:"extractor_model,omitempty,omitzero"`

	// SourceDocument Document ID or path
	SourceDocument string `json:"source_document,omitempty,omitzero"`

	// SourceText Original text span that yielded this extraction
	SourceText string `json:"source_text,omitempty,omitzero"`

	// SourceUrl URL of the source (if applicable)
	SourceUrl string `json:"source_url,omitempty,omitzero"`
}

// KnowledgeGraphRequest defines model for KnowledgeGraphRequest.
type KnowledgeGraphRequest struct {
	// Config Configuration for knowledge graph building
	Config KGBuilderConfig `json:"config,omitempty,omitzero"`

	// EntityLabels Entity types to extract (GLiNER zero-shot NER).
	// If not provided, uses model defaults.
	EntityLabels []string `json:"entity_labels,omitempty,omitzero"`

<<<<<<< Updated upstream
	// Model Name of model to use for entity/relation extraction. Supports:
	// - REBEL models from models_dir/rel/ (e.g., "rebel-large", "mrebel-large")
	// - GLiNER models from models_dir/ner/ (e.g., "gliner-multitask")
=======
	// Model Name of GLiNER model from models_dir/ner/ to use for entity/relation extraction
>>>>>>> Stashed changes
	Model string `json:"model"`

	// RelationLabels Relationship types to extract (GLiNER relation extraction).
	// If not provided, uses model defaults.
	RelationLabels []string `json:"relation_labels,omitempty,omitzero"`

	// Texts Texts to extract entities and relations from for building the knowledge graph
	Texts []string `json:"texts"`
}

// KnowledgeGraphResponse defines model for KnowledgeGraphResponse.
type KnowledgeGraphResponse struct {
	// Edges Relationship edges in the knowledge graph
	Edges    []KGEdge   `json:"edges"`
	Metadata KGMetadata `json:"metadata"`

	// Model Name of model used for extraction
	Model string `json:"model"`

	// Nodes Entity nodes in the knowledge graph
	Nodes []KGNode `json:"nodes"`
}

<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Extractors Available GLiNER extractor models (zero-shot recognition with custom labels)
	Extractors []string `json:"extractors,omitempty,omitzero"`

	// Questionators Available Seq2Seq questionator models from models_dir/questionators/
	Questionators []string `json:"questionators"`

	// Recognizers Available recognizer models from models_dir/recognizers/
	Recognizers []string `json:"recognizers"`

	// Rel Available relation extraction models from models_dir/rel/ (REBEL)
	Rel []string `json:"rel"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`
}

// QuestionGenerateRequest defines model for QuestionGenerateRequest.
type QuestionGenerateRequest struct {
	// Inputs Input texts to generate from
	Inputs []string `json:"inputs"`

	// Model Name of Seq2Seq questionator model from models_dir/questionators/
	Model string `json:"model"`
}

// QuestionGenerateResponse defines model for QuestionGenerateResponse.
type QuestionGenerateResponse struct {
	// Model Name of model used for generation
	Model string `json:"model"`

	// Texts Generated texts (array of arrays, one per input, multiple per beam)
	Texts [][]string `json:"texts"`
}

// RecognizeEntity defines model for RecognizeEntity.
type RecognizeEntity struct {
	// End Character offset where entity ends (exclusive)
	End int `json:"end"`

	// Label Entity type (PER, ORG, LOC, MISC)
	Label string `json:"label"`

	// Score Confidence score (0.0 to 1.0)
	Score float32 `json:"score"`

	// Start Character offset where entity begins
	Start int `json:"start"`

	// Text The entity text
	Text string `json:"text"`
}

// RecognizeRequest defines model for RecognizeRequest.
type RecognizeRequest struct {
	// Labels Custom entity labels to extract (GLiNER models only).
	// When using a GLiNER model, you can specify any entity types to extract,
	// enabling zero-shot NER without model retraining.
	// If not provided, the model's default labels are used.
	Labels []string `json:"labels,omitempty,omitzero"`

	// Model Name of recognizer model from models_dir/recognizers/
	Model string `json:"model"`

	// Texts Texts to extract entities from
	Texts []string `json:"texts"`
}

// RecognizeResponse defines model for RecognizeResponse.
type RecognizeResponse struct {
	// Entities Array of entity arrays (one per input text)
	Entities [][]RecognizeEntity `json:"entities"`

	// Model Name of model used for NER
	Model string `json:"model"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// BuildKnowledgeGraphJSONRequestBody defines body for BuildKnowledgeGraph for application/json ContentType.
type BuildKnowledgeGraphJSONRequestBody = KnowledgeGraphRequest

// GenerateQuestionsJSONRequestBody defines body for GenerateQuestions for application/json ContentType.
type GenerateQuestionsJSONRequestBody = QuestionGenerateRequest

// RecognizeEntitiesJSONRequestBody defines body for RecognizeEntities for application/json ContentType.
type RecognizeEntitiesJSONRequestBody = RecognizeRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Chunk text into smaller segments
	// (POST /chunk)
	ChunkText(w http.ResponseWriter, r *http.Request)
	// Generate embeddings
	// (POST /embed)
	GenerateEmbeddings(w http.ResponseWriter, r *http.Request)
	// Build a knowledge graph from text
	// (POST /knowledgegraph)
	BuildKnowledgeGraph(w http.ResponseWriter, r *http.Request)
	// List available models
	// (GET /models)
	ListModels(w http.ResponseWriter, r *http.Request)
	// Generate questions
	// (POST /questionate)
	GenerateQuestions(w http.ResponseWriter, r *http.Request)
	// Recognize named entities
	// (POST /recognize)
	RecognizeEntities(w http.ResponseWriter, r *http.Request)
	// Rerank prompts by relevance
	// (POST /rerank)
	RerankPrompts(w http.ResponseWriter, r *http.Request)
	// Get version information
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ChunkText operation middleware
func (siw *ServerInterfaceWrapper) ChunkText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChunkText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateEmbeddings operation middleware
func (siw *ServerInterfaceWrapper) GenerateEmbeddings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateEmbeddings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BuildKnowledgeGraph operation middleware
func (siw *ServerInterfaceWrapper) BuildKnowledgeGraph(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BuildKnowledgeGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateQuestions operation middleware
func (siw *ServerInterfaceWrapper) GenerateQuestions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateQuestions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecognizeEntities operation middleware
func (siw *ServerInterfaceWrapper) RecognizeEntities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecognizeEntities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RerankPrompts operation middleware
func (siw *ServerInterfaceWrapper) RerankPrompts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RerankPrompts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/chunk", wrapper.ChunkText)
	m.HandleFunc("POST "+options.BaseURL+"/embed", wrapper.GenerateEmbeddings)
	m.HandleFunc("POST "+options.BaseURL+"/knowledgegraph", wrapper.BuildKnowledgeGraph)
	m.HandleFunc("GET "+options.BaseURL+"/models", wrapper.ListModels)
	m.HandleFunc("POST "+options.BaseURL+"/questionate", wrapper.GenerateQuestions)
	m.HandleFunc("POST "+options.BaseURL+"/recognize", wrapper.RecognizeEntities)
	m.HandleFunc("POST "+options.BaseURL+"/rerank", wrapper.RerankPrompts)
	m.HandleFunc("GET "+options.BaseURL+"/version", wrapper.GetVersion)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

<<<<<<< Updated upstream
<<<<<<< Updated upstream
	"H4sIAAAAAAAC/+x9DW9bN7LoXyHUB8TOPfqwnWQTPSweHDfJeq+TeG1n2/uqwKbOGUmszyFPSB7ZapH3",
	"2x9mSJ5v+WPb9C5wCxSoJZHD4XA4X5yZ/DqIVZYrCdKawfTXgYlXkHH682hVyGv8IwETa5FboeRgOjhk",
	"Mf7A1IJZuLXsRtgVy5UR+DsTcqF0xvHv0SAa5FrloK0AgggyuYxXXHeBHq245rEFXYfElBZLIXnqF1qB",
	"Br84yMSwHbiN08KINewOooHd5DCYDoS0sAQ9+BoNRNJd6By+FCBjYLLI5qBpF6sAdWcSsb2I7UdsNBr1",
	"wIwGt8OlGvpvCyHtwT4uZCzX9nfaGcEyvfvBsd0FLkr0YyUtSFvNNVYLuRx8/RoNNHwphIZkMP0J6eKB",
	"NVCPqvP5XIJQ858htrg6scORkgux7NklfV9oOni2UNqhJOSS4cpgrGFWsQvQmbDADk+PRzN5sRKGCcM4",
	"MyLLU7EQkOAmFmJJIPBg/nZxcYrD2ZAlYrEAbdhCq4x+WxRpyggt0A6BmbxZiXjFhIzTIgHDcq3WIgHN",
	"DKQQE3JcJizm8Qpxi+toj2ayw7EZv72knRi35wUvUjuYPp9ELQK857ciK7IaW7lpuGsNttAIG255lqfg",
	"5nfPN1MJpI11BgtxC3haW44c90CzcJnCwIi9EXYFmj2hiU+IjERcYFZdgxzOuUEi+8kRU5pxD0LyDBxx",
	"6bMZx460Zvwr/vR1PKpvoUStxWvRQK1Bpzy/pAXvo9uHkl5+Wo57clPZHOwNgPSkvJ+ABnKuuVW6ScSZ",
	"pJNt0RAvXjmBCEU7KmnT2KwH0dmr5XoJtn+rnb1e0OC65HHbzMFfl+YOe7doVxrMSqVJY7HJ6HnUdyMT",
	"EnXlHNrlxw8ffvQnzHYmo8lwbzTZra9MwJwUx2NOFa+JFIc8iZR+CXHmrjui17xKcSk6/peGxWA6+G5c",
	"qZ6x1zvjupTZLvLw7KzqEm1QiZRUySVLVFxkIC2zK26ZBEjoQs6BmTwVlglpFTMZT9NwBGY0Gt0rQAmr",
	"z9spYHIlDZDGC5j9OkCZA5crYQfTBU8NRIMgWH6qa8Y9PHfUXJOmXpkEYpR7JBEotLEOc0T8a9QA9cqD",
	"2muCetUPy0CsZFID9rkUSf6yf22Lx9qe2mf0wwpIEmkwRWrZDTfMgF5D4kQMzawIPVcqBS5xhbq4bdgd",
	"WvNNaXWUIkFYyMyDuGpQ8SxHWC2R21TaDeHKY1vwNN2giE3YTsY3Xhm5vXgNBwkTC7bgaTrn8TVTcVxo",
	"DcnuQ6Rmi8HK3Tn8ohqhe9muvFrN4+G5uCx0z/4+nZ0EyyeoZMjmkCRCLselZsHzEjE08F9Zm0/H41TF",
	"PF0pY6cvJy8ng5q8KLToE5RIEuTMXAulhd00xNdPAyXlLZpXKR9Eg6XCXTYxfu3mszCfKY1qHQWaO6NU",
	"ccTemaOKpvGUJYA7YCaHGM0LbUYz+ZZQnbIrj9MVKsHwYepmXHmbzM/3mJLwuOKFVVcj1AiBdlYLMAyk",
	"+z+Zd4gcWhqFgfpN5WsuUj5Pgfn1/sOtMJOxyuZCOvuJpJUp8lxp62bTHmnNp089KczTp2wngRypoiSb",
	"FyJNmOVLszudySG7WqorNmSnhQb2TqFdDpq0wQ5Pb/jGVKhE7Oj0E1My3UTMpOoGjN0lCHgoCIM0xlkh",
	"rciA7Xg+NWyIi/11RmcXfTy7mA0ituDGlvNvU47T36n3Jz+yH08Oe+bepjz68eQQp16cfhofffr+cHx0",
	"+mnX7fR7oo15+tTtiAjPhuywsGqYgIXYsjk0qLrjT8ohEBcJYfDhn8ffHx8yhM7enX5yvykNWUrgcjSP",
	"jpSG9yd4ueOP554adN3nGyKAg2jzwm1JLVNAlNlOGPTjyaFf1Y15q3QMJWndht64e1Tu6CdHPdw+0cL9",
	"sVSzwWcEcaE3gU+MY2wkQcWU1pm0dVBT3HMJb2rzwn1wv4VP5QqnGlCMvTv9FJHkouWQy488mUqwRK7W",
	"bEcrQsyTj8cxpODs6VnD5P2pQs9ddMRtEJWI+S/dX04ClKK9a3a1xLj3fC4NxEWQLnfpAy7tIt0Ml+oy",
	"FXO+uDSx5mh4XqocJErNIwfw3MOrDJJrgPySp2INTRtz0jEw/6ZunBFiFcNZweZCQYWqQrIMMqU3jC/Q",
	"O0y5schwbOdjmvKMDxFtbsU8hd3RTL53k7kG4gH0sGOnkqQH6MBYVOhJcMTUggnJYyvWwm5GM/nJkDBI",
	"ao4aicLZ4Hk2G7Cd5ywTsrBgdvGc91b43R5bqULTFxP8LGEN2i8bMeBLRN4JX0T0hxVIZoDsMzdDaaYy",
	"YS0kUaABbsOjTQDSDUOJhzZKkZPcrK+COjeFJY83bA4rvhZK746a3DV4nvVpnVQtH8sKqVouW5zgj558",
	"QSVJq0t7GfzapiH+AL+wBFETyqWTzFOUwMloJg+TRHgtVv56I/CKAvtSQAEJK3KkMuJFX1wa8QuMZvLc",
	"UX9C2rGQqUAllVSysUW7Z72+KL+9dLS/dGf22G36kw7M3+F6I7IitVyCKky6CYxD7EsIo1WqAc2eJCIV",
	"mALeEA0xSBtMMaf6hakxysnZJ4byERHbfQgx2EeZbhgsFihM14CKX7LqmiN0qeTwF9CqRbiDbYRzW7zM",
	"5g8jmqfIjpDs/etd78oTvn5Tjpb9NOJ5rpUn01YSuRsXiPQgqpSelGQ8WQuDGLpFh94e9njPZGH4EtVR",
	"TnpKSX8syI2GLjMazBayXGmuBRL7NgZI3EbWPC2QaX9Q+hrZX8mlEQmwDgN6F13CcKm5kC5UZLVK2+w8",
	"efVi28FU1+Sx7FyPYhEUxydbZEKNeatT89cWf1sUaRoxCTcVXDw1ZLfnkwN27gxv9klWlg1p2TOwejM8",
	"JEm/Ap6A3n6WbrF7+Hwb/rNiMjkANmnRdm+yPXB1aazmFpbB9yjF12krBlxkaA2Q3B9Eg5T/shlEg7kq",
	"ZAJJzb2ppHjzbE5BD5smv194QyEkLRIwI/ae56YW16JzsysQujOrUq5SoUh2bJnxnG4hHpsnYbWOC6Kp",
	"upgge+54Ufvmr15fhgOYNnUl28E/amovaui83Q48dySTKUOKtaAoyRLIuEwiP91bAyJJgWxpYsEQ6Fuh",
	"Lx72MnMnMRvUt+52Q/IlWBeVet7hhuVcW7wWuYYKWxrfVNwRgzXItkz1W2E7uZCyrhUIV5I8pAcNy8Qt",
	"7tJRDkUJbd4LBOFuleEZsFx1BMGvg/kShhTdGYIcrvdGzwfTku/ilZLXm8HUMWBfOMutcpmInqj+a26A",
	"JUJDbFEwoiTiQlYRA1PMw68C2TF4ipxcF2FiZFUTNrLQKnMOwa/Vol/HziUHbcZobL8JDnoZvKvcksa0",
	"MmyLs5qRjO2TNGhezTqjTw+aFqulFL9UE+kzGZf3TCVJgwLCKj/5H/4btgTpfYg2kJn8vuaK/7/xyDrC",
	"jsM4tDzXgrO1yEHvjvAK4bU2YCPyw8hPtkMhW9FeUnVB2LaNy846fbamvwpdXjkRxpYWUSWN/PjGzeo1",
	"/S9WYKDHchZZBongFtKNu2CBydwTUsT4WgliGIo9DL1wZym3IONS7nmMzEoVKapqG6+YXSkDdC3LA6tx",
	"I9uB0XKEDkHngs0GiPHDLSq205BmuFzbPP2p5xpHgzgV+XAtLD1oDHPE+mD/cU6jp8elFRmowt7nzwWb",
	"gKIgVrEbLiypXB6UOIWkFWJtIfJvULgrby/geJx8px92MDHOyd7L3P+dz6WYxzJiNSv+LKhrZ1DRywkK",
	"Tz+2ZlM8Y++4hRu+YRfutzaLH0x6mdocXMYaEpBW8NQ82q0+qNyoGpR2tDOEKbeENtERP+Xa9j5Fu5+d",
	"PqJgYJFakamEp1VEk+1QyFhpJjK+pMdiJeHjgiLvd+3nAm5tHYGv0d3jjxH8p7OTxpzPX6MBye6tLyNC",
	"5kXP7o7x63KHVrkNjdh5FRjUAJ53DOmPcyGXKbgIuTvEKbuaDVaQpordKJ0ms8EVDmwG091QM6VwDw12",
	"vOdnfG5OqdPcsJ2K4rsI4NcZHeJsgNyM0B0o9xd+5+F/jVhjKB0NsoEbX/s4xYH+r9kg4ZZP6ddxLpf/",
	"G6//i2fRaDSaDb5+RUybsqO29QH6APFKSPIlNWprZLmKFVqZAh1asp05j69vuE5YTUL3XJu7ny48tbdC",
	"e7AE27pM7RK0DqtxEczug99PGpeghcfn7e8oH9A08w8NQX94PVh7aG6pl4Zc6pP9XbroQsbcNp06qwvo",
	"vMD6gYyuHN6phbAeIaLUrWUpyKVd9TxNtaRWeJpxt7dPdvlb3/saWAonM5j+9NNkNNnbP4iGk9Hk2fMX",
	"0WQ0+cvLV58j/H7/4Bl9//zFX/D7l68+157lutTpPNHVF9rKMJWoXJPNatiOkkAP045SjtYNfin/uO+p",
	"uKt5H/gK58wTimKgaC+RfCyDbDm4GmV6T09rl0jQomf4uokrjWYZGMOXcC8KDkjfqkGF9KgD/IXRy51m",
	"KAXZp7PjTsLK9ue+ahLb2SpEm4+V/cPEP19/PLuZ/Oe7pXrIY/k2zd6nLLdsOgixBhewnY85yMPjmrXs",
	"deFuhyqlNrlP0JXkL7m0ilhUQD7fmyCAv0a9MyoCuKhDXT60Hte9H9dzb8uoUNx27/zjXpkANXMvzrPB",
	"blMvhndo5wYPM7yq1l8kUh+pkMuCp8O9xxnVpRi/C2tou7IPUwb9nkDnu6F4OfxiH4n2rdWcJN9deL87",
	"ER/enLFycEl1dGWGZqXI5C4dYArZxYWxKmMpn0NqWoewTIUE7bAfROEjkd9yc/24LTT86bt2cQ5f9s/h",
	"C6tP2HYQTSe9xUIpl0P7vEQ/zb4sh2HCsPLhH+uVlRGFuzZRDduGej000eIiZHXyGyWFghJhrEjpW/dF",
	"41weib0Po9yNezO60uXxAGa43h9mB49BoS+RBNGpo1a/pU2Ct7moT2yFKM07d8Bwt1tjtvk1aGtRHMQz",
	"iks9bJLiQnNpUvzNKvYOdMbllP0NLfqIrdQNBUM2qvg/jzuje2zV7dfjEbejczkeZpJ4kj2M7Nv0xj37",
	"y5pWVe2e9lnWeEpdWAGJxB/jDg+WJP1hItYwHyPnkeSp+24OPOs3Je89uzuZPVDRId1HxLPA62+k9WkC",
	"nQz1u1K41WJhIORrA8HoS0WvvZf0PZeQLugxIR08HM92Tt+cRezj2buInXw8itj74/Ojpm12+uasN2AT",
	"Kw1b8rNdNiiNoMxPvFXd5M9Xr6IHmPQUY3wsqeawFLIh7iaPy3P3cHzuekWMv6uVZOeZqPttd+VuhjMI",
	"+6DU90Gg3p2cs1XcOQ3fQxJnAHjU3SiK5jgrgu14q8KrMSXTTZlHURjUEpzVh0Qo8ljMpc9q2zAuNyVl",
	"NjnUoUczCZLP0ZhjlZGCsNA4UUVwfjVY7R4wRjPpY+Y+d94/v9O4J6Z8DPMboXdlQ8+cTdmdgzYkU8g8",
	"lxtnkydFjNRO0Fn/PYV22xx4sDXQMQYeKgIvgv4K50gnIMD06LGKPdmNe+a2PoUM3SeXf3Ys4xET9Kh1",
	"VBBbSTX6DZr/EcJwuyoJe7ordOAYz8n9dtgAF++X9Hc5YW0p/a9HELbovA99snNblCCQoJ+EaFNtFQn3",
	"Mm3DDuzh2fAm14l4tAzE3ucoleV9jHuqcbpMQENSS5AP7OwgjxjVmKSC0pQM045FgpMdmF7I5UxymTAH",
	"UNRT7hcC0sSMLWQ5mnCGzWGBmifmaVq+VIBMciWk7YiPY2mdtKB8WMXakVsXefieUov8V2xRyITj2jyl",
	"NP7Huk9601cvxnW8YvQr7VxDCmseFGk7GtVGk/E8T0VM9pV5MM85XKozvIv1fh8rsGTFrTZFDyedNUgB",
	"tdvvEI/c07xPhjZOJjTEwWNDh1vo5RHsI1P7Cae/lqQ3wNSJIt1RjNJ+pelVJK14UquK5O5Q0taSk3+C",
	"NkLJ7YxAieH0yNmTxuCSxkUGxvIsb7Dy/mT/2XCyN9x7frE3mR5MppPJ/+3b1lLYy1hlWV8RyDuBpMHf",
	"2IqbVQM+n8d7+wfPekGqy7XbVg9IxbRPRQ9j6lCXam+0/3w06QO7FWZ4OO8DuN4bTfrAtY6pmlqjR1Qn",
	"fmNbfSfZfj0Nsb3qDfXPgtw/C3K388uWzOVuPoob1yx+JdFXJpC4/EPT4ZcU1pD+1ozqEwJCp7Rxj2G/",
	"Bdo5AemtR3wYIo20D7wtncyPQLA16DmyzIY5OkSlKE9gXiwpfkPTb7gr9w2vPJU08QM6oulhu2ygShlJ",
	"kqdb0VWFRRvcXX9GxB6xJ2Gaqw2OVaq0+MUl0xqVQsSe/GyU9JXDVhexLdBQ/Pv5xw8Re5Kq5SKz7ldX",
	"UAyLhYjJTLyGzV8pm5flXGgTsSdSqTzUIKcg7ahGshr6PztH0cEeRAOc1iRbbfC9pNuSdNItjotjMOby",
	"GjaXfXLp8Idz5obgxtjx97XEi2vYGIu2rNlIy2/dDiHWYFmq1HWRj9hbnqamrKY5/OH88vDo6M35+eV/",
	"vvmvy+PvGci10EqSpbzmWlBgWJTJas1S640q9NAhM7yGzVD02hfBlu6RsQf1R7IwLqRxPTEHI57xX5Tk",
	"N2YUq+wJUxqPOpT4vZpMJu4Y3wt5/LEZh2pPHkSDTMgT94g+3eszJ4lSlxX9+4nvCVqdwW89gPM3R2dv",
	"Lmrn8C8cglukdha99jIYVPKuKry7uY+hONHtksa6y+SulU+U37Ba5tWj9t6HNq0ydBj1oFwYuDQmvTeB",
	"4o10T0jnJ+OLk3Na+/wAZYd0pWimzHeeMpxPIw5/OKfqsrKoIeZpxUo9aRb3SvIH1mt177yrrrlEtjZ9",
	"NcvCQurTNf1YhmMpRXJ8fOqKEFIhr1mibijH2VCOKWS53UQ4h8b7Qi0PAc0iyC3LtVhzCwzhiAWbpyq+",
	"vvRfXorcFWLrAnZHTV/Y/+lvV5zIUfObvVf7o8lof/TIp9pAjJzb1UOJgWNZrmEhbiFUZKQwHY8pOdsc",
	"4F+fzk46RKE16kQZsbe1yYUBxudGpYUFP9YLp/EnA9qME275eNdNcqvglHkRX4MdO3zCjGwz9N8XOR3Q",
	"uE3POkwUV50Jj6Nj5xzvvUWvcUajpKRiDaa5XKIvvbf/F/Q8RpPxy4jtTWp//2V/tPeCPu3tRwxPf+/F",
	"S/f5RcT2Xrwa7T9/5j/v9tbYB+YNua+Xrva/iflBt4GFzyvFcxcyEWuRFDwtrwLDq+ZCHWhSB5j1iqkJ",
	"aQeRoQ2wt61Kp8TOiF/gcr6x0ERsb/Ls5fO/vJhsLdvBeci1AZCvFXIld8wBbLzSlPBK5Cb3+BpC2hfP",
	"AsIuzyMRGcjKwfTI7k+evdyGJ81jNyKxq/EKxHJF+OXilpIKXI5eWfOnAbfVbCfggN9F0a40xa/IDHU9",
	"OSyPyWJAEYealyTtIHKJRFTub6bj8VLYVTFHeeMN8mQ+9inx3Qqd4Ea46jGf056Ka/Civyp7pI4QumxL",
	"4rvTvD+pKt5m8rvv2A8rTlFID7heeu8fKUzQKic16K5iusSgZgIdnh5TvuzTp1VVxbvyIfTp0ymjqA7V",
	"rlW5lDtHJ8enu53sFQeIJoRqC4RwDhmXVsRVjg7hU2+/EnrODIlhQ+cIB68swUBYVaRNw9DHHb3ip/Ck",
	"a7LhMfnAM0iYf02sFWQgoDf+scK9zpiIKb3kUvzibm1EVHQX2HVZglvrgJa1GU0yhYfg8rW8NtG/XoX3",
	"9ECsmfw+yAsq6+QWqGgxBY5awLLAc47RRkKNExWbcalwS6YAigx/MtDHGDGXTBcS3XeZ8FRJoF5HVekS",
	"l8wxO4vTwljQxBEnxEbVIbXYCaUf3FrQZL+dHvuqR5CxACJ/l9euxjwXLqPpqrK9G5FGmlnyS9XfJJzy",
	"2eE7loscUiHdKnV+CG8IJJQzvA+QBL74UvBU2A1OOQJpNU/J1/M1SujlyyXjsVbGsESgipsXFhImVeIW",
	"OkW9FG+GuYYwvHHFKJPQ13ylwNdgGBqcOELz0n3c9Uf2Fjh+9Cf4Heu7fI7dXG4cclj9vjSqp0Inma01",
	"Uw7S4ekxgXnYuYS754KpzLUKITxeC4k2eVnOF5FLHHbyvpIS3lD30sIBdGmM5XYJIP7MaqWtPxNf4OEP",
	"nV6o5IzJeQweEr2r1fGipMwyt9Ownaut2Z1Xu3gH0D5zwHwC5VFJFAT4yYBppY37EMLO1b+Use9z8688",
	"LfC+HnFDTTCYI4zj1ogRIw4dGTVYLWDN04ithUEzw4hMpFwTPzuqN2Rum3HeVpK1vEyd3ie77D/qHFaD",
	"wb73fLZBYIdb6/a2Ft85WEeu0xzC2B+65grs4uIk1HxTXx838q0X/4R7w3ltV6qF15sFF2l5l0p98dA9",
	"1C9Wz0ZqBYFBA6B4+qUU/YfNNhTINV/ckKrqXCwqUtf4F6c3niFJ5PnXLrbjnx1XXCYpehkC0qR8cVRy",
	"l94KUxGDf+8IpkuasjM0ogw7A9drqmPHVDolhSWnKKQV1rUOq3oTDmpvBYP1Hk/zFd+j1nbO3RxMBwej",
	"yehgEA1K58mdPLmcyvTFYPJUoK2PO+1pO+aVpQlKoGkatNJ8g130vlSpyAHE8FXBZ5fXXYVQpxkgtUKz",
	"Ve8k14cPB38KdYd/LdOI8eu33DjbKAEXmBPGijigQXz1vrxOXTOorJ4OQqZ+sYfs/V2yvvY63rxpj74x",
	"zN9M/HTmzCfyT+lG1htVoGzeD31RRjQNKCRY5ljPlV2FvpVIFlt7EQxH5Tv/4Kerq6ufDSq6X2eSNUqj",
	"tnSvIwEaucFuGSdiJWP4FW3NAfCHFIWfGu0JccjzyaT8sdmn0f1a/lh2RnSAZzOJ/w3w568z+ZV2Qfew",
	"9PmOk9A47cK9ZHj/9rVKNsHXABedrD2Kjyn4WzaefVAjt5Bv8bX5joKeNn3hlDfdyv3J5Pde27+z0uJ9",
	"L8HElgkzBcUIF0WaUpTg2e+IiStN6cHgWK55KpIQWsB1n/8x63qT2Dt04AdGA1NkGdebwBo98s/AMqPu",
	"wzjc2WPbpWjwN4wvVKrZ0D4qUa+ZdDI1bZn0JrSeLY1xYWoleN5NI3vxiWmaid4QcmHaWxu55Bd0CGRi",
	"mPBvr926lJoT6du6EYyaCdgV6a2OT3fKwnqngKqe3Bcao5flduFm1LwQqxhF+Ko2IzVsglc7pLr5zBtW",
	"IczWKbvYnbLDmOKc9SpHb41U+2/DISu5ORVp6oMfa8Er09aTqGECu4YRtTpYIpgnMiTftCq2r15/e6Xs",
	"g4pjna38bUpjewqmdn+jLqy1sqKXirjerIpT/8SkcNIGkpn0Ng4dxyKleJdrhLBGEBqSQiZcWkqSDBei",
	"7Yvh1+VbSJlWXubfUP4rco1nKNclx/cPrAk+FVuwQ2M18Oyq9O4MaIE+snsSD75exDJlLCtfOnc70FCM",
	"Xk3JIwypcl6O1Fork6ioufx1u8DxMXJdvb6tw13TrvVQ0/493Ri81UBiEQf91GJ75Kd2ztps8LnS8DP5",
	"vreivstKd+PW26+hDz+yP+69J5zlK2UVxXFYzC1emp6pv+3m+EJHf4EQ/Oc7TJ+gmiov/xvZQI1mAn+w",
	"DdQsaca1t12qJszW+wfdtmG4bZB0C5DrLWXnNLwni6Zjh1S0L8uK/n0ssWeTZ99+Xd/SRaGBUcjk38oC",
	"LIPFtcprMvqqDoNLsH15prbQ0pCpYujKdytJo1pP+zImGrEPb84iErydlkKlYxZMJ2fydKMi/WYWjv1H",
	"Ge6g5AFpDVvxNbCroXh5xUyxWIjboGC9s+oWOdxWpMt2Qnsi0jGnaWGouuNOrOqOsFeZPnTzgC21wjxv",
	"stxuXApEmBLSxFCBe/BlKcWDFqh1iKI2YWHXzboXNC16y2j9qv+o19q5dZsvC92lWx2mcMrF84i9PTn8",
	"MMQ/Xh+eXTjuOHn/j3flE0aXV1rmeM0SR2PbN+urdy+NQ+u/jpY4Eca+D1Wf30xMt0rLt8kJE6Ks/11S",
	"8jX/9/RVT/qcIierKqaC+93U2rNY8zGsr/Z6p4c5wcaj3a5vWEXJHuId9tyD1tUhsQUyVgnoEfXzZgnQ",
	"p6GQwvqvXMivGkTpG+ThHbW85wfcp+++Y+VLQPA2H/nIyKW5AT0MjVso67AEpDfboJiqpCOUa5WhNtMN",
	"171Vuncr1Ubdpu62fxv1wEPzpeDJ8MuyaQAbb6Ev2/udun6c8Sr1fTlfw0bJGLZ9jaKIpJNhb6zl7O/U",
	"4U1IdsQTkaY8JhmuEzNq2PpbTdpwLt/Kot1WUv4HG7dbS6y3xfr+tDH/HWxMXP3g269eSZNS5Re1/rw7",
	"fRbT7jYLuJRkTqmURtJ2lVJaXYaiCUlVb7pzbzKH1yOd1Awy3HSnZWdpGrsUkotN7kT0OaVS6IQdqQ8n",
	"J42SY59Nc/rmjN72CCHfWLJsFllVwc4G/i3449k7epyv411NcCWyznWvimTLyScfj3DySZmyUk78ADfs",
	"v5S+dlPfai5jKKe9Pz6nee+FiSFNXQfykpq/UdV2rN0yVPWl6yzsuL7J4iVp090+Rfq3gnL53/IY2Os3",
	"Zxf+ya57Zji5aVCHQHPcV3++FtzFhd3nK5ZzzTOwoO9/r6pHnOrF06Uyo1pSr8vuKH1uH2yn+vlu5dSs",
	"EhbwrZRTp/L/D9ZK3TLtvsBHEAb+mfxPlfQ/QSXVuy3/yzqp5K+WXgmaSfO70hrOXD4i/VOL2xI6ygf/",
	"qnbaKsZ9UXVDFTUbIwVFdOQSQs5CEbpIS1ldK1PPCmOnM7k3KrMc/XqhFr1j6u+P2BlhTEGWslJ9Jg9G",
	"7Nz9a1PtPYXmndywK7+/q7JpeQJGLF2rY1PvxmwhBeP+KQTf19yhTKnfTj4j/asi+lQtRTz6zbqoEdrp",
	"0UTB8XSzLssfSB+5fK1mlk9O/1xQrzJrpvo8Rod02hmUioQYxI26s7C+nOBPpPaSMOt0EnjvIZ14SFP3",
	"T10sC5EAc7lRVcIFAqAmA2E0e1trMjBlH6DQPGUSrNduGmhy67HAeZGB80olHridVH07zSkq//0BxyxD",
	"IxKYyatUzMflVFTc8TVlkdM/fBpypipWur/rQlutIuhT33ngW6nUetuMP1yfNhon9IhVv3l/QH+q0v8Z",
	"qjRcxt+gSBFEpfU2lb5zurTWf+DOd45WO4KILcs2ClH4d/5EBi4g1+2HMOqJ49h/lv0JvtnFanei6KGy",
	"H1JvSvDfE2tueeU20K6JGQ0jbjQ9DcJrCaOeZ8t00zHPxeDr56//PwAA///hAdysXn0AAA==",
=======
	"H4sIAAAAAAAC/+x9/24bOdLgqxDaA0bO15JlO5nN6LA4OB4n41078drOznxfFMhUd0niupvskGzZmkHu",
	"z3uAe8R7kgOLZDf7h2R5Mpld4BsgQCypWSwWi/Wb1b/0YpHlggPXqjf+pafiJWQU/zxZFvzO/JGAiiXL",
	"NRO8N+4dk9j8QMScaHjQ5J7pJcmFYuZ3wvhcyIyav4e9qJdLkYPUDBAi8GQaL6lsAz1ZUkljDTKERIRk",
	"C8Zp6iZaggQ3OfBEkT48xGmh2Ar2elFPr3PojXuMa1iA7H2OeixpT3QNnwrgMRBeZDOQuIqlh9ofReQg",
	"IocRGQ6HHTCj3sNgIQbu24JxfXRoJlKaSv0brQxhqc71mGfbE9yU6MeCa+C6Gqu0ZHzR+/w56kn4VDAJ",
	"SW/8wdDFAauhHlX787EEIWb/hFib2ZEdTgSfs0XHKvH7QuLGk7mQFiXGF8TMDEorogW5AZkxDeT48mw4",
	"4TdLpghThBLFsjxlcwaJWcScLRCE2Zgfbm4uzeNkQBI2n4NUZC5Fhr/NizQliBZIi8CE3y9ZvCSMx2mR",
	"gCK5FCuWgCQKUogROcoTEtN4aXCLQ7SHE97i2Iw+THElyq55TotU98YvRlGDABf0gWVFFrCVHWZWLUEX",
	"0sCGB5rlKdjx7f3NRAJpbZ7enD2A2a0NW27WgKPMNIWCITllegmSfIMDv0EyInGBaHEHfDCjyhDZDY6I",
	"kIQ6EJxmYImLn9V+bEmr9n8xP33eH4ZLKFFr8FrUEyuQKc2nOOFjdHtb0ssNy82a7FAyA30PwB0pHyeg",
	"gpxKqoWsE3HCcWcbNDQHrxyAhMIVlbSpLdaBaK1VU7kA3b3U1lpv8OFQ8thl5uCOS32FnUvUSwlqKdKk",
	"Ntlo+CLqOpEJirpyDK7y3du3P7kdJv3RcDQ4GI72wpkRmJXiZptTQQORYpFHkdItIa7scTfo1Y9SXIqO",
	"/yFh3hv3/rRfqZ59p3f2QymzWeSZvdOiTbReJVJSwRckEXGRAddEL6kmHCDBAzkDovKUacK4FkRlNE39",
	"FqjhcPioAEWsPm6mgMoFV4Aaz2P2S8/IHJgume6N5zRVEPW8YPkQasYDs+9Gc43qemXkiVGuEUUgk0pb",
	"zA3in6MaqO8cqIM6qO+6YSmIBU8CYB9LkeQO++emeAzW1NyjH5eAkkiCKlJN7qkiCuQKEiticGRF6JkQ",
	"KVBuZgjFbc3ukJKuS6ujFAlMQ6Z24qpexbPUwGqI3LrSrglXGuuCpunaiNiE9DO6dsrIrsVpOEgIm5M5",
	"TdMZje+IiONCSkj2dpGaDQYrV2fxiwJCd7JdebTq20NzNi1kx/reX517y8erZMhmkCSML/ZLzWL2i8VQ",
	"w3+pdT7e309FTNOlUHr8cvRy1AvkRSFZl6A0JDGcmUsmJNPrmvj60BOcPxjzKqW9qLcQZpV1jF/Z8cSP",
	"J0IatW4Emt2jVFCDvTVHBQ6jKUnArICoHGJjXkg1nPDXiOqY3Dqcbo0S9B/GdsSts8nceIcpCo9bWmhx",
	"OzQawdNOSwaKALf/o3lnkDOWRqEgPKl0RVlKZykQN99/2BkmPBbZjHFrP6G0UkWeC6ntaFwjzvnsmSOF",
	"evaM9BPIDVUEJ7OCpQnRdKH2xhM+ILcLcUsG5LKQQN4IY5eDRG3Qp+k9XasKlYicXL4ngqfriKhU3IPS",
	"ewjBbIqBgRrjquCaZUD6jk8VGZjJ/jLBvYveXd1MehGZU6XL8Q8pNcPfiIvzn8hP58cdYx9SGv10fmyG",
	"3ly+3z95//3x/snl+z270u+RNurZM7siJDwZkONCi0ECGmJNZlCjat/tlEUgLhLE4O0/zr4/OyYGOnlz",
	"+d7+JiRkKYLLjXl0IiRcnJvDHb+7dtTA4z5bIwEsRJ0XdklikYJBmfT9Qz+dH7tZ7TOvhYyhJK1d0Kk9",
	"R+WKPljqmeUjLewfCzHpfTQgbuTa84myjG1IUDGltiZtCGps1lzCG+u8sB/sb/5TOcOlBCPG3ly+j1By",
	"4XSGy08cmUqwSK7GaEsrRMyRj8YxpGDt6UnN5P1QoWcPusGtF5WIuS/tX1YClKK9bXY1xLjzfKYK4sJL",
	"l236gHI9T9eDhZimbEbnUxVLagzPqciBG6l5YgFeO3iVQXIHkE9pylZQtzFHLQPzB3FvjRAtiBnlbS4j",
	"qIyq4CSDTMg1oXPjHaZUacNwpP8uTWlGBwZtqtkshb3hhF/YwVQC8oDxsGOrkrgDaMFoo9AT74iJOWGc",
	"xpqtmF4PJ/y9QmGQBI4aisJJ70U26ZH+C5IxXmhQe2afD5bmuwOyFIXEL0bmM4cVSDdtRIAuDPJW+BpE",
	"f1wCJwrQPrMjhCQiY1pDEnkamGU4tBFAuiZG4hkbpchRboazGJ2bwoLGazKDJV0xIfeGde7qvci6tE4q",
	"Fk9lhVQsFg1OcFuPvqDgqNW5nnq/tm6I7+AXliACoVw6yTQ1EjgZTvhxkjCnxcpf75k5okA+FVBAQorc",
	"UNnghV9MFfsZhhN+bak/Qu1Y8JQZJZVUsrFBu+edvih9mFraT+2ePXWZbqc987e4XrGsSDXlIAqVrj3j",
	"IPsiwsYqlWDMniRCFZiCOSESYuDam2JW9TMVMMr51Xti5KNBbG8XYpB3PF0TmM+NMF2BUfycVMfcQOeC",
	"D34GKRqEO9pEOLvEaTbbjWiOIn3GycWrPefKI75uUZaW3TSieS6FI9NGEtkT54m0E1VKT4oTmqyYMhja",
	"SQfOHnZ4T3ih6MKooxz1lOBuWww3KjzMxmDWkOVCUskMsR9igMQuZEXTwjDtj0LeGfYXfKFYAqTFgM5F",
	"5zBYSMq4DRVpKdImO4+++3bTxlTH5KnsHEaxEIrlkw0yIWDeatfcsTW/zYs0jQiH+wqu2TXDbi9GR+Ta",
	"Gt7kPa8sG9SyV6DlenCMkn4JNAG5eS/tZI/w+Sb8J8VodARk1KDtwWhz4GqqtKQaFt73KMXXZSMGXGTG",
	"GkC534t6Kf153Yt6M1HwBJLAvamkeH1vLkEO6ia/m3iNISTJElBDckFzFcS1cN/0EphsjaqUKxdGJFu2",
	"zGiOp9BsmyNhNY8NoolQTKA9dzYPvvmL05d+A8Z1XUn65o9A7UU1nbfXgme3ZDQmhmINKIKTBDLKk8gN",
	"d9YAS1JAWxpZ0Af6lsYX92uZ2J2Y9MKl29WgfPHWRaWe+1SRnEptjkUuocIWn68r7ojACnhTprqlkH7O",
	"OA+1AuKKkgf1oCIZezCrtJQzogQX7wQCs6dK0QxILlqC4JfebAEDjO4MgA9WB8MXvXHJd/FS8Lt1b2wZ",
	"sCucZWeZJqwjqv+KKiAJkxBrIxiNJKKMVxEDVcz8r8ywo/cUKbouTMWGVZVfyFyKzDoEv1STft63LjlI",
	"tW+M7VPvoJfBu8otqQ0rw7ZmVD2SsXmQBEmrUVf4qWPYhH8fuML/e3+o7cL2/XPG8lsxSlYsB7k3NCxs",
	"jpUCHaEfhH6qHjDeiLaiqvHCrmnctebpsvUcK7b36pwpXVoklTRwz9c4u9P0vlmCgg7LlWUZJIxqSNeW",
	"wf0m2xROROhKMNww9P0HTriSlGrgcSl3HEZqKYrUqEodL4leCgV4LMotCriB9GG4GBqDvMXgk57BeHeL",
	"hvRr0sRM1zQPP3Qco6gXpywfrJjGhMIgN1gfHT7NaXP0mGqWgSj0Y/6U18kYhdCC3FOmUeVRr0QxJCwM",
	"1hoilwMyq3L62jxvBm/1g45Gyjq5B5n93/o8gjgsIxJY0VdeXVqDBjMXRni5ZwOd/py8oRru6Zrc2N+a",
	"LH406mRqdTSNJSTANaOperJbe1S5MQGUZrTRhwk3hBaNI3xJpe5MBdufrT7AYFyRapaJhKZVRJH0MWQr",
	"JGEZXWCyVnB4N8fI97b13MCDDhH4HG1//syAf391Xhvz8XPUQ9m5MTPBeF50rO7MfF2uUAu7oCG5rgJz",
	"EsDxjkL5fc34IgUbobabOCa3k94S0lSQeyHTZNK7NQ/Wg9n2UTXGcAs+bHnPjfhYHxLSXJF+RfE9A+CX",
	"CW7ipGe42UC3oOxf5jsH/3NEao/i1hg2sM8HH8fmQffXpJdQTcf4637OF//THP9vn0fD4XDS+/zZYFqX",
	"HcHSe8YGj5eMoy8njbY0LFexQiNT36Il6c9ofHdPZUICCd1xbLanDhy1N0LbWYJtnCY4BI3Nqh0Etbdz",
	"/qJ2CBp4fNycx3hrTCMX6Pf6w+nBINHbUC81udQl+9t0kQWPqa47VVoW0MqAugcJHjlzpuZMO4SQUg+a",
	"pMAXetmRGmpILZ8asae3S3a5U9+ZjSuFk+qNP3wYDUcHh0fRYDQcPX/xbTQajv788ruPkfn+8Og5fv/i",
	"2z+b719+9zFIi7Wp00qRhRNtZJhKVK7QZlSkLzhgYthSytK6xi/lH4+latuad8csmDVPMIpgRHuJ5FMZ",
	"ZMPGBZTp3D0pbSK/QU//dR1XfJpkoBRdwKMoWCBds74BDsYz2q4s1CZtYTgYrcuFg4PnrC4SbyTlyhiB",
	"5rk3IDPKx+QHIycjshT3aGKuRfG/nmZNPSIBruHT4TV82nD4HbaiefrnKeUD/cJu8M4b60i0nbzVqWxU",
	"3GxfR1bnSYe4eaZLLpndaMPySCRuu/rUn0P8QxlPJTh8kZXneWq/mwHNug/io3tU/7yBehbpLuJ586aD",
	"+cwvBLO6khgNTd5fnbWKmTangqtBpL9RwdcT2d2PsX+8end1P/rbm4XYpZBik9XZZchtWLRXsDUJRfrv",
	"cuDHZ4En5+y0vRZVSkvnMSVckr/cySqaVQH5+GjxiPk16hxREeBvb14VLE18XdsuBXd3XNynkCyALCTN",
	"lzYhbKV1fcEJJEWeMqOHpxJShKAeVd1XkIkVkHIoKYcOiYsJEDOus6YjY3xqvA+9nsZlXdIjIVjG0d2r",
	"nrdbbKBgSMVPOhrW6g82KkGDg8f5S7HoWPuuaCiWsZRKQ4pNtVwvX2xCoxpclW5VZFkTCUqkBRYzBoi9",
	"fLETZlrS+G6aS7ECTpuU6bbmaHxH4MEMRDasxu7AE+abaVYoPcWYxw4MiGeo5ACjPZd05eJ/Bhomw0Au",
	"Hp/9c+eRO00WsKFuLWCVDUV2KhYSagV1j1M8lmDU0JR210/Z8CYe6XuqfK2XHRPCT6iGgWYZdOnAriLo",
	"95x9KoAwjAjMmaujwdCFma07ulYrLOoM7nft2rGcMS2pXJM7WA8w2UOo1pLNCg1ByKPahyYD1nxCUcgY",
	"lHVpMMfizuGS5bv6Un97c1nN0KGkFc4x7aLb2ffembIPES4SIP0l0MSdwL0tRaLbIWpXHIoQNWXpVohO",
	"/TRPSEUNeyDKQOHcplfKsMKdmlIXGUhFjEzI+KTXOVmRJ0/gUqxjyESC1dw7cmlXfXq1DSEBI68+g1PZ",
	"rT8vQFNjo3Qc6F1OndWhZkFPPXA1gE3476rCtOrrLiCucHUai4J34FmVTfsnsdY9BqXC8sIgR1dCZEmX",
	"9/K9sukcB6IC+5SASM9wwSaUb4SmaZBRNc9233PgNIMtpLN16u5+QMPq6aKlOVK7ImWe7UZqp1NQcc2v",
	"PAYdjPxWJF1aiXLBWUzTaTe1LiXLqFzv51jgJSEJycaUEy5d5Nqm744XCwkLdJ3i30H1oTD83VSfma0L",
	"jDkGlYlcI0eaElXIObVmYaZs5aatqcOEc0jp3Y/Rv6eybS/kS9Rstwo7tXZsXXnlIJXgro5RLihnP9sC",
	"w0p/4adfr71KRvuttFfjeO6uti5rG9I480sqp2I+V6CnwJNtd83sU66IGfVzZaUDT7pFXAgfc5i/doYZ",
	"LBjvnqN6CvN+StMs32ZWVEB9Pf3Ox9+NFXK6TaRd0fuad+cvlwUz+8jM41KtmnLHkGo1Scnti5RxkFMM",
	"uW3gaWcbeR3dnuZ7f+/F2JeS5FQvt8DpvmTzrnZFUeXU1aWvGaSJr96qFrAF/mNXEJwx3WdzQnMML3Tn",
	"dTr1o9f/b4zq/cLLR82oi9lRG7VI6aysgdwgr9AhdfQg/Tfn7O3pFfkZpBiopdDk7enV3nDCXT2Eu5eY",
	"RPaCgI1q+lsGrQS8FYC9qCb9elEp+noRnoTfNGAcXisMQgz73uUKtr5KiWIS9Or01el5WNoSRpolpEH9",
	"goQZpIPUmPdWmGe1b7BOxVFyAzwOcr95dgYYr9VU3SGIWtgygN/FsWWAaNOGt3yszm3vINKv3nznuvWi",
	"0m/zO49Om1EqIKZi/rTd3xAav/H5C7+iMtpCeVK523YbDFf4KOMGYzxYx2kqOLko1B1xKyLXOY3hJ8I4",
	"ORyNDoe9qOe/UVjd+KmgUoO0BWI/0Hu9FJJDRE5oyuZCckaHT1n0k+PtTdmyKWVhPZntrILP+Iq1Np12",
	"NKkwQtV1lgNndzuE0i3eVQJ06KpNTtZm+Yi/fvHq0RPadVtLknjcIrdPXTttC0A377AvqetwAcoC3bhZ",
	"aefuWZV30Sf28p/V6eEBd1cCbUXiIDPGhHY5VZRkKeOLgqaDg6cd8TKjvw1raFYV7lYX0F0U1vpuwF4O",
	"PumnoV3lIrfh7fOZVQJw0wI25DY/tJKbafZpMUD7gQk+CDKLT0MfVdA21OsKrV8zEWyZd1woLTJidVCD",
	"W5yK80g3Nd7TkH0E00f0boMhDNdiNSDHAtuEKc1S/NZ+UcP8iZWC6TY0O7TtdvMDLZQGXeuGQWiHPBVX",
	"V0i7HeN6fW37aHkwg9XhIDv6AjVXiq4QtVA4WC6onTtL8S5B+fb0yor0Di34BI/Upas6urgEVw263Ec8",
	"Eo+EDS5PryLy7upNRM7fnUTk4uz6pJ66vjy96vRWYiF3zfEYE6ndN+G773bKAD7JtXakKl3qarqntYhx",
	"cFzbl4oYfxVLTq4z1uUhdrU98Hvg14FdY3qeeht4ZqNftsnMPrES0CFtn+oytN0xFzxdl5cPC2UOFq3J",
	"2YisRUFiyt1V8DWhfF3SpGHGRxMOnM6M2iVt6SwKX7EmQUtb9d9l25fXtr9R5Q0StxC8jKXwbtAGRw/r",
	"Fvja5u6TItZfw8UrqfOodG8J911LbTb7E+26qIoTyb29DKbdRWvjGthb2mc8Hhr3gHFyUiAfcfF1nQDk",
	"3o2Wv1vNttI+y2O2sqhZ1mem7a4l2mYJV0L419f2bTDy33aJxk31e37xXWSzN0g2nvtHsGroxw417m+r",
	"tGoRG4qzO5Wd5V3MeinNcJ6gy1m1jvEsbCEPCXZfShle4FVEWubwJUalDcIXE259ZgOQhc1o5gzSRO1r",
	"yPKUalBkBnOjWGKapuUdAuBJLhjXLRlxxrUVCdgpQpBmTbWtu/oeL926r8i84Ak1c9MUG9w8SYp8KkCu",
	"uzqpURkvCf7qi2JgRb2ebNaJNtH0oT6bWtmV5ywu1R5uY73fpsKwZMWNJkO36x+QAoJzbxGPbNGKaxOi",
	"rDSoCYKnFvVuoJdDsItMzcsV3V2WOsvrWiVlW9o0Ne9PbCtn8NV0jf5K2wvpNjZj+gdIxQTfzAgYu8I0",
	"RMcFP9tOpUxRhKx8ODp8PhgdDA5e3ByMxkej8Wj0X13LWjA9jUWWdbVHesMMacxvZElVLVTWo7P44PDo",
	"eSdIMV3ZZXWAFES6Ji3+mRDqQhwMD19glVoL7EaY/kpbF8DVwXDUBa6xTdXQgB5RSPzasrp2snmvyYda",
	"qttNf7Sq/KNV5WZ+2dDTo31T1D5XbwuJoq+82mlv5qsWv6SwgvRLe42cIxDcpbW9pvIl0K4RSGfWbDdE",
	"ahcyzWlp3cn0BFuBnBmWWRNLh6gU5QnMigXeCcDh99Q2wvT3Lypp4h5oiabdVllDFe8Kc5puRFcU2ljf",
	"9vgTJPaQfOOH2a6ZsUiFZD/bShclUojIN/9UgruemloWsS6MofjX63dvI/JNKhbzTNtfbatNmM9ZjGbi",
	"Haz/Yqsxcsqkisg3XIjcd+dMgethQLIA/X8ql+czsDGSLfI62YKHHyXdhuug7bZxcQxKTe9g3VmzePzj",
	"NbGPmIWRs++DK5F3sFba2LJqzTV9sCuEWIImqRB3RT4kr2maqrLP1PGP19Pjk5PT6+vp307/c3r2PQG+",
	"YlJwtJRXVDIMmLHyGnm9CelaFHJgkRncwXrAOu0Lb0t3yNij8IqAf84nFL9RR0Oa0Z8Fp/dqGIvsGyKk",
	"2Wrf/O670Whkt/GC8bN39TBTc3APa9DP7fW28UGXOYmUmlb07ya+I2i1B1+6AdenJ1enN8E+/IpNsJME",
	"e9FpL4NSWPphDsiWEj+7SnzWHiZ7rFwLmTUJ7kQ/ae1daOMsA4tRV/2QgqlS6aPl6afc5iWuz/dvzq9x",
	"7usjIzu4bdKmyk4gY6xKxyeOf7zGvmtlu5+YphUr7VK1/is7mbXPvO07NTVsrboKcpiG1DVScM8S8yw2",
	"L9g/u7TteVLG70gi7rH7h8LuD5Dleh2ZMfi8a2HmIBizCHJNcslWVAMxcNiczFKBNxHwyynLbYtSWcDe",
	"sO4Luz/d6YoTPqx/c/Dd4XA0PBw+MXPmiZFTvdyVGOZZkkuYswfwvYpSGO/vY+ZcHZm/3l+dt4iCc4RE",
	"GZLXweBCAaEzvNUB7lknnPbfK5BqP6Ga7u/ZQXYWM2RWxHeg9y0+fkS2Hrjvixw3aL9JzxCmEVetAU+j",
	"Y2sfHz1Fr8yIWrOlijWIpHxhfOmDwz8bz2M42n8ZkYNR8PefD4cH3+Kng8OImN0/+Pal/fxtRA6+/W54",
	"+OK5+7zXeSvFM6/vSjG1XXHrmB+1Wzu7jg9m3xlP2IolBU3Lo0DMUXOlE4wTDzPsJTZC7cAyYwMcbOpf",
	"VWKn2M8wna011BE7GD1/+eLP3442NrQy42zV+L3vmOYddMaJBVhLwpTwSuRGj/gajOtvn3uE7S23hGXA",
	"KwfTIXs4ev5yE544jtyzRC/3l8AWS8QvZw+YMrW358tueBLMsuqNdi3wbRRtS1PzFZqhtmBM0xgtBltg",
	"3TtGSduL7DVKbISrxvv7C6aXxczIG2eQJ7N916ym3bvKuxG2r5rrNpOyO3Civ2oIiL2SZdmw2/Vtvziv",
	"esFN+J/+RH5cUoxCOsBhU1qXiVBeq5wH0G0v0RKDwAQ6vjzDIq5nz6p+Q2/KVPizZ2OCUR3s6lZ1Oeif",
	"nJ9d7rWKCSwgHOD7EBkI15BRrllclUwgPmFjct+NfYAM63sqW3hlcyIDq4q0SRi4uKNT/BietO2nHSZv",
	"aQYJccnCK4jFgls3t//29GrPgDt1aQqbiFERCSvuVER8xZ1/CwE8aAv6dWG8AQPiJKVKsbkLbSKlfC3B",
	"Csr2UGiykDylnEOCfZW8qMBeh1QDdvJLgRoFoIlnN8tjQyb2ExGr/VLXlvwAGBR+r6CLJ2LKiSy48dx5",
	"QlPBAV8AUPXzopxYPidxWigNEpnhHDmo2p8GJxnBBw8aJJpul2euFSDwmAFSvs1mt/s0Z7a25LYyu2tB",
	"RhxZskrV9Ntv8NXxG5KzHFLG7SwhK/j0AcrjDKvcE88SnwqaMr02Q06Aa0lTdPPczhgHny8IjaVQiiRM",
	"ufL5xBYxmVGXRiXF60EuwT9eO114hdo1QkuBrkARY2uaJyQtPcc9t2WvgZqPbgf/RLrOneUxW6VkeCw8",
	"KrWWYr69+sZGYhbS8eUZgtltX/yxs3FUYvtnIx6vGDfmeNnjLkJv2K/kohIQzkZ3gsICtPe3y+UiQPMz",
	"Cfo9/hP5wmz+wKqESsSonMbgIGEyLcQLb6OXl9oV6d9uvNZ+u2fOgDHNLDB3c/ykJIoB+F6BavRycdGD",
	"/u2vaqPjGubcOlqY83pCFXaGJpYwllsjgow4sGSUoCWDFU0jsmLKWBjVjWBP9Zq4bTLO60qoloep1RB8",
	"j/xHyGEBDPK947O1AXa8sZndxo50FtaJff2KgXE4sB2Hyc3NuW+Eis3unVh1kh9xr/mtzfZxPnEzpywt",
	"z1KpKnZdQ3iwOhYSdMmzEP9eGPH0c6kcj+u9mQ3XfLKPVK1Y2bwidcC/ZngtA4kizyW6SN9lHJeUJ6lx",
	"MBikSVhejGnClMXgUh3eaklTcmXsJ0WuwL6AoWXCVDolhQXFAKRm2r5Po3phTy9IE/RWBzTNl/QA3/di",
	"Pc3euHc0HA2PelGv9JvszqO3KVRX+CVPmTHzzUo73sXhSjmUVwJ1q6BRcOlNogvHtJYDkOGrLohtXrdt",
	"u1pvyMH3g+jqhQL25TTm4fe+GeBfyoJO8/VrqqxZlICNyTGlWezRQL66KI9T2wIqW4p6IRMe7AG52Cbr",
	"g8R4/aQ9+cQQdzLNpytrOaFriicy7N5sZPOhbxY+xGGA0cCy2nUm9NK/zMmQRQfJQL9Vrh2++XR7e/tP",
	"ZRTdLxNOav3KNrzSBQVoZB+201gRywkxX+HSLAC3SZH/qfbOHvPIi9Go/LH+8iL7a/lj+bogC3gy4eZf",
	"z/z8ecI/4yrwHJbu3lni3yZyY5MYzrV9JZK1dzPcDZ4gH76Pcd/ybWw7vd3El1p8rqdQjJONX1jljafy",
	"cDT6red2KVacvCsJjGyZEFVgeHBepCkGCJ7/hpjYflEdGJzxFU1Z4qMKZt4Xv8+8ziR2vhy4B6OeKrKM",
	"yrVnjQ75p2Bhb1+bx609tlmK+n5GynUPC2xoF5AIGxlamZo2THrl38dWGuNMBX3xnIeG9uI3qm4mOkPI",
	"RmgfdGTrXoxDwBNFmEu7thvyBP6j94cMjMAEbIv0xmsQtsrCsH1u1eTVdf80XpZdhR0ReCFaEAzuVb23",
	"A2y8QzvAZraZM6x8hK1VAL83JscxhjjD1oPOGqnW34SDVnJ9qKGpi3usGK1MW0eimglsuygHzSmRYI7I",
	"kHzVVpVdTXQ3t6/cqWOltZW/Tr/Kjk5Re1+oC4P3O2CSIg7f4EDxpUJlF6Vkwp2Ng9sxTzHUZbsTrwwI",
	"CUnBE8o11kT6A9H0xczXZRqk7FZWlt5gfavhGsdQtnW8e6lOIPhErEEPlJZAs9vSu1MgmfGRbTzD+3oR",
	"yYTSpExy7rWgGTF6O0aP0FfJOTkSvG8QRUXg8od2geVjw3VhY68Wd43b1kOg/TtaJDurAcWieehDg+3x",
	"ImKjXG3S+1hp+Am/6Gxz22al7bh1NlHuwg/tj0fPCSX5UmiBcRwSU20OTcfQLzs5rsObO0AG/Mctpo9X",
	"TZWX/5VsoFqH39/ZBqr3GTVzbzpUdZiN1AeetoE/bZC0u4KGd9Bn+HhHAU3LDqloX3al/PexxJ6Pnn/9",
	"eV2fdaHt1dN/KwvQn5BAClqjr7wmaW9JbrT+XMhabbiqu2R5EKzG37D0zjhUzZaBKJzbreScVP5B3JMz",
	"TfBFLeargyF59swF00/LQEQQRVf1an+LQF8VmG6xaNrUi9qb8MMhxhjdTa46vNfMWJL1Jfl3w/opJvwo",
	"wOeqxN6MvwBp7CbnUldYWdX7VyrF4EfG79DwDtzu5wYg3v0lr9w1Z4xRYhsa5S619j20PavL8J5vv4ar",
	"NyiuvQEWGLQ398JftUct3TTUXBwLr9Q747d/BbHIMuAJ2BdvnPJkoMUAgm0Pr8L5IMqnQ1W7MBnGFXax",
	"pyWkNqxQWhqHo9F/VFPaBYhC+0rFmXhAy69hR4/JbXC77jYit+Ftu1vX0dxderULfEDvABcyJrfFyiYx",
	"8BCofcBfpwhjmK9vPdHc/Z8q6vJf5V0efymjm2I2meDeVFi/R9R4NWMXufvlXUy33r2nEpqD3L/1plCT",
	"n61tD/YQg2y8DQ5P7QqCk9fsSOT6JUqg6QDtHUcMtAYnwSUcax2Yz+6vof+e/L//839to8XEea3WlzAH",
	"ArMqvnzS7HnQsrJ6D3FVCjMavnyBBMJmkipoIWnf7ZCmfibfhunx2FFgYbUbQkRVfEkFxtXk8f4EQQjp",
	"yX0KbJDoo5u81lTEWaC7NjmKrGUGk56H1uhZ4eDVOv6FPf4ifAdAibVqWLZX+LLyTdoBueStEXxjUhGs",
	"b5HfizzJ+uEK9qKKKKTvV7IX0qf2tSE25tCs43hqJGo42+CDW9vHgXtNlZ21nH3woVpv+UyJQoeVitK9",
	"3u3hK5mp3e1qfmd7dUNfiw4D5m8dPYX1H7bjv9B2NLMfff3ZjcJzte6kCN5C1+fCp7F8kTwkew2T1t6d",
	"aQuQ0gi0Bm71XskF6K47VFYQpUxpbEJH200rojKdEVVJ/4i8Pb2KaoUXZUOAMvPgY4M2ptdO+3XHEc2z",
	"fy/zeVgYy7WybYhvB+zlLVHFfM4efATJZWPsJMeb+oGQvn8pFgq8y7RQeD15K1ZhpsfFhFxucoclNfKY",
	"p1mu17a8t727Dvzb06sdADvTZUDO/Cob7ZuErF+pdtDflM0H7CS11xV0zBM09cDpbl5E5PX58duB+ePV",
	"8dWN3f/zi7+/Ib6lR5sbGhHlwCYzRp5j//CttLF/pWNLhZwzpS98L4evJrkbfWo2iSvlCwX+VY7+K/rv",
	"mW4574rrW2nkueTxNEvJUN6BbDBrv4MZQcfDvXY642l+QZPpG/OiFAIeiwTkEF/KThLATwPGmXZf2RR1",
	"9RBWGitrttezPTscnj/9iZSVKz478nc/ol422EE9XCDl6h7kwL/9By/IlIDkehMUVd0+LuMLZc/itovw",
	"WsjOpVQLdb7pVm+i1jFooD4VNBl8WtQDtt7+XjTXO7YvVY2XqbNIX8FaGD9nw9dG7qAoUuRUa0r+iq8J",
	"ZJyc0ISlKY2xglEmaliz4DeGYP2+fK0IbPPNOb+zUdt6s8ymXPQfMdD/RnZsJT1+vTnbllxWY0hbQGzf",
	"Jd2tMq78IwqzXUkVluk/WmHslEYQOrXaBu2vyqQa1gNFN+vciuJrLPGVCTkRb8/Pa61uXIH35ekV1pwh",
	"Iu4tpGUnzTAO5GoU3129waLREN9qgO3UYsMLVa+WcvD5uxMz+Lysny4HvoV78p9C3tmhryXlMZTDLs6u",
	"cdwFUzGkqX1dfBDz/SJ9WhqrZUDzU9u279uXW7OXqC33uhTlDwVeK31NYyCvTq9uXAlZtUftNqa+4CHu",
	"6nO0YtTWJ9jPtySnkmagQT4p9lXr2dMV+NrWcae5ka2mO9uVTsn4p75JzNdROkFvqd9Z34R9gbqSbv6g",
	"u8jwH+rmj7DJI3qmPDMNXeG1jXHZt6mages1k28sIi6LTKtWPVoQ6nr4BOql2Z/QK5kTW4R85XsesbSU",
	"w0FXpKxQeoz5QX+dxs3nWx+1zPXDIblCjDHuUTZGwpzeNfCkY03+La5UkVu3vtvy7fEJKLaw77xW4Wu5",
	"NaSgbObRvWDeoow3Da0sNvSvejalYsHiL/XbGtGWDm3jPUc7alr+gDrH3hGoV5bb13p0Kqx6eflT9EWr",
	"e1apNJBB7FNb+ziVA9yO1BIszcZVFw7SuYM0Jrh3i4IlQGw9flXkawBgTyv/NHkd9LQak7dQSJoSDtpp",
	"Mgk4uFGgYj1Bz3lOUVfcjuq8WVqPbbpt6xVkloFiCUz4bcpm++VQo6TjO7y0uGTxsqzTr1jp8SZfTRVq",
	"QF+6RldfR33Wu7T9zhq00aerQ5y6xbsN+kOF/ndQoeWVnS9RpAZEpfXWlb6zujRod7U19dDofhWRRdm1",
	"K7IJeOwQZoNq7fZbw45YjP5H2Q7rqx2sZuOzDiq7R8IeWP+a4HDD09aednXM8DHkRtXxpvjgkpLj2fKK",
	"0z7NWe/zx8//PwAA//8a/TXd554AAA==",
>>>>>>> Stashed changes
=======
	"H4sIAAAAAAAC/+y9/W4bObIo/iqE5geMnNOSZTuZzfiHxYXjcTLetROv7ezMuVEg090lietuskOyZWsG",
	"uX/eB7iPeJ/kgkWyP9myPJnMWeAMECBWN1ksFov1xWL1r4NYZLngwLUaHP46UPESMop/Hi8Lfmf+SEDF",
	"kuWaCT44HByR2LwgYk40PGhyz/SS5EIx854wPhcyo+bv8SAa5FLkIDUDhAg8mcVLKrtAj5dU0liDrEMi",
	"QrIF4zR1Ay1BghsceKLIEB7itFBsBTuDaKDXOQwOB4xrWIAcfI4GLOkOdAWfCuAxEF5ktyBxFksPdTiJ",
	"yF5E9iMyHo8DMKPBw2ghRu5pwbg+2DcDKU2l/p1mhrBUcD6mbXeA6xL9WHANXFd9lZaMLwafP0cDCZ8K",
	"JiEZHH4wdHHAGqhH1fp8LEGI239BrM3oyA7Hgs/ZIjBLfF5IXHgyF9KixPiCmJFBaUW0INcgM6aBHF2c",
	"jqf8eskUYYpQoliWp2zOIDGTmLMFgjAL8+P19YVpTkYkYfM5SEXmUmT4bl6kKUG0QFoEpvx+yeIlYTxO",
	"iwQUyaVYsQQkUZBCjMhRnpCYxkuDW1xHezzlHY7N6MMMZ6LsnOe0SPXg8MUkahHgnD6wrMhqbGW7mVlL",
	"0IU0sOGBZnkKtn93fTORQNoYZzBnD2BWq2fJzRywlxmmUDAmJ0wvQZJvseO3SEYkLhAt7oCPbqkyRHad",
	"IyIkoQ4EpxlY4uJvtRtb0qrdX82rz7vj+hRK1Fq8Fg3ECmRK8xkO+Bjd3pb0ct1yMyfbldyCvgfgjpSP",
	"E1BBTiXVQjaJOOW4si0amo1XdkBC4YxK2jQm60B05qqpXIAOT7Uz12tsXJc8dpo5uO3SnGFwinopQS1F",
	"mjQGm4xfRKEdmaCoK/vgLN+9ffuzW2EynIwno73xZKc+MgKzUtwscypoTaRY5FGkhCXEpd3uBr3mVopL",
	"0fH/SZgPDgff7FaqZ9fpnd26lOkXeWbttOgSbVCJlFTwBUlEXGTANdFLqgkHSHBD3gJReco0YVwLojKa",
	"pn4J1Hg8flSAIlYf+ymgcsEVoMbzmP06MDIHZkumB4dzmiqIBl6wfKhrxj2z7kZzTZp6ZeKJUc4RRSCT",
	"SlvMDeKfowao7x2ovSao78OwFMSCJzVgH0uR5Db757Z4rM2pvUY/LQElkQRVpJrcU0UUyBUkVsRgz4rQ",
	"t0KkQLkZoS5uG3aHlHRdWh2lSGAaMrUVVw0qnqUGVkvkNpV2Q7jSWBc0TddGxCZkmNG1U0Z2Lk7DQULY",
	"nMxpmt7S+I6IOC6khGRnG6nZYrBydha/qEboINuVW6u5PDRns0IG5vf+8sxbPl4lQ3YLScL4YrfULGa9",
	"WAwN/Jda54e7u6mIaboUSh++nLycDGryopAsJCgNSQxn5pIJyfS6Ib4+DATnD8a8SukgGiyEmWUT41e2",
	"P/H9iZBGrRuBZtcoFdRgb81Rgd1oShIwMyAqh9iYF1KNp/w1onpIbhxON0YJ+h+HtseNs8lcf4cpCo8b",
	"WmhxMzYawdNOSwaKALf/o3lnkDOWRqGgvlPpirKU3qZA3Hj/YUeY8lhkt4xb+wmllSryXEhte+Mcccxn",
	"zxwp1LNnZJhAbqgiOLktWJoQTRdq53DKR+RmIW7IiFwUEsgbYexykKgNhjS9p2tVoRKR44v3RPB0HRGV",
	"intQegchmEUxMFBjXBZcswzI0PGpIiMz2F+nuHbRu8vr6SAic6p02f8hpab7G3F+9jP5+ewo0PchpdHP",
	"Z0em6/XF+93j9z8c7R5fvN+xM/0BaaOePbMzQsKTETkqtBgloCHW5BYaVB26lbIIxEWCGLz95+kPp0fE",
	"QCdvLt7bd0JCliK43JhHx0LC+ZnZ3PG7K0cN3O63aySAhajzwk5JLFIwKJOhb/Tz2ZEb1bZ5LWQMJWnt",
	"hE7sPipn9MFSz0wfaWH/WIjp4KMBcS3Xnk+UZWxDgooptTVp66AOzZxLeIc6L+wP+87/Kke4kGDE2JuL",
	"9xFKLhzOcPmxI1MJFsnV6m1phYg58tE4hhSsPT1tmLwfKvTsRje4DaISMffQ/mUlQCnau2ZXS4w7z2em",
	"IC68dNmkDyjX83Q9WohZym7pfKZiSY3hORM5cCM1jy3AKwevMkjuAPIZTdkKmjbmpGNg/ijurRGiBTG9",
	"vM1lBJVRFZxkkAm5JnRuvMOUKm0YjgzfpSnN6MigTTW7TWFnPOXntjOVgDxgPOzYqiTuAFow2ij0xDti",
	"Yk4Yp7FmK6bX4yl/r1AYJDVHDUXhdPAimw7I8AXJGC80qB2zzntL82yPLEUh8cHE/OawAumGjQjQhUHe",
	"Cl+D6E9L4EQB2me2h5BEZExrSCJPAzMNhzYCSNfESDxjoxQ5ys36KEbnprCg8ZrcwpKumJA74yZ3DV5k",
	"Ia2TisVTWSEVi0WLE9zSoy8oOGp1rmfer20a4lv4hSWImlAunWSaGgmcjKf8KEmY02Ll23tmtiiQTwUU",
	"kJAiN1Q2eOGDmWK/wHjKryz1J6gdC54yo6SSSja2aPc86IvSh5ml/cyu2VOn6VbaM3+H6xXLilRTDqJQ",
	"6dozDrIvImysUgnG7EkiVIEpmB0iIQauvSlmVT9TNUY5u3xPjHw0iO1sQwzyjqdrAvO5EaYrMIqfk2qb",
	"G+hc8NEvIEWLcAd9hLNTnGW32xHNUWTIODl/teNcecTXTcrSMkwjmudSODL1ksjuOE+krahSelKc0GTF",
	"lMHQDjpy9rDDe8oLRRdGHeWopwR3y2K4UeFmNgazhiwXkkpmiP0QAyR2IiuaFoZpfxLyzrC/4AvFEiAd",
	"BnQuOofRQlLGbahIS5G22Xny/Xd9C1Ntk6eycz2KhVAsn/TIhBrzVqvmtq15Ny/SNCIc7iu4ZtUMu72Y",
	"HJAra3iT97yybFDLXoKW69ERSvol0ARk/1rawR7h8z78p8VkcgBk0qLt3qQ/cDVTWlINC+97lOLrohUD",
	"LjJjDaDcH0SDlP6yHkSDW1HwBJKae1NJ8ebaXIAcNU1+N/AaQ0iSJaDG5JzmqhbXwnXTS2Cy06tSrlwY",
	"kWzZMqM57kKzbI6E1Tg2iCbqYgLtudN57clfnb70C3DY1JVkaP6oqb2oofN2OvDskkwOiaFYC4rgJIGM",
	"8iRy3Z01wJIU0JZGFvSBvqXxxf1cpnYlpoP61O1sUL5466JSz0OqSE6lNtsil1Bhi+2bijsisALelqlu",
	"KmSYM87rWgFxRcmDelCRjD2YWVrKGVGCk3cCgdldpWgGJBcdQfDr4HYBI4zujICPVnvjF4PDku/ipeB3",
	"68GhZcBQOMuOMktYIKr/iiogCZMQayMYjSSijFcRA1Xc+rfMsKP3FCm6LkzFhlWVn8hcisw6BL9Wg37e",
	"tS45SLVrjO0T76CXwbvKLWl0K8O2plczktHfSYKkVa9L/BXoNuU/1Fzh/7U71nZiu76dsfxWjJIVy0Hu",
	"jA0Lm22lQEfoB6GfqkeMt6KtqGq8sGsbd51xQraeY8XuWp0xpUuLpJIGrn2Ds4Om9/USFAQsV5ZlkDCq",
	"IV1bBveLbI9wIkJXguGCoe8/csKVpFQDj0u54zBSS1GkRlXqeEn0UijAbVEuUY0byBDGi7ExyDsMPh0Y",
	"jLe3aMiwIU3McG3z8ENgG0WDOGX5aMU0HiiMcoP1wf7TnDZHj5lmGYhCP+ZPeZ2MUQgtyD1lGlUe9UoU",
	"Q8LCYK0hcmdAZlZOX5v2pvNGP+hgoqyTu5fZ/63PI4jDMiI1K/rSq0tr0ODJhRFerm1Npz8nb6iGe7om",
	"1/Zdm8UPJkGmVgezWEICXDOaqie7tQeVG1OD0o42+jBhT2jROMIXVOrgUbB9bfUBBuOKVLNMJDStIopk",
	"iCFbIQnL6AIPawWHd3OMfG+azzU86DoCn6PN7U8N+PeXZ40+Hz9HA5SdvScTjOdFYHan5nE5Qy3shMbk",
	"qgrMSQDHOwrl9xXjixRshNou4iG5mQ6WkKaC3AuZJtPBjWnYDGbbpuoQwy3Y2PKe6/Gx2aVOc0WGFcV3",
	"DIBfp7iI04HhZgPdgrJ/mWcO/ueINJri0hg2sO1rPw9NQ/fXdJBQTQ/x7W7OF/+/2f7fPY/G4/F08Pmz",
	"wbQpO2pTHxgbPF4yjr6cNNrSsFzFCq2T+g4tyfCWxnf3VCakJqED22bz0YGjdi+0rSVY7zC1TdBarMZG",
	"UDtbn180NkELj4/95xhvjWnkAv1efzg9WDvobamXhlwKyf4uXWTBY6qbTpWWBXROQF1DglvO7Kk50w4h",
	"pNSDJinwhV4GjoZaUssfjdjdG5JdbtcHT+NK4aQGhx8+TMaTvf2DaDQZT56/+C6ajCd/efn9x8g83z94",
	"js9ffPcX8/zl9x9rx2Jd6nSOyOoD9TJMJSpXaDMqMhQc8GDYUsrSusEv5R+PHdV2Ne+Wp2DWPMEoghHt",
	"JZJPZZCehatRJrh6UtqD/BY9/eMmrtiaZKAUXcCjKFggoVHfAAfjGW1WFqpPWxgORuty4eDgPmuKxGtJ",
	"uTJGoGn3BmRG+SH50cjJiCzFPZqYa1H8j6dZU49IgCv4tH8Fn3o2v8NWtHf/PKV8pF/YBd56YR2JNpO3",
	"2pWtjJvN88iaPOkQN21CcsmsRheWRyJxyzWkfh/iH8p4KrXNF1l5nqf22S3QLLwRH12j5u8e6lmkQ8Tz",
	"5k2A+cwbgqe6khgNTd5fnnaSmfqPgqtOZNir4JsH2eFm7J+v3l3eT/7+ZiG2SaToszpDhlzPpL2CbUgo",
	"MnyXAz86rXlyzk7b6VCltHQeU8Il+cuVrKJZFZCPjyaPmLdRsEdFgL+/eVWwNPF5bdsk3N1xcZ9CsgCy",
	"kDRf2gNhK62bE04gKfKUGT08k5AiBPWo6r6ETKyAlF1J2XVMXEyAmH7BnI6M8ZnxPvR6Fpd5SY+EYBlH",
	"d69qb5fYQMGQih90Mm7kH/QqQYODx/lLsQjMfVs0FMtYSqUhRV8u18sXfWhUnavUrYosayJBibTAZMYa",
	"Yi9fbIWZljS+m+VSrIDTNmXC1hyN7wg8mI7IhlXfLXjCPJllhdIzjHlswYC4h0oOMNpzSVcu/meg4WEY",
	"yMXjo38ObrmTZAE9eWs1VulJslOxkNBIqHuc4rEEo4ZmNJw/ZcObuKXvqfK5XrZPHX5CNYw0yyCkA0NJ",
	"0O85+1QAYRgRmDOXR4OhCzNaOLrWSCwKBvdDq3Ykb5mWVK7JHaxHeNhDqNaS3RYaaiGPah3aDNjwCUUh",
	"Y1DWpcEzFrcPlyzf1pf6+5uLaoSAklY4xixEt9MfvDNlGxEuEiDDJdDE7cCdDUmimyFqlxyKEDVl6UaI",
	"Tv20d0hFDbshykDh3B6vlGGFOzWjLjKQihiZkPHpIDhYkSdP4FLMY8hEgtncW3JpKD+9WoY6ASOvPmu7",
	"Mqw/z0FTY6MENvQ2u87qUDOhp264BsA2/HdVYlr1OATEJa7OYlHwAJ5V2rRvibnuMShVTy+sndGVEFkS",
	"8l5+UPY4x4GowD4lIDIwXNCH8rXQNK2dqJq24XsOnGawgXQ2T93dD2hZPSFami21LVKmbRiprXZBxTW/",
	"cRsEGPmtSEJaiXLBWUzTWZhaF5JlVK53c0zwkpDUycaUEy4hcm3Sd0eLhYQFuk7xH6D6UBj+YarPjBYC",
	"Y7ZBZSI3yJGmRBVyTq1ZmCmbuWlz6vDAuU7p7bfRv6ey7U7kS9RsWIWdWDu2qbxykEpwl8coF5SzX2yC",
	"YaW/8Ndv114lo/1e2qu1PbdXWxeNBWnt+SWVMzGfK9Az4Mmmu2a2lUtiRv1cWenAk7CIq8PHM8zfOsIt",
	"LBgPj1G1wnM/pWmWbzIrKqA+n37r7e/6CjnbJNIu6X3Du/OXy2oj+8jM41KtGnLLkGo1SMnti5RxkDMM",
	"ufXwtLONvI7uDvODv/di7EtJcqqXG+CEL9m8a1xRVDl1eelrBmnis7eqCWyA/9gVBGdMD9mc0BzDC+Fz",
	"naB+9Pr/jVG9X3j5qB11MStqoxYpvS1zIHvkFTqkjh5k+OaMvT25JL+AFCO1FJq8PbncGU+5y4dw9xKT",
	"yF4QsFFNf8ugcwBvBeAgaki/QVSKvkGEO+F3DRi7CYTjxRzkbj1P0VJp17tjTbaoYoaWtUcYTtVU3YV4",
	"pgzR9JG84+UECR9A5TeT3zlPg6j0nDzt0W0yYh3ETMyfRv+e4PS1P0HwMyrjHZQnlcNrl8TQ3sf5eszh",
	"2jxOUsHJeaHuiJsRucppDD8Txsn+ZLI/HkQD/0RhfuGngkoN0qZo/Ujv9VJIDhE5pimbC8kZHT9l0k+O",
	"eLd3d9+hgfUlNrMKtvE5Y106bWnUYIwotJtq7uZmCKVj+vgezPq0RZ+b0y+h8O0Xzx59kW2XtSSJxy1y",
	"6xRaaZuC2b/CPqktYISXKbJxO9fN3XQqb4NP7fU7q1XrG9xdyrM5gaPMqHPtTjVRWKWMLwqajvaetsXL",
	"M/VNWEM7r2+7k/lwWlbn2Yi9HH3ST0O7Og3chLc/UayO4Pom0HO6+KFzvJhmnxYj1OBM8FHtbO9p6KOW",
	"2YR6XbcpMmwoaZtoHRdKi4xYHdTiFqfFPNIdpfYkZB/BtIZmSAe3GMJwLebjcUxxTZjSLMWn9kED8yfm",
	"6rn00E3IylbWaJddPZjRan+UHXyB6ijFQR21+oazlG3wckjsvD25tAIyoFOe4GG545dAVZJa6nzIHUIG",
	"e8QNvji5jMi7yzcROXt3HJHz06vj5lHsxcll0PqOhdz2zMIYHN06AN9/v9WJ1pNcRUeq0kWshntayRMH",
	"x5UxqYjxN7Hk5CpjIY8ndI3fr4GfB1ZBGXjq9fBMr5/RZ7QeW3nikLatQmar2+uCp+vyMl2hzJaiDakV",
	"kbUoSEy5u9q8JpSvS5q0jOJoyoHTW6PESFfWicJnYEnQ0maxhyzl8hryt6q8EeEmgpeLFN516XFc8Bye",
	"r+1ZdFLE+mu4LJv9lWbWUktUbps60m+dd/N8Kk4k9/Zyk3YXh42hbW8dn/J4bIxtxslxgXzExdc1qZF7",
	"e+1oN5tNqWqWx2ymTDtNzQwbzo3ZZFdWQvi356r1mMxvQ6KxLx/NTz5ENnsjonffP4JVSzN2+LO6fdHJ",
	"rWupzPDRbJaHmPVCmu48QQeuKoXiWdhCHhOsJpQyvJCqiLTM4VNmSqeDL6bceqAGIKsXV5kzSBO1qyHL",
	"U6pBkVuYG8US0zQtc+KBJ7lgXHdkxCnXViRg5QNB2jnCNo/oB7xE6h6RecETasamKRZseZIU+VSAXIcq",
	"g1EZLwm+9UkesKJeT7bzHtto+tCVPSrYlucsLtUabmK93ydjrmTFXpMh7EjXSAG1fW8Rj2wShit7oaw0",
	"aAiCpyap9tDLIRgiU/uyQLhqUDBdrJMitaHsUPs+wKbjeZ8d1qoXtDkxrLe40D9BKiZ4PyNgJAjD6oEL",
	"a7Y8SBlyr7Py/mT/+WiyN9p7cb03OTyYHE4m/zM0rQXTs1hkWajczxtmSGPekSVVjcDTgN7Ge/sHz4Mg",
	"xWxlpxUAKYh0RUd8m0YwUeyN919g1lUHbC9Mf0UrBHC1N56EwLWWqepao0dUJ35jWqGVbN/T8YGL6rbO",
	"n6UX/yy92M8vPTUqujcfbbtmmUMUfeVVRXvTXHX4JYUVpF9aO+MMgeAqre21iy+BdoVAgqdA2yHSuGBo",
	"dkvnjqEn2ArkrWGZNbF0iEpRnsBtscAcd+x+T21hR3+foJImrkFHNG03ywaqePeV07QXXVFoY33b7U+Q",
	"2GPyre9mq0DGIhWS/WIzN5RIISLf/ksJ7mpEalnEujCG4t+u3r2NyLepWMwzbd/a0pEwn7MYzcQ7WP/V",
	"ZhfklEkVkW+5ELmvNpkC1+MayWro/0u5cysDG+PCIm+Srdb4UdL1XG/slkGLY1BqdgfrYA7e0U9XxDYx",
	"EyOnP9Su+N3BWmljy6o11/TBzhBiCZqkQtwV+Zi8pmmqyrpJRz9dzY6Oj0+urmZ/P/nP2ekPBPiKScHR",
	"Ul5RyTBUxspr0c2immtRyJFFZnQH6xEL2hfelg7I2IN6yrtv5w+Xv1UHY5rRXwSn92oci+xbIqRZal/M",
	"7fvJZGKX8Zzx03fNMFO78wBzqs/sda3DvZA5iZSaVfQPE98RtFqDL12Aq5Pjy5Pr2jr8hkWwg9TWImgv",
	"g1KYymA2yIaUNTtLbGs3k91WriTKmtTu+D5p7iG0cZSRxSiUD6NgplT6aLr1CbdR/quz3euzKxz76sDI",
	"Dm6LjqmyssUhZllji6OfrrCOWFm+JqZpxUrbZGH/xspc3T1v6yjNDFurUIIJ05C6wgCuLTFt8TL+7umF",
	"LTeTMn5HEnGP1SwUVjOALNfryPTB9q4kl4NgzCLINcklW1ENxMBhc3KbCsysx4czltuSm7KAnXHTF3Z/",
	"ut0VJ3zcfLL3/f54Mt4fP/EcyhMjp3q5LTFMW5JLmLMH8LV3Ujjc3cVzaHVg/np/edYhCo5RJ8qYvK51",
	"LhQQeou3FMC1dcJp970CqXYTqunuju1kRzFdbov4DvSuxcf3yNYj97zIcYF22/SswzTiqtPhaXTsrOOj",
	"u+iV6dEoHlSxBpGUL4wvvbf/F+N5jCe7LyOyN6n9/Zf98d53+GtvPyJm9fe+e2l/fxeRve++H++/eO5+",
	"7wRvWXjm9VUWZrbKaxPzg26pYlfBwKw74wlbsaSgabkViNlqLhGBceJh1mtjTVA7sMzYAHt99ZhK7BT7",
	"BWa3aw1NxPYmz1+++Mt3k94CTaafzYK+9xXAvIPOOLEAG4cwJbwSuckjvgbj+rvnHmF7aythGfDKwXTI",
	"7k+ev+zDE/uRe5bo5e4S2GKJ+OXsAQ8g7W3wsrqbBDOtZuFYC3wTRbvS1DxCM9QmQGkao8VgE4YHRyhp",
	"B5G9FoiFXdXh7u6C6WVxa+SNM8iT211XfKVbi8m7EbZOmKuekrI7cKK/KnCHtX9lWYDa1SE/P6tqm035",
	"N9+Qn5YUo5AOcL3IqjuJUF6rnNWg29qYJQY1E+jo4hQrMzx7VtXPeVMeLD97dkgwqoNVyqpb+8Pjs9OL",
	"nc7RvAWEHXxdHQPhCjLKNYurBATEp15o21cXHyHD+hrBFl5ZbMfAqiJtEkYu7ugUP4YnbTllh8lbmkFC",
	"3GHhJcRiwa2bO3x7crljwJ24Ywp7EKMiUs8gUxHxGWS+qj48aAv6dWG8AQPiOKVKsbkLbSKl/Mn8Cspy",
	"R2iykDylnEOCdYK8qMDafVQDVqZLgRoFoIlnN8tjYyZ2ExGr3VLXlvwAGBR+ryDEEzHlRBbceO48oang",
	"gAXtq/pUlBPL5yROC6VBIjOcIQdV69PiJCP44EGDRNPt4tSVtgMeM0DKd9nsZpfmzGZq3FRmdyPIiD1L",
	"VqmKWPsFvjx6Q3KWQ8q4HaXOCv74AOVxhlnbiWeJTwVNmV6bLsfAtaQpunluZYyDzxeExlIoRRKmXDp4",
	"YlOCTK8Lo5Li9SiX4Js3dhdeCXaFvVKgK1DE2JqmhaSl57jjluw1UPPTreA3JLTvLI/ZnB/DY/Wt0iiR",
	"5cuF9xbGspCOLk4RzHbr4redjaMSWw8a8XjFuDHHy5ptEXrDfibnlYBwNroTFBagvY9cThcBmtekVr/w",
	"X8gXZvFHViVUIkblNAYHCQ/T6njh7erykrYiw5vea9o3O2YPGNPMAnM3oY9LohiA7xWoVm0SFz0Y3vym",
	"sjCuAMyNo4XZr8dUYaVjYgljuTUiyIgjS0YJWjJY0TQiK6aMhVHdcPVUb4jbNuO8roRquZk6Ba53yH/U",
	"OawGg/zg+GxtgB31FmfrrbBmYR3bz4kYGPsjW0GXXF+f+cKeWLzdiVUn+RH3ht/aLofmD27mlKXlXipV",
	"xbZzqG+swERqVd8sxH8URjz9UirHo2atYcM1n2yTqrQom1ekrvGv6d44gUSR5w66yNCdOC4pT1LjYDBI",
	"k3qyLh4TpiwGd9ThrZY0JZfGflLkEuwHBTomTKVTUlhQDEBqpu33IaoP0AxqxwSD1R5N8yXdw++XWE9z",
	"cDg4GE/GB4NoUPpNduXR2xQqFH7JU2bMfDPTwLclXCqH8kqgaRW00he9SXTumNZyADJ8VdWvy+u2DFXn",
	"iy/4vQtdFci3H1sxjd/74nZ/LdMjzePXVFmzKAEbk2NKs9ijgXx1Xm6nrgVUlsj0Qqa+sUfkfJOsrx2M",
	"N3fak3cMcTvT/Lq0lhO6prgj69WIjWze98Wvx9gNMBpY5o7eCr30HycyZNG1w0C/VK68u/l1c3PzL2UU",
	"3a9TThr1t3o+UYICNLKN7TBWxHJCzCOcmgXgFinyrxrfoDFNXkwm5cvmx3js2/Jl+fkbC3g65ebfwLz+",
	"POWfcRa4D0t37zTxX8e4tocYzrV9JZK1dzPcjZTaefguxn3Lr4tt9bUOn2rxuXmEYpxsfGCVN+7K/cnk",
	"9x7bHbHi4KFDYGTLhKgCw4PzIk0xQPD8d8TE1j8KYHDKVzRliY8qmHFf/DHjOpPY+XLgGkYDVWQZlWvP",
	"GgH5p2BhbxOb5tYe65eivj6PctWwaja0C0jUC/NZmZq2THrlvy9WGuNM1eq8OQ8N7cVvVdNMdIaQjdA+",
	"6MjmvRiHgCeKMHfs2i0wU/MfvT9kYNRMwK5Ib5X13ygL6+Vgq6Klrpql8bLsLGyPmheiBcHgXlVLuoaN",
	"d2hHWJw1c4aVj7B10sl3DslRjCHOeik9Z41U82/DQSu52dXQ1MU9VoxWpq0jUcMEtlWBa8UWkWCOyJB8",
	"1dKLoaKw/eUYt6rAaG3lr1N/MVD5aOcLdWHtewV4SBHXv0hA8SM5ZVWgZMqdjYPLMU8x1GWr7a4MCAlJ",
	"wRPKNeZE+g3R9sXM4/IYpKy+VabeYH6r4RrHULYUuvtITE3wiViDHiktgWY3pXenQDLjI9t4hvf1IpIJ",
	"pUl5yLnTgWbE6M0heoQ+S87Jkdr381BU1Fz+ul1g+dhwXb1QVYe7DrvWQ037B0r+OqsBxaJp9KHF9oaf",
	"2ulq08HHSsNP+XmwbGuXlTbjFiwKHMIP7Y9H9wkl+VJogXEcElNtNk2g65ftHFexzG0gA/7jBtPHq6bK",
	"y/9KNlCjYu0fbAM162aasfs2VRNm6+gDd9vI7zZIulUu63eqb7F5IIGmY4dUtC+rLP77WGLPJ8+//riu",
	"brjQ9iLnv5UF6HdITQpao6+8dGjvHPZafy5krXouvi5ZXgtWBy9HYAfMx1NTTjuF8VBkdwumOVn9o7gn",
	"p5rg50jMo70xefbMhdhPyvBEGUML3fMO3Q+Y8v0xBh3dteR+UIGby9bbbVNhyg9quF2WMzEAz0Eay8o5",
	"3RUpLbn+RqUY/cT4HZrmNcf8uQGId23JK3etGKOYWHhFuUukQw9tx2o7vFc7bKC20zF0L/2X31pL1fzU",
	"XWjuw/JmnTMrA5/D2mg3c5C7N6WL3qaWtS3B8gvI1te1kD9WUGPGdoUXV39OAk1HqG8da6E1Mq1dArHa",
	"yfx2f439c/J///f/sYXrEuc1WVvWkBuj+j59z9jutRKA1Xddq1SMyfjlCzRdsDifqpXks7Xy09SP5Mva",
	"PB67qGn49mXHUrnjrYKacp8+ftu8FsJ48q1zG6T46AZvFGlwFtC2RWMiaxnAdOChtSoQOHiNCmr1mmkR",
	"1lQvsVYty+oSP/5s+D4kh5BL3pptdUgqgg0t8juRJ9mwPoOdqCIKGfqZ7NTp03hsiI1nONZxOTH7tT7a",
	"6IOb28eR++yPHbUcffShmm/ZpkQhYCWh7Gje3f9KZlK4/McfbC/1VCkIKNC/B2q06j9tl/9C28WMfvD1",
	"RzcKz+Vak6L2Va8hF/4YxSdpQ7LTMqns3Y2uACmtIGtgVd/pW4AO3eGxgihlxm8XtUObylSLal+GLw+d",
	"I2PTRI2D//Kuf6lWfWzKxpS6x07hOJZp+4/yPAkTM7lWtqzrzYi9vCGqmM/Zg49guNMAO8hRX3UHMvQf",
	"GUKBd5EWCq/HbsSqftLgYhLubGyLKbXO0U6yXK9teml3dR34tyeXWwBG2wU/ruVn2bwobHR6w/Z00N+U",
	"197tII3y74FxaiUacLjrFxF5fXb0dmT+eHV0eW3X/+z8H2+IL9DQ5YZWRLNmlBkjz7F//Sufsf9EXkeF",
	"nDGlz30Vga8muVtVR/rElfIH1f9VjuYr+u8Z7j8LxZWtNPJc8niYv2Qo7560mHUYYEbQ8XinG06vDha3",
	"cQzaTN8aF6UQ8FgkIMf4kWuSAP4aMc60e2SPSKtGmOmqrNnePG3YYvN88w0pMyd8dP4fvkczbS1APZwg",
	"5eoe5Mh/TQUvaJSA5LoPiqpuv/rb7FUN2K6L8FrI4FSqidpJbY4XNuq/jNSngiajT4tmwNDb34v2fA/t",
	"RyrjZeos0lewFsbP6Xls5A6KIkVOtKbkb/jZNcbJMU1YmtIYM+hkosYNC743BOjX5WtFANtfIvmDjdrO",
	"lzr6zkL/jMH9N7JjK+nx283ZruSyGkPaBFb7bd6wyrj0TRSetiRVWGb4aIarUxqd2CHaX5VJ1QoUXa9z",
	"K4qvMMVUJuRYvD07a5RacQnGFyeXmPOEiLivOpZVPetxIJcj9+7yDSYt1vGtOthKITa8UNUKKTufvTs2",
	"nc/K/N2y41u4J/8p5J3t+lpSHkPZ7fz0CvudMxVDmtrPb9eClF+kT0tjtTy6+9S17Yf2Y8HsJWrLnZCi",
	"/LHAa42vaQzk1cnltUthqtbIdGrawf7APQ7V2Vkxas/H7e8bklNJM9AgnxT7atSMCQW+NlV8aS9kp+jL",
	"ZqVTMv6JL1LydZROrbbRH6xv6nVpQoc+fqO7yPCf6ubPsMkjeqbcMy1d4bWNcdk3qZqRq3WS9yaxlkmO",
	"VakYLQh1NWRq6qVdGc8rmWObBHvpa+6wtJTDtao8WaH0IZ5E+escbjxfeqdjru+PySVijHGPsjAPnhhd",
	"AU8Cc/JfxaSK3Lj53ZRf405AsYX9hrCqf+ZYQwrKHtC5D3ZblPGmm5XFhv5VzaBULFj8pX5bK9oS0Dbe",
	"c7S9ZuUL1Dk2R72Z2Ww/kxBUWM305qfoi071plJpIIPYVhvrCJUd3Io0DljahZPOHaQzB+mQ4NotCpYA",
	"sfngVZKpAYA1lXxr8rpWU+mQvIVC0pRw0E6TScDOrQQJ6wl6znOKuuJ2VOft1O6o/LC+ZZaRYglM+U3K",
	"bnfLrkZJx3d4aW7J4mWZJ16x0uNFptoq1IC+cIWWvo76bFYJ+4M1aKtOVECcusm7BfpThf53UKHVp/y/",
	"QJEaEJXWW1f6zurSWrmljUcPrepLEVmUVaMiewCPFapsUK1b/mkciMXof5blmL7axmoX3gpQ2TWp12D6",
	"rwkOtzxt7WnXxAybITeqwJe3a5dkHM+WV2x2ac4Gnz9+/n8BAAD//+ukjX03nAAA",
>>>>>>> Stashed changes
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
