//go:build go1.22

// Package termite provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package termite

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Text Text to chunk
	Text string `json:"text"`
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl string `json:"api_url"`

	// BackendPriority Backend priority order for model loading with optional device specifiers.
	// Format: `backend` or `backend:device` where device defaults to `auto`.
	//
	// Termite tries entries in order and uses the first available backend+device
	// combination that supports the model.
	//
	// **Backends** (depend on build tags):
	// - `go` - Pure Go inference (always available, CPU only, slowest)
	// - `onnx` - ONNX Runtime (requires -tags="onnx,ORT", fastest)
	// - `xla` - GoMLX XLA (requires -tags="xla,XLA", TPU/CUDA/CPU)
	//
	// **Devices**:
	// - `auto` - Auto-detect best available (default)
	// - `cuda` - NVIDIA CUDA GPU
	// - `coreml` - Apple CoreML (macOS only, used by ONNX)
	// - `tpu` - Google TPU (used by XLA)
	// - `cpu` - Force CPU only
	//
	// **Examples**:
	// - `["onnx", "xla", "go"]` - Try backends with auto device detection
	// - `["onnx:cuda", "xla:tpu", "onnx:cpu", "go"]` - Prefer GPU, fall back to CPU
	// - `["onnx:coreml", "go"]` - macOS with CoreML acceleration
	BackendPriority []string                           `json:"backend_priority,omitempty,omitzero"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (never unload, eager loading).
	// When set to "0" or omitted, models are loaded eagerly at startup and never unloaded (legacy behavior).
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive="0" (default): eager loading (load at startup, never unload)
	// - If keep_alive>0: lazy loading (load on demand, unload after idle)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	// - `{models_dir}/recognizers/` - Recognition models (ONNX)
	// - `{models_dir}/questionators/` - Question generation models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal embedding (text or image)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// KGBuilderConfig Configuration for knowledge graph building
type KGBuilderConfig struct {
	// DeduplicateRelations Remove duplicate relations. Default true
	DeduplicateRelations bool `json:"deduplicate_relations,omitempty,omitzero"`

	// MinEntityConfidence Minimum confidence for entities. Default 0.0
	MinEntityConfidence float32 `json:"min_entity_confidence,omitempty,omitzero"`

	// MinRelationConfidence Minimum confidence for relations. Default 0.0
	MinRelationConfidence float32 `json:"min_relation_confidence,omitempty,omitzero"`

	// SimilarityThreshold Minimum similarity (0.0-1.0) for entity resolution. Default 0.85
	SimilarityThreshold float32 `json:"similarity_threshold,omitempty,omitzero"`

	// TrackProvenance Track extraction provenance. Default true
	TrackProvenance bool `json:"track_provenance,omitempty,omitzero"`

	// TypeMustMatch Require entities to have same type to merge. Default true
	TypeMustMatch bool `json:"type_must_match,omitempty,omitzero"`
}

// KGEdge defines model for KGEdge.
type KGEdge struct {
	// Confidence Confidence score (0.0-1.0)
	Confidence float32 `json:"confidence"`

	// CreatedAt When the edge was first created
	CreatedAt time.Time `json:"created_at,omitempty,omitzero"`

	// Id Unique identifier for this edge
	Id string `json:"id"`

	// Properties Arbitrary key-value attributes
	Properties map[string]interface{} `json:"properties,omitempty,omitzero"`

	// Provenance Sources of this relationship
	Provenance []KGProvenance `json:"provenance,omitempty,omitzero"`

	// SourceId ID of the source node (head entity)
	SourceId string `json:"source_id"`

	// TargetId ID of the target node (tail entity)
	TargetId string `json:"target_id"`

	// Type Relationship type (e.g., "founded", "works_at", "located_in")
	Type string `json:"type"`

	// UpdatedAt When the edge was last modified
	UpdatedAt time.Time `json:"updated_at,omitempty,omitzero"`
}

// KGMetadata defines model for KGMetadata.
type KGMetadata struct {
	// CreatedAt When the graph was created
	CreatedAt time.Time `json:"created_at,omitempty,omitzero"`

	// Description Optional description
	Description string `json:"description,omitempty,omitzero"`

	// DocumentCount Number of documents processed
	DocumentCount int `json:"document_count,omitempty,omitzero"`

	// DocumentIds IDs of processed documents
	DocumentIds []string `json:"document_ids,omitempty,omitzero"`

	// EdgeCount Total number of edges
	EdgeCount int `json:"edge_count,omitempty,omitzero"`

	// Name Optional name for the knowledge graph
	Name string `json:"name,omitempty,omitzero"`

	// NodeCount Total number of nodes
	NodeCount int `json:"node_count,omitempty,omitzero"`

	// UpdatedAt When the graph was last modified
	UpdatedAt time.Time `json:"updated_at,omitempty,omitzero"`
}

// KGNode defines model for KGNode.
type KGNode struct {
	// CanonicalName Primary/preferred name for this entity
	CanonicalName string `json:"canonical_name"`

	// Confidence Aggregated confidence score (0.0-1.0)
	Confidence float32 `json:"confidence"`

	// CreatedAt When the node was first created
	CreatedAt time.Time `json:"created_at,omitempty,omitzero"`

	// Id Unique identifier for this node
	Id string `json:"id"`

	// Mentions All surface forms that refer to this entity
	Mentions []string `json:"mentions,omitempty,omitzero"`

	// Properties Arbitrary key-value attributes
	Properties map[string]interface{} `json:"properties,omitempty,omitzero"`

	// Provenance Sources of this entity
	Provenance []KGProvenance `json:"provenance,omitempty,omitzero"`

	// Type Entity type (e.g., "person", "organization", "location")
	Type string `json:"type"`

	// UpdatedAt When the node was last modified
	UpdatedAt time.Time `json:"updated_at,omitempty,omitzero"`
}

// KGProvenance defines model for KGProvenance.
type KGProvenance struct {
	// CharOffsetEnd Character offset where the extraction ends
	CharOffsetEnd int `json:"char_offset_end,omitempty,omitzero"`

	// CharOffsetStart Character offset where the extraction begins
	CharOffsetStart int `json:"char_offset_start,omitempty,omitzero"`

	// ExtractionTimestamp When the extraction occurred
	ExtractionTimestamp time.Time `json:"extraction_timestamp,omitempty,omitzero"`

	// ExtractorConfidence Raw confidence from the extraction model
	ExtractorConfidence float32 `json:"extractor_confidence,omitempty,omitzero"`

	// ExtractorModel Model used for extraction (e.g., "gliner_small")
	ExtractorModel string `json:"extractor_model,omitempty,omitzero"`

	// SourceDocument Document ID or path
	SourceDocument string `json:"source_document,omitempty,omitzero"`

	// SourceText Original text span that yielded this extraction
	SourceText string `json:"source_text,omitempty,omitzero"`

	// SourceUrl URL of the source (if applicable)
	SourceUrl string `json:"source_url,omitempty,omitzero"`
}

// KnowledgeGraphRequest defines model for KnowledgeGraphRequest.
type KnowledgeGraphRequest struct {
	// Config Configuration for knowledge graph building
	Config KGBuilderConfig `json:"config,omitempty,omitzero"`

	// EntityLabels Entity types to extract (GLiNER zero-shot NER).
	// If not provided, uses model defaults.
	EntityLabels []string `json:"entity_labels,omitempty,omitzero"`

	// Model Name of model to use for entity/relation extraction. Supports:
	// - REBEL models from models_dir/rel/ (e.g., "rebel-large", "mrebel-large")
	// - GLiNER models from models_dir/recognizers/ (e.g., "gliner-multitask")
	Model string `json:"model"`

	// RelationLabels Relationship types to extract (GLiNER relation extraction).
	// If not provided, uses model defaults.
	RelationLabels []string `json:"relation_labels,omitempty,omitzero"`

	// Texts Texts to extract entities and relations from for building the knowledge graph
	Texts []string `json:"texts"`
}

// KnowledgeGraphResponse defines model for KnowledgeGraphResponse.
type KnowledgeGraphResponse struct {
	// Edges Relationship edges in the knowledge graph
	Edges    []KGEdge   `json:"edges"`
	Metadata KGMetadata `json:"metadata"`

	// Model Name of model used for extraction
	Model string `json:"model"`

	// Nodes Entity nodes in the knowledge graph
	Nodes []KGNode `json:"nodes"`
}

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Extractors Available GLiNER extractor models (zero-shot recognition with custom labels)
	Extractors []string `json:"extractors,omitempty,omitzero"`

	// Questionators Available Seq2Seq questionator models from models_dir/questionators/
	Questionators []string `json:"questionators"`

	// Recognizers Available recognizer models from models_dir/recognizers/
	Recognizers []string `json:"recognizers"`

	// Rel Available relation extraction models from models_dir/rel/ (REBEL)
	Rel []string `json:"rel,omitempty,omitzero"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`
}

// QuestionGenerateRequest defines model for QuestionGenerateRequest.
type QuestionGenerateRequest struct {
	// Inputs Input texts to generate from
	Inputs []string `json:"inputs"`

	// Model Name of Seq2Seq questionator model from models_dir/questionators/
	Model string `json:"model"`
}

// QuestionGenerateResponse defines model for QuestionGenerateResponse.
type QuestionGenerateResponse struct {
	// Model Name of model used for generation
	Model string `json:"model"`

	// Texts Generated texts (array of arrays, one per input, multiple per beam)
	Texts [][]string `json:"texts"`
}

// RecognizeEntity defines model for RecognizeEntity.
type RecognizeEntity struct {
	// End Character offset where entity ends (exclusive)
	End int `json:"end"`

	// Label Entity type (PER, ORG, LOC, MISC)
	Label string `json:"label"`

	// Score Confidence score (0.0 to 1.0)
	Score float32 `json:"score"`

	// Start Character offset where entity begins
	Start int `json:"start"`

	// Text The entity text
	Text string `json:"text"`
}

// RecognizeRequest defines model for RecognizeRequest.
type RecognizeRequest struct {
	// Labels Custom entity labels to extract (GLiNER models only).
	// When using a GLiNER model, you can specify any entity types to extract,
	// enabling zero-shot NER without model retraining.
	// If not provided, the model's default labels are used.
	Labels []string `json:"labels,omitempty,omitzero"`

	// Model Name of recognizer model from models_dir/recognizers/
	Model string `json:"model"`

	// Texts Texts to extract entities from
	Texts []string `json:"texts"`
}

// RecognizeResponse defines model for RecognizeResponse.
type RecognizeResponse struct {
	// Entities Array of entity arrays (one per input text)
	Entities [][]RecognizeEntity `json:"entities"`

	// Model Name of model used for NER
	Model string `json:"model"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// BuildKnowledgeGraphJSONRequestBody defines body for BuildKnowledgeGraph for application/json ContentType.
type BuildKnowledgeGraphJSONRequestBody = KnowledgeGraphRequest

// GenerateQuestionsJSONRequestBody defines body for GenerateQuestions for application/json ContentType.
type GenerateQuestionsJSONRequestBody = QuestionGenerateRequest

// RecognizeEntitiesJSONRequestBody defines body for RecognizeEntities for application/json ContentType.
type RecognizeEntitiesJSONRequestBody = RecognizeRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Chunk text into smaller segments
	// (POST /chunk)
	ChunkText(w http.ResponseWriter, r *http.Request)
	// Generate embeddings
	// (POST /embed)
	GenerateEmbeddings(w http.ResponseWriter, r *http.Request)
	// Build a knowledge graph from text
	// (POST /knowledgegraph)
	BuildKnowledgeGraph(w http.ResponseWriter, r *http.Request)
	// List available models
	// (GET /models)
	ListModels(w http.ResponseWriter, r *http.Request)
	// Generate questions
	// (POST /questionate)
	GenerateQuestions(w http.ResponseWriter, r *http.Request)
	// Recognize named entities
	// (POST /recognize)
	RecognizeEntities(w http.ResponseWriter, r *http.Request)
	// Rerank prompts by relevance
	// (POST /rerank)
	RerankPrompts(w http.ResponseWriter, r *http.Request)
	// Get version information
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ChunkText operation middleware
func (siw *ServerInterfaceWrapper) ChunkText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChunkText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateEmbeddings operation middleware
func (siw *ServerInterfaceWrapper) GenerateEmbeddings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateEmbeddings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BuildKnowledgeGraph operation middleware
func (siw *ServerInterfaceWrapper) BuildKnowledgeGraph(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BuildKnowledgeGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateQuestions operation middleware
func (siw *ServerInterfaceWrapper) GenerateQuestions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateQuestions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecognizeEntities operation middleware
func (siw *ServerInterfaceWrapper) RecognizeEntities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecognizeEntities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RerankPrompts operation middleware
func (siw *ServerInterfaceWrapper) RerankPrompts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RerankPrompts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/chunk", wrapper.ChunkText)
	m.HandleFunc("POST "+options.BaseURL+"/embed", wrapper.GenerateEmbeddings)
	m.HandleFunc("POST "+options.BaseURL+"/knowledgegraph", wrapper.BuildKnowledgeGraph)
	m.HandleFunc("GET "+options.BaseURL+"/models", wrapper.ListModels)
	m.HandleFunc("POST "+options.BaseURL+"/questionate", wrapper.GenerateQuestions)
	m.HandleFunc("POST "+options.BaseURL+"/recognize", wrapper.RecognizeEntities)
	m.HandleFunc("POST "+options.BaseURL+"/rerank", wrapper.RerankPrompts)
	m.HandleFunc("GET "+options.BaseURL+"/version", wrapper.GetVersion)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9/XIbN/Lgq6CYqwrlHVKUZGcdXm1dyYrsaFeytZK8ye8XuihwpkliNQOMAQwlJuX7",
	"8x7gHvGe5AoNYAbzQYqK4+xWbapcZXFm0Gg0Gv2FRuOXXiyyXHDgWvXGv/RUvISM4p8ny4LfmT8SULFk",
	"uWaC98a9YxKbF0TMiYYHTe6ZXpJcKGbeE8bnQmbU/D3sRb1cihykZoAQgSfTeEllG+jJkkoaa5AhJCIk",
	"WzBOU9fREiS4zoEnivThIU4LxVaw14t6ep1Db9xjXMMCZO9T1GNJu6Nr+FgAj4HwIpuBxFEsPdT+KCIH",
	"ETmMyHA47IAZ9R4GCzFwTwvG9dGh6UhpKvVvNDKEpTrHY75td3BToh8LroHrqq3SkvFF79OnqCfhY8Ek",
	"JL3xT4YuDlgN9aianw8lCDH7J8Ta9I7scCL4nC06RonPC4kTT+ZCWpQYXxDTMyitiBbkBmTGNJDjy7Ph",
	"hN8smSJMEUoUy/KUzRkkZhBztkAQZmK+v7m5NJ+TAUnYfA5SkbkUGb6bF2lKEC2QFoEJv1+yeEkYj9Mi",
	"AUVyKVYsAUkUpBAjcpQnJKbx0uAWh2gPJ7zFsRl9mOJIlB3znBap7o1fjKIGAS7oA8uKLGAr28yMWoIu",
	"pIENDzTLU7Dt2/ObiQTSWj+9OXsAM1sbptyMAVuZbgoFQ3LK9BIk+Robfo1kROIC0eIO+GBGlSGyaxwR",
	"IQl1IDjNwBIXf6v92JJW7f9iXn3aH4ZDKFFr8FrUEyuQKc2n2OFjdHtb0ss1y82YbFMyA30PwB0pHyeg",
	"gpxKqoWsE3HCcWYbNDQLr2yAhMIRlbSpDdaBaI1VU7kA3T3U1lhv8ONQ8thh5uCWS32EnUPUSwlqKdKk",
	"1tlo+CLqWpEJirqyDY7y3du3P7oZJv3RcDQ4GI72wp4RmJXiZppTQQORYpFHkdItIa7scjfo1ZdSXIqO",
	"/yFh3hv3vtqvVM++0zv7oZTZLPLM3GnRJlqvEimp4AuSiLjIgGuil1QTDpDggpwBUXnKNGFcC6IymqZ+",
	"CtRwOHxUgCJWHzZTQOWCK0CN5zH7pWdkDkyXTPfGc5oqiHpesPwUasYDM+9Gc43qemXkiVGOEUUgk0pb",
	"zA3in6IaqG8dqIM6qG+7YSmIBU8CYB9KkeQW+6emeAzG1JyjH5aAkkiCKlJN7qkiCuQKEitisGVF6JkQ",
	"KVBuegjFbc3ukJKuS6ujFAlMQ6Z24qpexbPUwGqI3LrSrglXGuuCpunaiNiE9DO6dsrIjsVpOEgIm5M5",
	"TdMZje+IiONCSkj2dpGaDQYrR2fxiwJCd7JdubTq00NzNi1kx/jeX517y8erZMhmkCSML/ZLzWLmi8VQ",
	"w3+pdT7e309FTNOlUHr8cvRy1AvkRSFZl6A0JDGcmUsmJNPrmvj6qSc4fzDmVUp7UW8hzCjrGL+y7Ylv",
	"T4Q0at0INDtHqaAGe2uOCmxGU5KAGQFROcTGvJBqOOGvEdUxuXU43Rol6H+MbYtbZ5O59g5TFB63tNDi",
	"dmg0gqedlgwUAW7/R/POIGcsjUJBuFLpirKUzlIgrr8/2R4mPBbZjHFrP6G0UkWeC6ltaxwj9vnsmSOF",
	"evaM9BPIDVUEJ7OCpQnRdKH2xhM+ILcLcUsG5LKQQN4IY5eDRG3Qp+k9XasKlYicXL4ngqfriKhU3IPS",
	"ewjBTIqBgRrjquCaZUD6jk8VGZjO/jLBuYveXd1MehGZU6XL9g8pNc3fiIvzH8mP58cdbR9SGv14fmya",
	"3ly+3z95/93x/snl+z070u+QNurZMzsiJDwZkONCi0ECGmJNZlCjat/NlEUgLhLE4O0/zr47OyYGOnlz",
	"+d6+ExKyFMHlxjw6ERIuzs3ijt9dO2rgcp+tkQAWos4LOySxSMGgTPr+ox/Pj12v9pvXQsZQktYO6NSu",
	"o3JEP1nqmeEjLewfCzHpfTAgbuTa84myjG1IUDGltiZtCGpsxlzCG+u8sD/sO/+r7OFSghFjby7fRyi5",
	"sDvD5SeOTCVYJFejtaUVIubIR+MYUrD29KRm8v5UoWcXusGtF5WIuYf2LysBStHeNrsaYtx5PlMFceGl",
	"yzZ9QLmep+vBQkxTNqPzqYolNYbnVOTAjdQ8sQCvHbzKILkDyKc0ZSuo25ijloH5vbi3RogWxLTyNpcR",
	"VEZVcJJBJuSa0LnxDlOqtGE40n+XpjSjA4M21WyWwt5wwi9sYyoBecB42LFVSdwBtGC0UeiJd8TEnDBO",
	"Y81WTK+HE/5eoTBIAkcNReGk9yKb9Ej/BckYLzSoPTPPB0vz7IAsRSHxwcj85rAC6bqNCNCFQd4KX4Po",
	"D0vgRAHaZ7aFkERkTGtIIk8DMwyHNgJI18RIPGOjFDnKzbAXo3NTWNB4TWawpCsm5N6wzl29F1mX1knF",
	"4qmskIrFosEJburRFxQctTrXU+/X1g3xHfzCEkQglEsnmaZGAifDCT9OEua0WPn2npklCuRjAQUkpMgN",
	"lQ1e+GCq2M8wnPBrS/0RaseCp8woqaSSjQ3aPe/0RenD1NJ+aufsqcN0M+2Zv8X1imVFqikHUah07RkH",
	"2RcRNlapBGP2JBGqwBTMCpEQA9feFLOqn6mAUc6v3hMjHw1ie7sQg7zj6ZrAfG6E6QqM4uekWuYGOhd8",
	"8DNI0SDc0SbC2SFOs9luRHMU6TNOLl7tOVce8XWDsrTsphHNcykcmTaSyK44T6SdqFJ6UpzQZMWUwdB2",
	"OnD2sMN7wgtFF0Yd5ainBHfTYrhR4WI2BrOGLBeSSmaI/RADJHYgK5oWhml/EPLOsL/gC8USIC0GdC46",
	"h8FCUsZtqEhLkTbZefTtN5smplomT2XnMIqFUCyfbJAJAfNWs+aWrXk3L9I0IhzuK7hm1gy7vRgdkWtr",
	"eJP3vLJsUMtegZbrwTFK+iXQBOTmubSdPcLnm/CfFKPREZBRg7YHo82Bq6nSkmpYeN+jFF+XjRhwkRlr",
	"AOV+L+ql9Od1L+rNRMETSAL3ppLi9bm5BDmom/yu4zWGkCRLQA3JBc1VENfCedNLYLLVqlKuXBiRbNky",
	"ozmuQjNtjoRVPzaIJkIxgfbc2Tx48henL/0EjOu6kvTNH4Hai2o6b68Fz07JaEwMxRpQBCcJZJQnkWvu",
	"rAGWpIC2NLKgD/QtjS/uxzKxMzHphUO3o0H54q2LSj33qSI5ldosi1xChS1+X1fcEYEV8KZMdUMh/Zxx",
	"HmoFxBUlD+pBRTL2YEZpKWdECQ7eCQRmV5WiGZBctATBL73ZAgYY3RkAH6wOhi9645Lv4qXgd+ve2DJg",
	"VzjL9jJNWEdU/xVVQBImIdZGMBpJRBmvIgaqmPm3zLCj9xQpui5MxYZVlR/IXIrMOgS/VJ1+2rcuOUi1",
	"b4ztU++gl8G7yi2pNSvDtqZVPZKxuZEESatWV/hrp2axWHD2c9UQf6Nx+UhTlDRGQGjhGv/dPSEL4M6H",
	"aAKZ8O8CV/x/7w+1Jey+/85YnitGyYrlIPeGZgmZZa1AR+iHoZ+sB4w3or2o6rywbRqXrX66bE23FNq8",
	"cs6ULi2iShq572srq9P0v1mCgg7LmWUZJIxqSNd2gXkms1tIEaErwZBhMPYwcMKdpFQDj0u55zBSS1Gk",
	"RlXreEn0UijAZVlOWMCNpA/DxdA4BK0FNukZjHe3qEi/Js1Md03z9KeOZRz14pTlgxXTuKExyA3WR4dP",
	"cxodPaaaZSAK/Zg/520CjIJoQe4p06hyqVfiGJIWBmsNkduDMqNy9oL53jTe6ocdjZR1sg8y+7/1uQRx",
	"WEYksOKvvLq2BhXunBjh6b4NbIrn5A3VcE/X5Ma+a7L40aiTqdXRNJaQANeMpurJbvVR5UYFUJrRTh+m",
	"3BDaNI74JZW6cyvavrb6CIOBRapZJhKaVhFN0seQsZCEZXSBm8WCw7s5Rt63jecGHnSIwKdo+/dnBvz7",
	"q/Namw+foh7K7o07I4znRcfozszjcoRa2AENyXUVGJQAjncU6o9rxhcp2Ai5ncQxuZ30lpCmgtwLmSaT",
	"3q35sB5Mt5+qMYZ78GPLe67Fh3qTkOaK9CuK7xkAv0xwEic9w80GugVl/zLPHPxPEal9ilNj2MB+H/wc",
	"mw/dX5NeQjUd49v9nC/+p1n+3zyPhsPhpPfpk8G0LjuCofeMDxAvGUdfUhptbViuYoVGpkCLlqQ/o/Hd",
	"PZUJCSR0x7LZvnXhqL0R2s4SbGM3wSJoTFZtIai9nfdPaouggceHzfsob41p5jYavP5wejDYaG6ol5pc",
	"6pL9bbrIgsdU1506LQto7cC6DwkuObOm5kw7hJBSD5qkwBd62bE11ZBafmvGrt4u2eVWfeduYCmcVG/8",
	"00+j4ejg8CgajIaj5y++iUbD0Z9ffvshMs8Pj57j8xff/Nk8f/nth2Bbrk2d1hZd2NFGhqlE5QptVkX6",
	"ggNuTFtKWVrX+KX847Gt4rbm3XEXzponGMUwor1E8qkMsmHiAsp0zp6UNpGgQU//uI4rfk0yUIou4FEU",
	"LJCuXr0K6VAH5g3BnTtJjBQk76/OWgkrm7f7qkakv1GI1jcruz9j/3j17up+9Lc3C7HLZvkmzd6lLDcM",
	"2guxGheQ/rsc+PFZYC07XbjXokqpTR4TdCX5Sy6tIhYVkA+PJgiYt1Fni4oAf3vzqmBp4nOXdkmquuPi",
	"PoVkAWQhab60m352RdQHnEBS5Ckzsm4qIUUI6lHxeAWZWAEpm5Ky6ZA4v4uYdp379hnjU2Ph6fU0LnNP",
	"HgmzMY4mdfW9nWIDBd1m3+loWNtj3ihoDA4e58/FomPsu6KhWMZSKg0pNuXrvHyxCY2qcZWeU5FlTSQo",
	"kRaYsBYg9vLFTphpSeO7aS7FCjhtUqZbY9L4jsCDaYhsWLXdgSfMk2lWKD1Fv3IHBsQ1VHKA0dBLunIx",
	"HgMNNzxALh7v/VPnkjtNFrAhNylglQ2JVCoWEmpJU49TPJZANSRT2p0jY0NYuKTvqfL5PLZNCD+hGgbG",
	"r+uyf7oSXd9z9rEAwtDrmjOXK4HuoemtO4JRSx7pDOB2zdqxnDEtqVyTO1gPMKBPqNaSzQoNgVtZzUOT",
	"AWt2tyhkDMqajRhHd+twyfJd7dW/vbmseugwOBT2Me2i29l33mC1HxEuEiD9JdDErcC9LYmA2yFqlwCI",
	"EDVl6VaITv00V0hFDbsgymDM3IbQS9ftTk2p875SESMTMj7pdXZW5MkTuBT3qjORYMbujlzalYNcTUNI",
	"wMirz2BVduvPC9DU2CgdC3qXVWd1qBnQUxdcDWAT/rsq+ah63AXEJSdOY1HwDjyr1Fj/JeYzx6BUmEIW",
	"7MOUEFmiuvhQ2ZC9A1GBfYrT2TNcsAnlG6FpGuyamW+7c9k5zWAL6WwusssBb1g9XbQ0S2pXpMy33Ujt",
	"tAoqrvmVy6CDkd+KpEsrUS44i2k67abWpWQZlev9HJN4JCQh2ZhywqWLXNv03fFiIWFh6BBaRF9M9aEw",
	"/N1Un+mtC4xZBpWJXCNHmhJVyDm1ZmGmbHaezZvCTcWQ0rsvo39PZdseyOeo2W4Vdmrt2LryykEqwV2u",
	"mlxQzn62SWSV/sJfv157lYz2W2mvxvLcXW1d1iakseaXVE7FfK5AT4En284T2a9coirq58pKB550i7gQ",
	"Pu4T/doeZrBgvLuP6ivcW1GaZvk2s6IC6nOmd17+rq2Q020i7Yre17w7f4Ao6NkHhR6XalWXO4atqk5K",
	"bl+kjIOcYtxqA08728jr6HY33/mzDca+lCSnerkFTvdBine1Y2gqpy73eM0gTXyGTjWALfAfSzN3xnSf",
	"zQnNMbzQHTvv1I9e/78xqvczD5g0oy5mRm3UIqWzMs9tg7xCh9TRg/TfnLO3p1fkZ5BioJZCk7enV3vD",
	"CXd7zu7sWRLZJHAbZfaZ5K1NTisAe1FN+vWiUvT1IlwJT9vifCQsHx4dC0IM+97lCqa+2nbCjaar01en",
	"52H6QhjKl5AGe8QSZpAOUmPeW2Ge1Z5gZoCj5EZ4VZJBcw0NcK9DU3WHoGrhy6CfLs4tA0WbJr7la3VO",
	"fwexfjUTOBeuF5X+m+cAdN6McgExFfOncYFZ3Kr7FFVtRGXUhfKkcrvtdBju8NHGDUZ5MI7TVHByUag7",
	"4kZErnMaw4+EcXI4Gh0Oe1HPP1GYyfaxoFKDtMlA39N7vRSSQ0ROaMrmQnJGh08Z9IaQv6XEhx1kTLVp",
	"0wj/o0eznVXwG5+d1KbTjqYVRqq61nTg9G6HULrHu0qCDp21ydnaLCfx7WePHj2iXae1JInHLXLz1DXT",
	"Ntlv8wz79KkOV6BMxoybWVXuTE157nhiD3pZ3R4ucHf8y2afDTJjVGi3f4WSLGV8UdB0cPC0JV7unm7D",
	"GpoZZLvtwXYn4LSeDdjLwUf9RLS9LbUVbydoy49LqleaVwZ5Z5gpGxdKi4xY0d6YBKc5EPte1FIkTxtC",
	"LY1t2yiu4ePhNXwkYYNNE1HPjWuwUEr5QL8o0U+zj4uBbzCoUueemgxV6thtg6g+20VZN7jIsDqma3HM",
	"wEyY0izFp/ZBbV6eiH26HeuWit5uu6B50+CaujURGjFPxdVlWm7HuJ6A2V6PHsxgdTjIjj5DN5byLkQt",
	"lCh15mhyfJeI9YmcbywzwvbMJ7Up9Ul7A8UxtfXc6qS4kZSr1LzTgrwBmVE+Jt9DmoqILMU95kuuRfG/",
	"flO7efNSfsJKbi3k3bIWHMl2I/smHfc0ayCQKV37FN3WpUcicdPYpz7ZBP9QEallmEQ2aSlP7bMZ0Kw7",
	"2+Rxa/fzDMErz+vWnOmwAJ8QlXFbth3VaoIjFV0hFNRbj4TOLk+vIvLu6k1Ezt+dROTi7Pqknr5xeXrV",
	"6bHHQu66z2lWVbs+xLff7rQL/qTwkiNVGVaquntaKRwHx5W3qYjxV7Hk5DpjXVGSrvIOfg78OLA6Ts9T",
	"byvnbBR3mxzNE2usONTtV12uptNZgqfr8qhloYyWoDUXOjIij8SUu4Pva0L5uqRMw5GNJhw4nRnDsx7K",
	"QENKFD4/ToKW9oxDl3dbHlL/WpXnZdxA8OiZwpNQG0IemMHD1zaLJSli/SWCHU3TZWfLpWW47CoCNzvY",
	"bT1WsSe5tyfhtDtlbnxle0T9jMdD4y8zTk4KZCsuvqxXHLD0RofYjWlbdqFlPCv3m5mFpvNuSb/NQWxK",
	"6V+fZLhB573tkp2bEgk9CbpJaGyqjSLhUaat2YEdPOuP7bSSIhsGYne+R5Z3Me6lNM15gvGYqoaOZ2cL",
	"eUiwDFXK8CSzItKyiM/DK21tvphwG1AyAFlYlWfOIE3UvoYsNyacIjOYG80T0zQtDzMAT3LBuG6JjzOu",
	"rbTAkhmCNJO7bXLid3j62D0i84In1PRNU6z081RXT667SspRGS8JvvWZY7CiXpE2E1abaPp4uN1/3JXn",
	"LC7VHG5jvd/GCixZcaNN0R0XC0gBweq3iEc2s8vVS1FWJtTEwVOzizfQyyHYRabmKY/uclOdOaitvMst",
	"9aqaBzm25fz4lNNGoant2aYbq1L9A6Rigm9mBAzs4l5dx0lHW1em3McLWflwdPh8MDoYHLy4ORiNj0bj",
	"0ei/u4a1YHoaiyzrqhP1hhnSmHdkSVUtjtyjs/jg8Oh5J0gxXdlhdYAURLpqNf6bEOpCHAwPX2AqZwvs",
	"Rpj+bF0XwNXBcNQFrjFNVdOAHlFI/NqwumayecDKxyGrY1Z/1Oz8o2bnZn7ZUNykfWTVflevj4mirzxj",
	"aksUqBa/pLCC9HOLrpwjEJyltT0v8znQrhFI59bybojUToaa1dI6HOoJtgI5MyyzJpYOUSnKE5gVC4zf",
	"YPN7aiuC+oMglTRxH7RE026jrKGKh5Y5TTeiKwptbHC7/AkSe0i+9s1s+dBYpEKyn206mBIpROTrfyrB",
	"XXFRLYtYF8ZQ/Ov1u7cR+ToVi3mm7VtbcxTmcxajmXgH67/YlKWcMqki8jUXIvdlSlPgehiQLED/n8pt",
	"hhvYuM0j8jrZgo8fJd2Gc6nt+nlxDEpN72Ddmdh7/MM1sZ+YgZGz74KzmXewVtrYsmrNNX2wI4RYgiap",
	"EHdFPiSvaZqqsuDW8Q/X0+OTk9Pr6+nfTv9revYdAb5iUnC0lFdUMgwMs/I8e70a61oUcmCRGdzBesA6",
	"7QtvS3fI2KPwHI3/zu+2f62OhjSjPwtO79UwFtnXREgz1b4K4Lej0chO4wXjZ+/qcahm4x4e1Di35+zG",
	"B13mJFJqWtG/m/iOoNUcfO4EXJ+eXJ3eBPPwKybBdhLMRae9DEphfpRZIFvyYO0o8Vu7mOyycrV01iQ4",
	"nP2ksXehjb0MLEZdSXYKpkqlj57hOOV2u+v6fP/m/Br7vj4ysoPbanWqLIkyxqMb+MXxD9dYgK6sexTT",
	"tGKlXY52/MqSbu01bwtwTQ1bq66sNaYhdRUd3LfEfItVFPbPLm2dopTxO5KIeyyDorAMBWS5XkemDX7v",
	"ark5CMYsglyTXLIV1UAMHDYns1TgcR18OGW5rdUqC9gb1n1h96dbXXHCh/UnB98eDkfDw+ETt5U9MXKq",
	"l7sSw3xLcglz9gC+aFMK4/19TCtRR+av91fnLaJgHyFRhuR10LhQQOgMjz6B+9YJp/33CqTaT6im+3u2",
	"ke3FNJkV8R3ofYuPb5GtB+55keME7TfpGcI04qrV4Gl0bM3jo6volWlRqzpVsQaRlC+ML31w+GfjeQxH",
	"+y8jcjAK/v7z4fDgG/x1cBgRM/sH37y0v7+JyME33w4PXzx3v/c6j2555vXlMaa2PHAd86N2jWtXesLM",
	"O+MJW7GkoGm5FIhZai6viHHiYYZF1UaoHVhmbICDTYW8SuwU+xmms7WGOmIHo+cvX/z5m9HGyl6mnT1a",
	"ce9Lx3kHnXFiAdZ2aUp4JXKjR3wNxvU3zz3C9ihowjLglYPpkD0cPX+5CU9sR+5Zopf7S2CLJeKXswdM",
	"gLDH+MuygBLMsOoVhy3wbRRtS1PzCM1Qm1WpaYwWgz2F0DtGSduL7FljrAisxvv7C6aXxczIG2eQJ7N9",
	"VzWnXcTLuxG2wJwre5OyO3Civ6qMiEWjZVm53BWwvziviuJN+FdfkR+WFKOQDnBYnddtUiivVc4D6Lao",
	"aolBYAIdX55hpuOzZ1XhpTflRuizZ2OCUR0sb1eVW+ifnJ9d7rUybSwgbOALMhkI15BRrllc5RMhPmGF",
	"dl+WfoAM64tLW3hllSYDq4q0SRi4uKNT/BietHW4HSZvaQYJcbuJQc0mA+jUbVbY3RkVkTAhVUXEJ6T6",
	"ixjgQVugZfmmOpn8RnC5Wx40dLtXfj/dE2vCv/PyAis/Ug1Y1zAFarSAJp7nLKMNmdhPRKz2S4VbMgVg",
	"ZPi9gi7GiCknsuDGfecJTQUHvA6hqm5GObHMTuK0UBokcsQ5slE1SQ12MtIPHjRItN8uz1xhROAxAyR/",
	"m9du92nObPbVbWV71yKN2LLkl6oEup/lq+M3JGc5pIzbXkJ+8HsIKJQzPA+SeL74WNCU6bVpcgJcS5qi",
	"r+fKmBkvny8IjaVQiiRMuYMmiU3zM60ujV6K14Ncgv+8tsSw2IArC5cCXYEixuA0X0hauo97bspeAzU/",
	"3Qx+RboWn2U3m8dnOCxcL7UCa77Y/MayahbS8eUZgtltXvzas8FUYquJIx6vGDc2eVnxL0KX2I/kopIS",
	"zlB30sICtJUOyuEiQPOaBNUv/4l8YSZ/YPVCJWdUTmNwkHBfLcQL6zaU5R8U6d9uLABxu2fWgLHPLDBX",
	"Y+GkJIoB+F6BalSWcSGE/u2vKurjyvfcOlqY9XpCFdbJJpYwllsjgow4sGSUoCWDFU0jsmLKmBnV2XlP",
	"9ZrMbTLO60qyloupVR59j/wp5LAABvnO8dnaADveWNpvY30+C+vEXkZjYBwObP1lcnNz7svCYul/++Vr",
	"J/4R95rz2ixm53dv5pSl5Voq9cWuYwgXVsdAgpqBXgMY8fRzKfqP65WqDdd8tJ9UhWnZvCJ1wL+meW0b",
	"EkWe2+0ifbftuKQ8SY2XwSBNwgR83CtMWQxuv8ObLmlKrowRpcgV2OsoWnZMpVNSWFCMQmqm7e0i1fVF",
	"vWCvoLc6oGm+pAd4+411N3vj3tFwNDzqRb3SebIzjy6nUF0xmDxlxtY3I+24mcQpS+WVQN00aKQke7vo",
	"olSphgOQ4auakG1et0XEWvcF4W0purpewV7VYz5+70sT/qVMeTaPX1NlbaMEbGCOKc1ijwby1UW5nNpm",
	"UFlg1QuZcGEPyMU2WR/sjtdX2pNXDHEr0/y6suYT+qe4IsNa1kY2H/rS6UNsBhgSLPPBZ0Iv/dVWhiw6",
	"2BH0U+UuBzC/bm9v/6mMovtlwkmtetqGC25QgEb2Y9uNFbGcEPMIh2YBuEmK/KvaDUbmkxejUfmyfpWT",
	"fVu+LC9PsoAnE27+9czrTxP+CUeB67D0+c4Sf7fKjd3JcP7tK5Gsva/hzroFm+L7GPwt76bb6a4Xn2/x",
	"qb6PYjxtfGCVN67Kw9Hot+7b7bNi5107wciWCVEFxgjnRZpilOD5b4iJrV7VgcEZX9GUJT60YPp98fv0",
	"60xi59CB+zDqqSLLqFx71uiQfwoWtk6B+dzaY5ulqPc3lKtlFtjQLioRllW0MjVtmPTK305XGuNMBVX6",
	"nJuG9uLXqm4mOkPIhmkfdGSTX4xDwBNFmNt7bZeuCpxId/MLwghMwLZIb1wKsVUWhsWEq5Kzrhap8bLs",
	"KGyLwAvRgmCEr6pEHmDjvdoBltbNnGHlw2ytIyJ7Y3IcY5wzLITorJFq/E04aCXXmxqauuDHitHKtHUk",
	"qpnAtqZ0UCoTCeaIDMkXLZzZVdJ3czHNnepnWlv5y1TP7KiptveZujC47QJ3KuLwPguKVyyV9caSCXc2",
	"Dk7HPMV4l62VvDIgJCQFTyjXmCTpF0TTFzOPy72QMq28zL/B/FfDNY6hbCF9d8VQIPhErEEPlJZAs9vS",
	"u1MgmfGR7Za49/UikgmlSbnTudeCZsTo7Rg9Qp8q5+RIcPsiiorA5Q/tAsvHhuvCEngt7hq3rYdA+3cU",
	"bHZWA4pF89FPDbbHI7uNnLVJ70Ol4Sf8orPobpuVtuPWWdK5Cz+0Px5dJ5TkS6EFxnFITLVZNB1NP2/l",
	"uFqIbgEZ8B+2mD5eNVVe/heygWr1hn9nG6he9dT0vWlR1WE29j9wtQ38aoOkXaM0rNYww887smhadkhF",
	"+/JY0b+PJfZ89PzL9+uqvgttD2f/W1mAZbA4KM6KRl95kNieI95o/bnotdpwmH3J8jD8bN5h/p1xqJrF",
	"NVE4t4suOqn8vbgnZ5rgtTXm0cGQPHvmIuqnZSAiCKirevq/RaCvCtxzsWja/Re1N+GHQ4wxumOLdXiv",
	"mbEk60PyN+X6Lib8KMDnqsTetL8Aaewm51JXWFnV+1cqxeAHxu/Q8A7c7ucGIJ6OJ69cIQCMUWLBJuWO",
	"ffc9tD2ry/AkfL+Gqzcorr0BFhi0N/fCF6VALd001FwcC4tPOOO3fwWxyDLgCdhrSE55MtBiAMG0h+c+",
	"fRDl46GCj8HRtjCusIs9LSG1YYXS0jgcjf5UdWkHIArt0xVn4gEtv4YdPSa3wVHS24jchkdLb119dXcs",
	"3A7wAb0DHMiY3BYru4mBi0DtA76dIoxhvr71RHPng6qoy3+XZ338+YxuitnNBHdvY/2cUeOiyi5y98tj",
	"1W68e08ndHDFiDeJmnxtbXywixlk4448XL0rCFZgs4aXqzAqgaYDtHscUdAqnASnc6yVYH67v4b+Ofl/",
	"/+f/2tKkifNerU9hFgburvhcSjP3QZHX6nbmKi9mNHz5AgmF5VdVUHTV3jiRpr4nX7js8RhSYGm1S6dE",
	"VZxJBUbW5PFKHkEo6ckVPWyw6IPrvFaGx1miu5YFi6yFBpOeh9ao7uLg1WpkhlUxI7yZoMRaNSzcK7zC",
	"fZOWQC55awTgmFQE61vk9yJPsn44gr2oIgrp+5HshfSpPTbExr0060CeGska9jb4yY3tw8Bd3mV7LXsf",
	"/FSNt/ymRKHDWkUpX6+L8oXM1e4CT7+z3bqhAkyHIfO3jirc+g8b8l9oQ5rej75870bxucR3UgR38/W5",
	"8NtZPmMekr2GaWsP0rQFSGkMWkO3um1zAbrrQJUVRClTGss20nZ5l6jc1oiqzf+IvD29ilDJt67XKncg",
	"fIzQxvba23/d8UTz7d/LfT3MkuVa2cLdtwP28paoYj5nDz6S5HZlbCfHmyrnkL6/qgsF3mVaKDzGvBWr",
	"cMfHxYbcHuUOQ2rsZ55muV7bXN/27JbgS+Nkpw5qpsyAnPlRNwqgCUk6a9u4Xv8eFpWw/dZTaNpdN25b",
	"Q9viRURenx+/HZg/Xh1f3VjuOL/4+5syV6fNK424c2C5GVPQLY7wJt/YX4PZUjDnTOkLX97ki8n1Rr2n",
	"TcJM+XSCf1U44BX999yUOe+K/ltZVTEVPL4fE+R/1bO+ugoi9TuYE3Q83GtvgjzNm+hYB42lg2ILeCwS",
	"kEO8254kgL8GjDPtHtm97eojzFNW1s6vbxPtsJ6++oqUKS9+W+WJ2XSUq3uQA3+JER6vKQHJ9SYoqjq7",
	"XAYmyrLgbZ/itZCdQ6kG6pzare5HrfDNQH0saDL4uKhHer3BvmiOd2zvpo2XqTNhX8FaGMdow2MjilA6",
	"KXKqNSV/xdsOGScnNGFpSmOU4TJRw5rJvzF26+flS4VuN9VO+p2t4Y21hDZtav8RTP0PMoQrafLr7eG2",
	"JLNKpTSSNquU0upSuG2WVHGd/qNZy06PtHKQ0XCTretrh/WI0806tyL6GnOGZUJOxNvz81ptHZc2fnl6",
	"hUlsiJC7ZLUsXhsGlFzS47urN5iFGuJdNbC1YGycoqoGUzY+f3diGp+Xudllw7dwT/5LyDvb9LWkPIay",
	"2cXZNba7YCqGNLW38QdB5M9StS1rt4yUfmw7C317hzh7idp0r0uRfl/godXXNAby6vTqxuWmteesXVHY",
	"Z1TEXYWWVozaBAj7+5bkVNIMNMgnBdVqVYK6Imrbavw0J7ZV5me7cqqXw2HwpZRTq8TV76yV2vWIunb4",
	"vDBwYeg/VNJ/gkoKbx7/1Tqp5K+GXvGaSdJt+btX9uANKJJvzFwuM1urIkFaEOqqB9VUUb0CqFdEJzbz",
	"+cpXW2JpKauDekxZofQYNyX9cR7Xny+61DL1D4fkCjHGIEtZkgk3Eq+BJx1j8hfZUkVu3fhuywv8E1Bs",
	"Ya/9VuHN5BpSUHa7093xb1HGM45WPhv6V9WiUrFg8fCzdVEttNOhibzjaVtNyxeoj+zBhHo6u711p1OZ",
	"1XPan6JDWnW7SkWCDGK/2lpBqmzgZqS2m9MsmXXhIJ07SGOCc7coWALEHgKoMosNAKym5b8mr4NqWmPy",
	"FgpJU8JBO+0mARs3smKsF+k5r1TinttR1Tfz+bF6vi36gswyUCyBCb9N2Wy/bGoUd3yHxyWXLF6WhwMq",
	"Vnq8vFhTrRrQl67E1pdSqWF9uN9dn9YqhHWIVTd4N0F/qNL/DFXqF+NnKFIDotJ660rfWV0aFNraus/R",
	"qLsVkUVZLyyyu/1Ym8wG5NqFv4YdcRz9j7IQ1xdbWM2Sax1Udp+E1bf+NbHmhleuPe3qmOFnyI2q47L8",
	"4GSU49nyXNU+zVnv04dP/z8AAP//qgee1mqgAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
